aws/aws-sdk-go

- aws/ec2.go
- aws/error.go
- aws/json.go
- aws/query.go
- aws/rest.go
Check for zero length responses and return just an APIError with
StatusCode - these are returned when an operation doesn't return
"special errors".
> Include HTTP StatusCode in APIError - fixes #42

- gen/autoscaling/autoscaling.go
- gen/cloudformation/cloudformation.go
- gen/cloudsearch/cloudsearch.go
- gen/cloudwatch/cloudwatch.go
- gen/elasticache/elasticache.go
- gen/elasticbeanstalk/elasticbeanstalk.go
- gen/elb/elb.go
- gen/iam/iam.go
- gen/importexport/importexport.go
- gen/rds/rds.go
- gen/redshift/redshift.go
- gen/sdb/sdb.go
- gen/ses/ses.go
- gen/sns/sns.go
- gen/sqs/sqs.go
- gen/sts/sts.go
- internal/unmarshal_xml_test.go
- model/model.go
- model/templates.go
As you may know, XML does not handle map well like JSON does because we don't know what element value will be used as a key or as a value.
We need to implement xml.Unmarshaler interface for map.
In this PR, UnmarshalXML is generated only for query protocol because I have no idea how to detect which format is used in response.
Once this PR lands, SQS's ReceiveMessage works well with MessageAttributes:clap:
> Implement xml.Unmarshaler for map

- gen/endpoints/endpoints.go
This pull request adds support for service endpoint overrides. To add an override, import `github.com/stripe/aws-go/gen/endpoints` in your code, and call `endpoints.AddOverride(<service>, <region>, <uri>)`:
endpoints.AddOverride("EC2", "test-1", "http://localhost:3000")
Fixes #63
> Add support for service endpoint overrides

- aws/config.go
This is required to let users override the default endpoints, for
example when using DynamoDB Local.
> Include the Endpoint field while merging configs

- aws/core.go
- Add support for logging the request before and after it is signed
- Fix nil pointer crash when the response object is nil (such as when
the URL is malformed)
> Improve request debug handlers

- internal/model/api/shape.go
This affects generated 'api.go' files such that their keys, when json marshalled, are named as they were in the json shape definition.
For example, in ECS, the Cluster struct has the following diff:
```
type Cluster struct {
-       ClusterARN  *string `locationName:"clusterArn" type:"string" json:",omitempty"`
-       ClusterName *string `locationName:"clusterName" type:"string" json:",omitempty"`
-       Status      *string `locationName:"status" type:"string" json:",omitempty"`
+       ClusterARN  *string `locationName:"clusterArn" type:"string" json:"clusterArn,omitempty"`
+       ClusterName *string `locationName:"clusterName" type:"string" json:"clusterName,omitempty"`
+       Status      *string `locationName:"status" type:"string" json:"status,omitempty"`
metadataCluster …
```
> Specify marshal key in json tag

- aws/credentials.go
user.Current() relies on CGO causing it to fail if cross compiled. It
has been replaced by checking environment variables HOME and
USERPROFILE. Fixes #107
> Replace mechanism to get the current user dir.

- internal/fixtures/integration/generate.go
step:
make test
response:
panic: open /Users/nick/aws-sdk-go/apis/autoscaling-2011-01-01.normal.json: no such file or directory
> fix json file path error

- apis/ecs/2014-11-13.normal.json
- internal/model/api/inflections.csv
- service/ecs/api.go
- service/ecs/examples_test.go
Similar to https://github.com/awslabs/aws-sdk-go/pull/191 but runs `go generate` to generate the Go code. Also uses the latest json api definition from [boto/botocore](http://github.com/boto/botocore) and adds the inflection for `Docker`.
> Add full ECS API.

- aws/credentials.go
I have just hit this error and have no way of knowing what caused it.
This PR just includes the original error in the message.
> Improve error reporting in IAM credentials

- aws/handler_functions.go
- aws/request.go
- aws/request_test.go
- aws/service.go
- aws/types.go
- internal/protocol/rest/build.go
- service/dynamodb/customizations.go
- service/sqs/checksums.go
Fixes retry support to not fail due to body not being rewound between retry attempts.
Merged #196 and #204 together along with other changes to make sure rewind works in all cases, Made sure the ordering of handler's setting Request.Retryable vs the Service.ShouldRetry are consistent. A Request Handler setting Request.Retryable will prevent RetryHandler calling Service.ShouldRetry. The Service's delay value wills still be applied though.
Verified all tests pass and used @josharian's [script to ping for aws request limits](https://gist.github.com/josharian/b77539174c0ac5a5ca13) to verify retries were handled correctly.
Please try this out this PR and let me know if you hit retry failures still.
> Fixes retry support to not fail due to body not being rewound between retry attempts. (#204+#196)

- aws/handler_functions.go
- service/s3/unmarshal_error_test.go
Also handles other redirect failures as APIError.
> Return redirect errors as APIErrors with MovedPermanently codes.

- internal/signer/v4/v4.go
`Query.Encode()` will replace " " with "+", but the v4 spec calls for
replacing " " with "%20" instead.
Fixes #219
> signer/v4: Encode "+" to "%20"

- service/s3/s3manager/upload.go
First, thanks for landing s3manager -- I was about to implement this myself.
I've been trying to use s3manager to perform fast concurrent S3 uploads in a backup tool at work. I'm putting pretty large files; my test file is 60GB. Unfortunately, I ran into a variety of issues. I fixed some of them here.
The biggest issue was a memory leak. It turns out that the current s3manager code causes the entire input reader contents to be retained, and in my test that is far larger than the available system memory. The bug is due to a slightly subtle GC interaction where a reference to each chunk buffer is held onto for the duration of the whole multi-part upload.
I also found that the uploader could deadlock because the workers could all exit without the dispatcher being aware; this was much simpler …
> s3manager: Fix memory leak

- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_test.go
Improves memory consumption on io.ReaderAt streams (files, in memory
buffers) by avoiding creation of individual byte buffers.
Increasing concurrency threshold for seekable streams will no longer
impact memory usage.
Fixes #232
> s3/s3manager: Buffer parts with io.SectionReader when possible

- aws/handler_functions.go
- aws/service.go
Only ExpiredTokenException error code was being used to determine if the credentials
need to be refreshed, but there are actually three different error codes which
imply expired credentials.
- ExpiredTokenException
- ExpiredToken
- RequestExpired
All expired credentials conditions should now be handled and the SDK will
attempt to refresh when the error occurs.
Fixes #249
> aws: ExpiredToken and RequestExpired error code should refresh credentials

- internal/test/integration/s3/s3manager/integration_test.go
- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_test.go
In order to more consistently support the upcoming download manager,
move the s3manager.Upload() function into an s3manager.Uploader
structure. The new API is:
u := s3manager.NewUploader(opts) // opts can be nil
resp, err := u.Upload(&s3manager.UploadInput{...})
This changes from:
s := s3.New(nil)
resp, err := s3manager.Upload(s, &s3manager.UploadInput{...}, nil)
In the new API, the client is (optionally) passed through the
UploadOptions.S3 member. If S3 is nil, a default client will be used.
Note that the DefaultConcurrency and DefaultPartSize constants are
also renamed in order to be properly namespaced.
> s3manager: Slight modification to Upload API [Breaking Change]

- internal/test/integration/s3/s3manager/integration_test.go
- service/s3/s3manager/download.go
- service/s3/s3manager/download_test.go
The download manager implementation performs concurrent ranged GET operations against an object in an S3 bucket and writes the data locally using parallel writes. Concurrency can be managed using the "Concurrency" option.
Sample usage:
```go
// Open a file, err omitted for simplicity
fd, _ := os.Create("my-image.png")
// Pass in &s3manager.DownloadOptions{} to manipulate
// Concurrency or ranged PartSize.
mgr := s3manager.NewDownloader(nil)
// Perform the download to the file from a bucket/key
params := &s3.GetObjectInput{Bucket: aws.String("bucket"), Key: "image.png"})
n, err := mgr.Download(fd, params)
if err != nil {
panic(err)
}
fmt.Println("Wrote %d bytes to my-image.png")
```
This implementation does not yet support arbitrary io.Writer objects. A io.WriterAt object must be provided. …
> s3/s3manager: Add download manager

- internal/signer/v4/v4.go
This patch seems to significantly improve s3manager.Uploader performance by reducing the bottleneck from the amount of writes.
/cc @jasdel
> signer/v4: Improve signing performance with io.Copy()

- aws/config.go
- aws/config_test.go
The attribute was omitted from copying into the new instance.
Merge method is simplified to avoid unnecessary nil checks for newcfg.
Both method Copy and Merge are now covered with unit tests.
> Fix copying of Config.LogHTTPBody attribute in Config.Copy() method

- Makefile
You can now run `make help` to list Makefile targets.
> Adding `make help` Makefile target

- aws/awsutil/path_value_test.go
- aws/param_validator_test.go
- aws/request_pagination_test.go
- aws/request_test.go
- aws/service.go
- internal/protocol/xml/xmlutil/unmarshal.go
- sdk.go
- service/s3/customizations_test.go
- service/sqs/api_test.go
- service/sqs/checksums_test.go
Such a simplified formatting helps to improve code readability.
> Simplify struct, map, array and slice literals

- aws/handler_functions.go
- aws/request.go
- internal/signer/v4/v4.go
- internal/signer/v4/v4_test.go
Simplified aws.Request to not need logic to handle request resigning.
Updated the v4 signer to resign the request if the request was already
signed and the credentials have expired. This occurs when a request fails
due to expired tokens or network errors.
> Handle resigning requests cleanly

- aws/handler_functions.go
- aws/handler_functions_test.go
Guards against a panic we had reported over in:
https://github.com/hashicorp/terraform/issues/2202
> handler_functions: avoid panic on nil HTTPResponse

- aws/credentials/credentials.go
- aws/credentials/ec2_role_provider.go
- aws/credentials/ec2_role_provider_test.go
Moves the expiry shared logic out of EC2RoleProvider and into the new shared struct.
This allows other providers which need expiration, to use shared logic.
Adds Expiry struct for PR #267
> aws/credentials: Add Expiry struct for Provider expiration shared logic

- aws/awserr/error.go
- aws/awserr/types.go
- aws/credentials/chain_provider.go
- aws/credentials/chain_provider_test.go
- aws/credentials/credentials_test.go
- aws/credentials/ec2_role_provider.go
- aws/credentials/env_provider.go
- aws/credentials/shared_credentials_provider.go
- aws/credentials/static_provider.go
- aws/handler_functions.go
- aws/handler_functions_test.go
- aws/param_validator.go
- aws/request_test.go
- internal/protocol/ec2query/build.go
- internal/protocol/ec2query/unmarshal.go
- internal/protocol/jsonrpc/jsonrpc.go
- internal/protocol/query/build.go
- internal/protocol/query/unmarshal.go
- internal/protocol/query/unmarshal_error.go
- internal/protocol/rest/build.go
- internal/protocol/rest/unmarshal.go
- internal/protocol/restjson/restjson.go
- internal/protocol/restxml/restxml.go
- service/dynamodb/customizations.go
- service/s3/bucket_location.go
- service/s3/content_md5.go
- service/s3/s3manager/upload.go
- service/s3/sse.go
- service/s3/unmarshal_error.go
- service/sqs/checksums.go
Adds two new constructors for the awserr Error types. Can also be used for building awserr.Error for testing.
- awserr.New() returns an Error object described by code, message, and origErr. If origErr satisfies the Error interface it will not be wrapped within a new Error object, and will instead be returned.
- awserr.NewRequestFailure() returns a new request error wrapper for the given Error provided.
Fixes: #254
> aws/awserr: Error constructors exposed

- service/dynamodb/dynamodbattribute/converter.go
- service/dynamodb/dynamodbattribute/converter_test.go
Make the package name match the import path.
Having mismatched package/imports is confusing and only makes things
harder to understand. Additional confusion is added when the package
called "dynamodb" imports another package called "dynamodb."
Also, goimports didn't like your alphabetizing :P
> Change dynamodbattribute package name.

- internal/model/api/customization_passes.go
- internal/model/api/shape.go
- service/s3/api.go
Since S3 does not enforce any formatting on the Expires field the SDK would fail
to process request response where the Expires field was not RFC822 (HTTP-Date) format.
To parse the time as RFC822 use the following sip
```go
t, err := time.Parse("Mon, 2 Jan 2006 15:04:05 GMT", expiresHeader)
```
> service/s3: Expires change to string in HeadObjectOutput and GetObjectOutput

- README.md
The `Region` parameter in `aws.Config` must be a string pointer, not a string. Update the example to show users how to instantiate the `aws.Config` object correctly using `aws.String` call.
> Update README.md to reflect new param requirement

- .travis.yml
The current codebase is not compatible with the upcoming Go 1.5.
I'm not sure what approach do maintainers plan to take about `internal` package, but it should be probably solved, otherwise it will be difficult for any other project using this SDK w/ 1.5+.
Related: https://github.com/hashicorp/terraform/issues/2893
> Build against latest Go too (but allow failures)

- service/cloudfront/sign/policy.go
- service/cloudfront/sign/policy_test.go
- service/cloudfront/sign/privkey.go
- service/cloudfront/sign/privkey_test.go
- service/cloudfront/sign/randomreader.go
- service/cloudfront/sign/sign_url.go
- service/cloudfront/sign/sign_url_test.go
Adds CloudFront URL signer utility to the SDK. This allows you to sign
URLs to access restricted resources through CloudFront.
For more information on CloudFront URL signing see:
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-custom-policy.html
Usage Example:
```go
// Sign URL to be valid for 1 hour from now.
signer := sign.NewURLSigner(keyID, privKey)
signedURL, err := signer.Sign(rawURL, time.Now().Add(1*time.Hour))
if err != nil {
exitErr("Failed to sign url, err: %s", err.Error())
}
```
Fixes: #188
> service/cloudfront/sign: Add Amazon CloudFront URL signer

- aws/logger.go
- aws/service/request.go
- aws/service/service.go
Adds aws.LogDebugWithRequestRetries - States the SDK should log when
service requests will be retried. This should be used to log when you
want to log when service requests are being retried. Will also enable LogDebug.
Adds aws.LogDebugWithRequestErrors - States the SDK should log when
service requests fail to build, send, validate, or unmarshal.
Fix: #323
> Add additional log levels for request retries and errors

- README.md
See: https://docs.aws.amazon.com/sdk-for-go/api/service/ec2.html#type-Instance
> fix struct field by using InstanceId

- aws/corehandlers/handlers.go
I saw this showing up in one of my projects. I think it's safe to remove?
> Removed rogue fmt.Println

- aws/credentials/stscreds/assume_role_provider.go
Using a pointer to a string to match the AssumeRoleInput type, also not using aws.String() so it can be nil.
> pass ExternalId to sts.AssumeRole from stscreds provider

- internal/protocol/json/jsonutil/unmarshal.go
Check PkgPath on StructField which will be empty for exported fields
(http://golang.org/pkg/reflect/#StructField).
We have an application which heavily uses DynamoDB and we are seeing a lot of allocations in `jsonutil/unmarshal`. Based on a heap dump nearly 25% of the allocations (program wide) are coming from `strings.ToLower` in unmarshalStruct:
```
(pprof) peek ToLower
241578716 of 252105072 total (95.82%)
Dropped 547 nodes (cum <= 1260525)
----------------------------------------------------------+-------------
flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
57705326   100% |   github.com/aws/aws-sdk-go/internal/protocol/json/jsonutil.unmarshalStruct
0     0%     0%   57836399 22.94% …
```
> internal/protocol/json: Reduce unmarshal allocs

- awsmigrate/awsmigrate-renamer/gen/gen.go
- internal/fixtures/protocol/generate.go
- internal/model/api/api.go
- internal/model/api/load.go
This adds an extra option to the API generation code to allow opting out of the `Input`/`Output` names so you can get types with their original names, best used in conjunction with the existing `NoRemoveUnusedShapes` option.
Being able to get the original shape names is useful for ECS.
If you'd like a more nuanced approach, I could refactor it a bit more and accomplish this 'more correctly', but this does resolve our specific issue now.
This also removes the `NoInflections` option which is no longer read anywhere and some leftover code related to it.
> internal: Allow toggling off shape renames

- aws/request/retryer.go
We’re using Terraform for our infrastructure-as-code, and it depends on aws-sdk-go – the infrastructure we’re building out are quite large (250’ish components - lots of Lambda functions and DynamoDB tables), so we’re probably hitting API concurrency limits that most other people aren’t bothered by.
We’ve seen that Lambda casts TooManyRequestsException and DynamoDB casts LimitsExceededException when deleting more than 10 tables at once. Both seems to be retryable, and I would think that aws-sdk-go would be the optimal place to fix it reliably for everyone to enjoy?
> Lambda- and Dynamodb tables deletion throttling exceptions

- service/cloudformation/template/basic_functions.go
- service/cloudformation/template/basic_functions_test.go
- service/cloudformation/template/template.go
- service/cloudformation/template/template_test.go
A draft, and not feature-complete.  Feedback appreciated.
Context from my original issue #393:
>I'm trying to programmatically generate CloudFormation templates.
>
>`cloudformation.CreateStackInput` has its `TemplateBody` field typed as a `*string`.  I'd like to be able to build up a strongly-typed Template in memory, call `json.Marshal()` and use the result as the `TemplateBody`.
I've roughly followed [the approach outlined](https://github.com/aws/aws-sdk-go/issues/393#issuecomment-144875078) by @jasdel .  One difference is that the intrinsic `Fn::x`  and `Ref` functions are modeled as Go functions, not types.  It makes the usage syntax a bit cleaner:
```go
FnJoin("\n", "Stack ID is:", Ref("AWS::StackId") )
```
instead of 
```go
FnJoin{ "\n", []interface{}{ "Stack ID is:", Ref{ …
```
> Statically typed CloudFormation Templates

- service/cloudformation/template/template.go
- service/cloudformation/template/template_test.go
My motivation here is [`DependsOn`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html).  I added the other ones for completeness, but I'm unfamiliar with them.
[Docs here.](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-product-attribute-reference.html)
> CloudFormation template Resource has optional attributes

- service/dynamodb/customizations.go
I noticed that there was a custom `retryer` type for `dynamodb` but it wasn't hooked up. This hooks it up.
Not sure if this was intentional or just an oversight.
> service/dynamodb: hook up custom retryer

- private/protocol/json/jsonutil/build.go
More work on https://github.com/aws/aws-sdk-go/issues/377
Avoids fetching a field if its value is empty. There are many cases
where most fields will be empty. For example, `dynamodb.AttributeValue`.
```
benchmark                 old ns/op     new ns/op     delta
BenchmarkBuildJSON-4      8942          7807          -12.69%
benchmark                 old allocs     new allocs     delta
BenchmarkBuildJSON-4      58             45             -22.41%
benchmark                 old bytes     new bytes     delta
BenchmarkBuildJSON-4      1344          1136          -15.48%
```
> private/protocol/json/jsonutil: reduce build allocs

- README.md
Grabbed from release notes link in the github release of v0.10.10
https://github.com/aws/aws-sdk-go/releases/tag/v0.10.0
> Fixing README release notes link

- aws/awsutil/path_value.go
- aws/awsutil/path_value_test.go
- aws/request/request_pagination.go
- aws/request/request_pagination_test.go
Request pagination was updated to handle optional pagination tokens.
Updates SetValueAtPath to allow setting a pointer type to nil.
Previously attempting to set a path to nil would set the path to the
referenced type's zero value if the type was a pointer.
Fix #439 
Fix #302
> Fix pagination optional tokens and SetValueAtPath for nil pointer fields

- service/s3/customizations.go
PutBucketLifecycleConfiguration() also requires Content-MD5 to be set.
> Add opPutBucketLifecycleConfiguration to the switch in initRequest()

- service/s3/s3manager/s3manageriface/interface.go
This adds interfaces for s3manager.Download & s3manager.Uploader.
Follows naming convention of the auto-generated interfaces and names the package s3managerinterface, and the interfaces DownloaderAPI & UploaderAPI.
See Issue #483
> Adding an interface package for s3manager.

- Makefile
- awsmigrate/awsmigrate-renamer/rename/rename14.go
In golang/tools@542ffc7e7 the tools/go/types packages were updated to
use the import path `go/types` instead of `golang.org/x/tools/go/types`.
This cause the SDK to fail to build once retrieved due to the awsmigrate
package referencing x/tools/go/types.
Fix #488
> Fix SDK's usage of go/types in Go 1.5

- private/protocol/query/unmarshal_error.go
- private/protocol/rest/unmarshal.go
- private/waiter/waiter.go
- private/waiter/waiter_test.go
- service/s3/unmarshal_error.go
- service/s3/unmarshal_error_test.go
The waiters were ignoring any acceptor other than "error" if there was
any request error when polling for resource status. This caused waiters
like S3 WaitForObject to return immediately with an error because 404 not
found was returned. The waiters will now handle status acceptors with
errors.
Also fixed a bug with pathAll being too greedy and matching on empty
list when it should not.
Fix #497
> Fix status waiter with status code > 4xx

- aws/ec2metadata/service.go
- aws/ec2metadata/service_test.go
The EC2Metadata Client was incorrectly overriding the http.DefaultClient
when users had modified the default client's parameters. The metadata
client will now only set its alternate dial timeout if no http client
was provided, or if the provided client was never modified from the
original http.Client{}.
Also updates the logic so DefaultTransport is reused instead of
hardcoded.
Addresses #504
> Fix EC2Metadata Client overriding http.DefaultClient incorrectly

- service/cloudfront/sign/policy.go
- service/cloudfront/sign/sign_url.go
The url signer's policy validation was overly restrictive. While at
least a single policy statement makes sense for signed URLs, but not for
signed cookies. The SDK doesn't provide direct support for signed
cookies, but the Policy object can be used to generate them.
Addresses #506
> service/cloudfront/sign: Loosen policy statement count validation

- .travis.yml
- Makefile
- aws/config.go
- aws/ec2metadata/service.go
- aws/ec2metadata/service_test.go
- aws/session/session.go
The EC2Metadata client was taking a copy of http.Client's Transporter
which is not safe. This also complicated the implementation preventing
custom configurations by users. This alternative implementation is
concurrency safe and is much more flexible with custom transports and
dialers.
The EC2Metadata Timeout override can also be disabled by setting the
EC2MetadataDisableTimeoutOverride `aws.Config` flag. This flag needs to
be passed into the Session or Config prior to creating the credentials
change and EC2RoleProvider.
Fix #509
> Fix data race in EC2Metadata client initialization

- Makefile
There is no point in having a separate target for `go get`ing dependencies for integration tests due to the fact that all tests are loaded by go and then eventually skipped, hence dependencies for all tests need to be installed.
When I first tried running `make unit-with-race-cover` I got the following error:
```
awstesting/integration/smoke/shared.go:13:2: cannot find package "github.com/lsegal/gucumber" in any of:
/usr/local/Cellar/go/1.5.1/libexec/src/github.com/lsegal/gucumber (from $GOROOT)
/Users/radeksimko/gopath/src/github.com/lsegal/gucumber (from $GOPATH)
```
> tests: Dependencies are the same for integ & unit

- aws/credentials/shared_credentials_provider_test.go
Adds test case for absolute path to shared credentials alternatively file handling. Ensures that both relative and absolute paths work as expected.
> Add absolute path test for AWS_SHARED_CREDENTIALS_FILE

- aws/corehandlers/handlers_test.go
- aws/credentials/chain_provider_test.go
- aws/credentials/credentials.go
- aws/credentials/credentials_test.go
- aws/credentials/ec2rolecreds/ec2_role_provider.go
- aws/credentials/env_provider.go
- aws/credentials/shared_credentials_provider.go
- aws/credentials/static_provider.go
- aws/credentials/stscreds/assume_role_provider.go
This should help in situations such as debugging the `ChainProvider` or even giving the user better idea of what's happening under the hood - i.e. where are the used credentials coming from.
This PR may introduce a breaking change for users having custom providers as these will be missing the new method per modified interface (`Name()`).
> credentials: Expose provider names

- awstesting/util.go
- models/protocol_tests/generate.go
- models/protocol_tests/input/ec2.json
- models/protocol_tests/input/json.json
- models/protocol_tests/input/query.json
- models/protocol_tests/input/rest-json.json
- models/protocol_tests/input/rest-xml.json
- private/model/api/shape.go
- private/model/api/shapetag_test.go
- private/protocol/ec2query/build_test.go
- private/protocol/ec2query/unmarshal_test.go
- private/protocol/idempotency.go
- private/protocol/idempotency_test.go
- private/protocol/json/jsonutil/build.go
- private/protocol/jsonrpc/build_test.go
- private/protocol/jsonrpc/unmarshal_test.go
- private/protocol/query/build_test.go
- private/protocol/query/queryutil/queryutil.go
- private/protocol/query/unmarshal_test.go
- private/protocol/restjson/build_test.go
- private/protocol/restjson/unmarshal_test.go
- private/protocol/restxml/build_test.go
- private/protocol/restxml/unmarshal_test.go
- private/protocol/xml/xmlutil/build.go
Adds support for service models which specify a shape member is the
idempotency token to be auto filled with a random UUID if the member's
value is not already set.
This replaces the needs for customizations per service per request when
an idempotency token should always be provided, but optionally set by the
user.
> Add idempotency token auto fill support

- aws/corehandlers/param_validator.go
- aws/corehandlers/param_validator_test.go
Request validation logic ensures that struct fields have appropriate values.
When validating slices and maps, the goal is to find any structs they may
contain, since only struct fields have validation rules. Slices of uint8,
aka []byte, do not lead to structs and so cannot cause validation to fail.
Speed up validation of this (unnamed) type.
This is particularly important for APIs such as Kinesis which can contain
byte slices for megabytes of data - each byte does not need to be validated
individually.
The below output of golang.org/x/tools/cmd/benchcmp is for a Kinesis
PutRecords request including 100 Records of 10kB each.
benchmark                  old ns/op     new ns/op     delta
BenchmarkValidateAny-8     310052182     216116        -99.93%
benchmark                  old allocs …
> aws/corehandlers: speed up validation of []byte

- aws/awserr/error.go
- aws/credentials/ec2rolecreds/ec2_role_provider.go
- aws/ec2metadata/api_test.go
- aws/ec2metadata/service.go
- service/s3/s3manager/upload_test.go
Improves the error messages received for EC2Metadata client requests.
The error message bodies were being dropped by the SDK and are now
included in the error returned.
Also updates the SDK to returned errors to be chained in a stack so that
nested errors are not ignored. This change updates the SDK so that the
chain of errors which occurred are all included. Instead of just the first error.
Fix #545
> Improve EC2 instance role and EC2Metadata client error messages

- private/endpoints/endpoints.json
- private/endpoints/endpoints_map.go
- private/signer/v4/functional_test.go
- service/s3/host_style_bucket_test.go
Updates the S3 service endpoint definition patter to remove redundant
rules. This also updates s3 testing mock regions to be consistent with
the expected pattern.
> private/endpoints: Simplify S3 service endpoint logic

- aws/defaults/defaults.go
- aws/logger.go
- aws/request/handlers.go
- aws/request/handlers_test.go
- aws/request/request.go
Adds support for setting a logger on `request.Handlerlist` used by each
service client. This allows you to provide a debug logging function
which is called for each iteration in the handler list. A default
logging func is also provided, `LogHandlerListItems` which will log the
handler used, if named, and the current state of the request's Error.
Adds support for stopping a `request.HandlerList`'s iteration after a
request handler has been executed. A default `HandlerListStopOnError`
func is provided to stop iterating a handler list's request handlers if
any request error occurs. This is added to the default Build handler
list. To stop if the request fails to build.
> aws/request: Add support for logging and stopping handler lists

- .travis.yml
- Makefile
- Do not fail on example naming scheme because example code is within a `_test` package when running go vet
- Add Travis testing for Go 1.6
> Update for Go 1.6

- aws/awserr/error.go
close paren on log call
change log.Printf to log.Println to match other calls
> awserr: fix typo in error.go example code

- aws/corehandlers/handlers.go
- aws/corehandlers/handlers_test.go
- aws/request/request.go
> Close response body on retries and if a response was returned during an error in corehandler

- Makefile
- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_test.go
Adds to PR #564's Change SSEKMSKeyID to SSEKMSKeyId in s3manager.UploadInput. 
Added additional test to ensure s3manager.UploadInput has parity with s3.PutObjectInput in the future. 
Replaces #564
> Fix s3 manager upload fields

- aws/client/default_retryer.go
- aws/request/offset_reader.go
- aws/request/offset_reader_test.go
- aws/request/request.go
Fixes #569 
There was a possibility of a data race in retrying due to transport trying to manipulate HTTPRequest's body and the SDK trying to reuse the request by seeking on the body. To fix this we added a thread-safe `io.Reader`, that way the transport will be mutually exclusive with the SDK's retry.
Performance benchmarks of the `io.Reader` vs `offsetReader`:
```
BenchmarkBytesReader-4  1000000000               1.80 ns/op
ok      github.com/aws/aws-sdk-go/aws/request   1.978s
BenchmarkOffsetReader-4 20000000                91.3 ns/op
ok      github.com/aws/aws-sdk-go/aws/request   2.951s
```
> Fixed data race in retry by adding our own custom io.Reader

- README.md
Think this is a typo in the readme about credientials
> Correctly point to the credentials file

- private/model/api/customization_passes.go
- private/protocol/ec2query/build_test.go
- private/protocol/ec2query/unmarshal_test.go
- private/protocol/jsonrpc/build_test.go
- private/protocol/jsonrpc/unmarshal_test.go
- private/protocol/query/build_test.go
- private/protocol/query/unmarshal_test.go
- private/protocol/restjson/unmarshal_test.go
- private/protocol/restxml/build_test.go
- private/protocol/restxml/unmarshal_test.go
- service/cloudtrail/api.go
- service/dynamodb/api.go
- service/ec2/api.go
- service/ecr/api.go
- service/firehose/api.go
- service/iam/api.go
- service/kinesis/api.go
- service/kms/api.go
- service/lambda/api.go
- service/ses/api.go
- service/sns/api.go
- service/sqs/api.go
- service/support/api.go
- service/waf/api.go
Adds custom doc string to blob types to document the fact the SDK will
automatically encode and decode the value as it goes across the wire.
Presenting the user with a raw binary []byte type. Without needing to
manually encode/decode the value.
Fix #559
> private/model/api: Add custom doc for blob type doc strings

- private/protocol/rest/build.go
Example: linefeed `\n` charater is escaped to %A instead of %0A
> Hex values that are lower than 0x10 are incorrectly URL-escaped

- aws/ec2metadata/api.go
- aws/ec2metadata/api_test.go
This is an implementation of a very basic check for "authenticity" of an EC2 metadata API as discussed in https://github.com/aws/aws-sdk-go/issues/543
This is how I'd expect people to use it:
```go
func getCreds(key, secret, token, profile, credsfile string) *awsCredentials.Credentials {
providers := []awsCredentials.Provider{
&awsCredentials.StaticProvider{Value: awsCredentials.Value{
AccessKeyID:     key,
SecretAccessKey: secret,
SessionToken:    token,
}},
&awsCredentials.EnvProvider{},
&awsCredentials.SharedCredentialsProvider{
Filename: credsfile,
Profile:  profile,
},
}
cfg := &aws.Config{}
endpoint := os.Getenv("AWS_METADATA_ENDPOINT")
if endpoint != "" {
cfg.Endpoint = aws.String(getMetadataEndpoint())
}
ec2Provider := &ec2rolecreds.EC2RoleProvider{
Client: …
```
> ec2rolecreds: Add method for getting instance identity doc

- Makefile
Breaks apart the `integration` make task into multiple sub tasks and pulls in performance task to be run also during integration.
Makes it easier to run smoke test separate from integration customization tests.
> Add performance to integ tests, and break integ into multiple tasks

- aws/awserr/error.go
- aws/awserr/types.go
- awstesting/integration/smoke/iotdataplane/iotdataplane.feature
- awstesting/integration/smoke/kms/kms.feature
- service/route53/service.go
- service/route53/unmarshal_error.go
- service/route53/unmarshal_error_leak_test.go
- service/route53/unmarshal_error_test.go
service/route53: Add batched error support for ChangeResourceRecordSets
Adds support for batched errors that ChangeResourceRecordSets can
optionally return.
Replaces PR #438
Also deprecate BatchError in favor of BatchedErrors
BatchError did not satisfy the awserr.Error interface like it should of. This
update adds a new type BatchedErrors which satisfies awserr.Error.
> service/route53: Add batched error support for ChangeResourceRecordSets

- private/protocol/query/unmarshal_error.go
Adds support to fallback and attempt to parse the
ServiceUnavailableException out of the response body. This is helpful
when the request failed and the service returned unavailable error.
Previously the error unmarshaller would fail with a serialization error.
Fix #331
> private/protocol/query: Add parsing of ServiceUnavailableException

- service/dynamodb/dynamodbattribute/doc.go
- service/dynamodb/dynamodbattribute/encode.go
Docs for the new struct tag`dynamodbav` was incorrectly referring to them as to `dynamodb`, which is
not a valid struct tag.
> service/dynamodb/dynamodbattribute: Fix struct tag documentation

- private/endpoints/endpoints.json
- private/endpoints/endpoints_map.go
- private/endpoints/endpoints_test.go
EC2 Metadata endpoint was using the wrong endpoints.json configuration
causing the look up to return https://ec2metadata.cn-north-1.amazonaws.com.cn
as the endpoint instead of http://169.254.169.254/latest. This impacted
both CN and GovCloud regions.
> private/endpoints: Fix CN and GovCloud EC2Metadata endpoint

- private/protocol/ec2query/unmarshal.go
Query and EC2 query slightly differ in that the request id is sent as
RequestID not RequestID.
> private/protocol/ec2query: Unmarshal correct error request id.

- models/apis/ec2/2015-10-01/waiters-2.json
- service/ec2/waiters.go
Updates the coral model for EC2 waiters to use the correct error code.
Fix #599
> service/ec2: Correct waiter error code checked

- aws/types.go
- aws/types_test.go
If the WriteAtBuffer is given ordered calls to WriteAt, i.e. the
length of the internal buffer grows with each call, the WriteAtBuffer
significantly degrades in performance due to the internal buffer
allocating too slowly. This occurs when downloading an object from S3,
where the object is downloaded in ordered chunks. I included a new
test, BenchmarkWriteAtBufferOrderedWrites to test the performance
around this use case.
By growing the internal buffer's capacity by 2*expLen, we may
potentially use more memory, but we spend less time copying bytes and
reallocating the internal buffer.
This change allows a consumer of this library to use two new
mechanisms to control the allocation of the internal buffer:
1. .GrowthCoeff, which defines the growth rate of the internal
buffer. In cases where …
> aws/types: grow WriteAtBuffer capacity by 2m when growing to length m

- aws/credentials/stscreds/assume_role_provider.go
If a IAM policy requires a user to be authenticated with multi-factor authentication, we have to pass the `mfa-serial-number` and its `token-code`. This changes enable us to do it like following sample code in Python.
http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_sample-code.html#MFAProtectedAPI-example-assumerole
> aws/credentials/stscreds/: Adds support for AssumeRole with MFA Auth

- service/s3/customizations.go
Adds customizations to the S3 service client for generating MD5 for
the PutBucketReplication operation.
[Looks like](http://docs.aws.amazon.com/AmazonS3/latest/API/APIRest.html) this was the only operation missing the Content-MD5.
Fix #612
> service/s3: Add Content-MD5 for PutBucketReplication

- aws/config.go
- service/s3/customizations.go
- service/s3/platform_handlers.go
- service/s3/platform_handlers_go1.6.go
- service/s3/platform_handlers_go1.6_test.go
Adds support for the HTTP header `Expect: 100-Continue` being set for S3
PUT requests over 2MB. This status allows the s3 service client to wait
for the S3 service to authenticate and validate the request prior to sending
the body. Reducing the transfer cost for invalid or unauthenticated request.
> service/s3: Add support for Expect: 100-Continue

- aws/request/request.go
- aws/request/request_test.go
This was generating panics (`nil pointer dereference`) on retries, since Body will can be empty in some cases (e.g.: when connections/requests time out there isn't a response).
> response.Body can be nil when requests time out

- Makefile
Updates the Makefile's sandbox-test recipe to use the go 1.5 no 1.5 experiment test case.
> Add sandbox dockerfiles for go 1.5 without 1.5 experiment

- example/signCloudFrontCookies/signCookies.go
- service/cloudfront/sign/policy.go
- service/cloudfront/sign/sign_cookie.go
- service/cloudfront/sign/sign_cookie_example_test.go
- service/cloudfront/sign/sign_cookie_test.go
Adds a CookieSigner for signing cookies for client user agents to use when requesting protected resources from CloudFront.
Minor additions to #614
> Add CookieSigner for CloudFront resources

- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_test.go
Apparently some HTTP transactions can return io.ErrUnexpectedEOF, eg
https://groups.google.com/forum/#!topic/golang-nuts/2wDPB42-rZ0
Before this change, this would result in S3Manager sending a lot of 0
sized parts, eventually causing the error "TotalPartsExceeded:
exceeded total allowed configured MaxUploadParts".
> Fix infinite loop if Reader returns io.ErrUnexpectedEOF

- service/glacier/customizations.go
- service/glacier/customizations_test.go
Hashing was occurring more times than needed when fields/headers were already set.
> Fix to not hash again if Checksum is set

- example/service/cloudfront/signCookies/README.md
- example/service/cloudfront/signCookies/signCookies.go
- example/service/s3/listObjects/README.md
- example/service/s3/listObjects/listObjects.go
- example/service/s3/listObjectsConcurrently/README.md
- example/service/s3/listObjectsConcurrently/listObjectsConcurrently.go
Moves the example code files into a tree separated by service and purpose. This should make it easier for find contextualized examples as more are added.
```
/example
...
/service/
/s3/
listObjectsConcurrently/
listObjects/
/cloudfront/
signCookies/
...
> Moved example code into tree structure for better discoverability

- private/signer/v4/functional_test.go
- private/signer/v4/v4.go
- private/signer/v4/v4_test.go
This fixes the bug where Content-Length was incorrectly being
blacklisted from a signed signature. The header was being incorrectly
excluded from the V4 signature.
Fix #625
> private/signer/v4: Remove Content-Length from blacklist of signed headers

- private/signer/v4/v4.go
- private/signer/v4/v4_test.go
Issue was discovered where the Authorization header would be incorrectly
added to the V4 signature. The header would be signed with the old
value, then updated once the signature was calculated for the new
request. This issue would occur when credentials were expired and the
request was retried.
Added Authorization to ignored headers list, and updated tests to
correctly verify that the Authorization headers are not signed when
requests are resigned.
Fix #627
> private/signer/v4: Do not sign Authorization header on retries

- private/signer/v4/v4.go
- private/signer/v4/v4_test.go
Requests that are delayed to be sent, or are retried so many times that
the original date the request was signed with is past the age a
signature can be, the request needs to be resigned.  This prevents
issues for request being retried many times, and finally succeding but
encounter an expired signature.
Fix #486
> private/signer/v4: Resign requests which are too old

- aws/corehandlers/handlers.go
- aws/corehandlers/handlers_test.go
- private/signer/v4/v4.go
- private/signer/v4/v4_test.go
Removes the content-length header from the HTTP request if its value is
zero. This would of already been performed by the Go http.Client, but
the SDK needs to do this earlier to ensure the content-length header
does not get included in the signature.
This change also ensures the bode's content-length is signed if set to a
value other than 0.
Fix #625
> private/signer/v4: Include Content-Length in signature

- aws/request/request.go
- aws/request/request_test.go
If a failure occurs before `Request.HTTPResponse` is set, the retry handler will panic when trying to read `Request.HTTPResponse.Body`. This adds guards to the retry handler.
Note, this was partially fixed in https://github.com/aws/aws-sdk-go/pull/622, but this handles the case where the `Request.HTTPResponse` is completely `nil` (not just a `nil` `Body`).
cc: @ricardochimal @fabiokung
> Fix retries when response is nil

- aws/config.go
- service/s3/customizations.go
- service/s3/host_style_bucket.go
- service/s3/host_style_bucket_test.go
Updates S3 to support S3 accelerate functionality. To enable this set
the `aws.Config.S3Accelerate` flag to true. The bucket must have
accelerate enabled before you can use the SDK with the accelerate flag
enabled.
> service/s3: Add support for S3 accelerate

- private/protocol/json/jsonutil/build.go
Updates the `jsonutil` package to encode non printable characters as
`\u0000` instead of `\x00`.
Fix #654
> private/protocol/json/jsonutil: Fix JSON string encoding for unicode 

- Gemfile
Updates the doc tool temporarily to fix the unexpected inclusion of`Input` or validated shapes in package list root on http://docs.aws.amazon.com/sdk-for-go/api/.
Fix #658
> Update doc tool dependency pinning.

- aws/client/default_retryer.go
- aws/request/request_test.go
Implements #669 
* Use a seeded PRNG source in order to yield random backoff sequences
* Apply effective jitter to backoff durations for throttling errors
> Make DefaultRetryer more efficient in dealing with throttling errors

- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/decode_test.go
- service/dynamodb/dynamodbattribute/encode.go
- service/dynamodb/dynamodbattribute/encode_test.go
- service/dynamodb/dynamodbattribute/shared_test.go
@xibz - a PR in response to issue #671.
I started to enhance the tests in marshaler_test with time fields on the test structs, but received a sea of failures, since most (all?) of the tests seem to verify success using reflect.DeepEqual. Unfortunately, DeepEqual doesn't play very well with time, so I aborted the changes.
> Alter dynamodbattribute marshaling to handle time conversion

- service/s3/s3manager/upload.go
This has been observed in testing with Ceph Infernalis. Strictly speaking the bug is in Ceph for sending malformed data, but crashing here with a nil pointer deref isn't good practice.
See ncw/rclone#459 for background
> Fix nil pointer deref if Location is nil in CompleteMultipartUploadOutput

- aws/request/http_request.go
- aws/request/http_request_1_4.go
- aws/request/http_request_copy_test.go
- aws/request/http_request_retry_test.go
If the header map values are reused between retry attempts it is
possible for a race codition to occur where transporter is still
referencing the header values when the request is being retried and
resigned.
This change updates the request copy to do a deep copy for headers and
URL. In addition the request fields not used by the SDK are dropped.
Fix #679
> aws/request: Fix data race caused by resusing request header map value

- awstesting/integration/smoke/sns/sns.feature
Error message changes should not cause integ tests to fail. Loosening the validation done on responses.
> Update integration test for SNS error message

- README.md
There were two API Reference badges in the same line of badges.
They link to the same content. This PR removes one.
> Remove second API Reference badge from README.md

- doc-src/aws-godoc/templates/style.css
Updates the style sheet for the generated docs to not have a max width.
> Remove max width from generated docs

- awstesting/util.go
- models/protocol_tests/generate.go
- private/model/api/param_filler.go
- private/util/sort_keys.go
A single function from `awstesting` caused the main packages to import `awstesting` which in turn brought a lot of testing related dependencies with itself. By moving a single file we can get rid of this dependency and the library can be self-contained again with the already vendored dependencies.
> Move awstesting.SortedKeys to private/util package (fixes #721)

- aws/signer/v4/v4.go
Updated to use a const instead of recomputing the SHA256 for each
request's empty body.
Minor fix up of #731
> aws/signer/v4: Use const SHA256 for empty request body hash

- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
Removes the string concats from stripExcessSpaces that was causing many
allocs for each signed request.
```
benchmark                        old ns/op     new ns/op     delta
BenchmarkStripExcessSpaces-4     18815         542           -97.12%
benchmark                        old allocs     new allocs     delta
BenchmarkStripExcessSpaces-4     406            5              -98.77%
benchmark                        old bytes     new bytes     delta
BenchmarkStripExcessSpaces-4     17616         144           -99.18%
```
Fix #712
> aws/signer/v4: Remove string concats from stripExcessSpaces

- README.md
Adds reference document links for AWS service guides, SDK getting
started guides, and SDK API references.
Fix #262
Fix #474
> Update README with useful links and reference docs

- service/sqs/checksums.go
- service/sqs/checksums_test.go
In rare cases the message ID in the response could be nil, this update
guards against this, and logs the occurrence with request ID.
Fixup of #707
> service/sqs: Guard against nil panic in ReceiveMessage

- aws/config.go
- aws/request/request.go
- aws/signer/v4/functional_test.go
- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
The X-Amz-Content-Sha256 header was not being signed for S3 requests.
This header is required to be signed, per the S3 V4 signature spec.
Fix #743
> Update V4 signer to sign Sha256 header for S3 requests

- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/encode.go
- service/dynamodb/dynamodbattribute/shared_test.go
Previously the marshalers would not be able to assign or receive values
correctly from type aliased primitives because interface type switch
casing was used. These comparisons need to be done with reflect Kinds to
find the correct type matches.
Fix #724
> service/dynamodb/dynamodbattribute: Update Marshalers for aliased types

- service/dynamodb/dynamodbattribute/encode.go
- service/dynamodb/dynamodbattribute/encode_test.go
Fixes #752 and doesn't squash `error` when calling `encode` in `encodeStruct`
> Fixing issue 752 by properly handling omitempty

- service/s3/unmarshal_error.go
- service/s3/unmarshal_error_test.go
Updates the S3 error unmarshaler to ensure the error code and message is
always provided. The logic was expecting ContentLength to be 0 if not
set, but this is incorrect. Removed the dependency on checking the
ContentLength and switch to fallback if the body parse fails.
Fix #765
> service/s3: Ensure error code is always set

- awstesting/assert.go
Removes the dependency on testify's assert in awstesting so the SDK will no longer require additional non-runtime related libraries when doing operations like `go build ./...` on a Go workspace with the SDK in it.
Related to #737 and #449
> awstesting: Remove non-testing dependancy on testify assert

- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
A regression was introduced in commit bae4e5236e96d15b7d97d69b7d91550defa99741 (relating to issue #743) that broke glacier's UploadMultpartPart. I'm not 100% sure what's going on here, but it appears that glacier has the same signer-v4 exceptions as s3?
Fix #783
> fix for issue #783

- aws/credentials/static_provider.go
- aws/defaults/defaults.go
- aws/defaults/defaults_test.go
- aws/session/doc.go
- aws/session/env_config.go
- aws/session/env_config_test.go
- aws/session/session.go
- aws/session/session_test.go
- aws/session/shared_config.go
- aws/session/shared_config_test.go
- aws/session/testdata/shared_config
- aws/session/testdata/shared_config_invalid_ini
- aws/session/testdata/shared_config_other
- awstesting/integration/customizations/s3/s3manager/integration_test.go
- awstesting/integration/integration.go
- awstesting/integration/smoke/shared.go
Updates the SDK to take advantage of the new `AWS_SDK_LOAD_CONFIG` environment variable. When set to a truthy value, as defined in strconv.ParseBool, the SDK will load both shared config file (~/.aws/config), and the shared credentials file (~/.aws/credentials). The shared credentials file has precedence over the shared config.
Both config files share the same format. Both `[name]` and `[profile name]` are accepted as section names. The first, `[name]` will be looked for first before falling back to `[profile name]` per config file.
See the [session](http://docs.aws.amazon.com/sdk-for-go/api/aws/session/) package docs for more information.
Deprecates the `session.New` method since it cannot return an error when the session fails to load until a request is made. `session.NewSession` …
> aws/session: Add support for shared config (~/.aws/config) file

- aws/session/doc.go
- aws/session/session.go
Notice this typo while reading your doc, might as well contribute a fix :)
> Fixed a typo in session documentation (Optons vs Options)

- aws/session/session.go
The Shared Config update expanded how the SDK can be configured to load
credentials, but the error message returned when no credentials were
found was not updated to be consistent with current chain provider
message.
> aws/session: Correct credentials error messages, if no creds founds

- aws/client/client.go
fixes #805 (which also describes the scenario in which this is important).
> Log errors that happen while dumping requests/responses

- aws/session/doc.go
The complete paragraph is found a little way down the file.
> Remove leftover chopped paragraph from documentation.

- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_test.go
Fixes how the io.ErrUnexpectedEOF error was handled by the uploader received from io.Reader input.
Fix #780
> service/s3/s3manager: Fix UnexpectedEOF not being handled durign upload

- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/decode_test.go
- service/dynamodb/dynamodbattribute/encode.go
- service/dynamodb/dynamodbattribute/encode_test.go
If a struct pointer type is embedded as a field, the current implementation will crash when decoding a dynamodbattribute into it. Such as the c object in this following example:
```
type B struct {
Bint int
}
type C struct {
*B
}
c := C{}  // c.B is nil and we didn't create a B explicitly.
```
I think this is a bug because encoding/json could handle it correctly: https://play.golang.org/p/vg3PJJwrw6
The root cause of the bug is the abuse of reflect.Value.FieldByIndex which crashes on nil pointers.
The encoding procedure cannot handle embedded pointer struct field either, for the same reason. 
The fix is trivial, i.e., creating a object on nil embedded pointer when decoding and skipping nil embedded pointer when encoding.
> Fix crashes when embedded pointer to struct is being decoded/encoded to dynamodbattribute.

- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_test.go
Fixes #824 in regards to the `Body` being an `io.ReaderAt` and potentially not implementing a `Seek` method. If it doesn't implement a seek method, then the `Content-Length` will be the part size.
> Fixes bug with Uploader

- service/s3/s3manager/download.go
It looks like the Downloader documentation was copied from the
uploader.go file, and still contains references to the Uploader type as
well as uploading in general. Some of the code samples in the docs don't
compile, so this fixes that.
> Update Downloader documentation to fix references to Uploader

- service/s3/s3crypto/helper_test.go
This was never updated when the code was changed.
Basically was passing an empty buffer, but this wasn't suppose to be passed. The methods that calls `Read` will always provide a buffer of at least length 1.
> service/s3/s3crypto: Fixing unit test

- service/s3/s3manager/download.go
- service/s3/s3manager/download_test.go
Adds the ability to automatically retried S3 object parts that fail
after the initial request response is provided. This includes scenarios
such as the network connection is terminated, or broken.
The body parts will be retried based on the S3 service clients Max
Retries configuration. For example setting the aws.Config.MaxRetries to
3 will allow the S3 Downloader to retry part body failures up to 3
times.
This feature is enabled automatically. No additional work is needed to
take advantage of it.
Fix #466
> service/s3/s3manager: Add retry download object part body

- aws/session/session.go
`AWS_DEFAULT_PROFILE` is not loaded, if `SharedConfigState = SharedConfigEnable`
> load shared environment if SharedConfigState Enable

- Makefile
golint dropped support for Go 1.5. The make test were updated to skip
linting on 1.5 as well as 1.4.
> Fix travis tests for Go 1.5

- aws/client/client.go
- aws/request/offset_reader.go
- aws/request/offset_reader_test.go
- aws/request/request.go
- aws/signer/v4/v4.go
Fixes the possible race conditions where the SDK's request body could be
mutated by the HTTP request directly. This could occur because the SDK did
not consistently protect the SDK's request#Request.Body parameter from the
http#Request.Body. This inconsistency prevented the SDK from protecting
against race conditions when HTTP Client's Transport would still be reading
on the http#Request.body and the SDK would be attempting to retry the
API operation.
During a API operation retry the request#Request.Body needs to be rewound
for then next retry of the HTTP request. This is protected now by creating
a strong separation between the request#Request.Body and http#Request.Body.
A per request wrapper is created for each HTTP request attempt that is safe
to use concurrently.
Fix #868, #869, #871
> aws/request: Fix HTTP Request Body race condition.

- aws/corehandlers/handlers.go
- aws/corehandlers/handlers_test.go
- aws/defaults/defaults.go
- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
Improves the reliability of the request signature by resigning the
request each retry. In addition logic was added to the Send request
handler chain to ensure the delay between Sign and Send will not prevent
expired signature. This also brings the SDK in line with the other AWS
SDKs in their behavior of resigning the request each retry.
Related to #822
> aws/signer/v4: Remove logic determining if request needs to be resigned

- aws/session/shared_config.go
Make it skip shared config file if it can't be read for
whatever reason (not exist, permissions, IO error, etc).
Previously files were skipped only if they didn't exist,
but other conditions can prevent them from being read and
same logic should be applicable to them.
> Truly skip shared config on read errors

- Makefile
- awsmigrate/awsmigrate-renamer/gen/gen.go
- awsmigrate/awsmigrate-renamer/rename/rename.go
- awsmigrate/awsmigrate-renamer/rename/renames.go
- awsmigrate/awsmigrate-renamer/renamer.go
- example/aws/request/handleServiceErrorCodes/README.md
- example/aws/request/handleServiceErrorCodes/handleServiceErrorCodes.go
- example/service/cloudfront/signCookies/README.md
- example/service/cloudfront/signCookies/signCookies.go
- example/service/ec2/filterInstances/README.md
- example/service/ec2/filterInstances/filter_ec2_by_tag.go
- example/service/s3/concatObjects/README.md
- example/service/s3/concatObjects/concatObjects.go
- example/service/s3/listObjects/README.md
- example/service/s3/listObjects/listObjects.go
- example/service/s3/listObjectsConcurrently/README.md
- example/service/s3/listObjectsConcurrently/listObjectsConcurrently.go
- models/protocol_tests/generate.go
- private/model/cli/api-info/api-info.go
- private/model/cli/gen-api/main.go
- private/model/cli/gen-endpoints/main.go
Adds the `deprecated` build tags to the awsmigrate.
Adds the `example` build tag to all examples.
Adds the `codegen` build tags to the SDK's code generate commands.
This change prevents the SDK adding unintended executables to the user's `/bin`
> Add build tags to internal SDK tools

- aws/signer/v4/functional_1_4_test.go
- aws/signer/v4/functional_1_5_test.go
- aws/signer/v4/functional_test.go
- aws/signer/v4/uri_path.go
- aws/signer/v4/uri_path_1_4.go
- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
aws/signer/v4: Add support for URL.EscapedPath to signer
Adds support for the URL.EscapedPath method added in Go1.5. This allows
you to hint to the signer and Go HTTP client what the escaped form of the
request's URI path will be. This is needed when using the AWS v4 Signer
outside of the context of the SDK on http.Requests you manage.
Also adds documentation to the signer that pre-escaping of the URI path
is needed, and suggestions how how to do this.
aws/signer/v4 TestStandaloneSign test function is an example
using the request signer outside of the SDK.
Fix #866
> aws/signer/v4: Add support for URL.EscapedPath to signer

- service/dynamodb/dynamodbattribute/tag.go
- service/dynamodb/dynamodbattribute/tag_test.go
As a set can also have omitemptyelem tag.
https://github.com/aws/aws-sdk-go/blob/master/service/dynamodb/dynamodbattribute/encode.go#L108
@jasdel
> Tag can be split into max 3

- CHANGELOG.md
- aws/version.go
- models/apis/ecr/2015-09-21/api-2.json
- models/apis/ecr/2015-09-21/docs-2.json
- models/apis/elasticache/2015-02-02/api-2.json
- models/apis/elasticache/2015-02-02/docs-2.json
- service/dynamodb/dynamodbattribute/tag_test.go
- service/ecr/api.go
- service/ecr/ecriface/interface.go
- service/ecr/examples_test.go
- service/elasticache/api.go
- service/elasticache/examples_test.go
- service/elasticache/service.go
Release v1.4.16
===
Service Model Updates
---
* `service/ecr`: Update Amazon EC2 Container Registry service model
* DescribeImages is a new api used to expose image metadata which today includes image size and image creation timestamp.
* `service/elasticache`: Update Amazon ElastiCache service model
* Elasticache is launching a new major engine release of Redis, 3.2 (providing stability updates and new command sets over 2.8), as well as ElasticSupport for enabling Redis Cluster in 3.2, which provides support for multiple node groups to horizontally scale data, as well as superior engine failover capabilities
SDK Bug Fixes
---
* `aws/session`: Skip shared config on read errors (#883)
* `aws/signer/v4`: Add support for URL.EscapedPath to signer (#885)
SDK Features
---
* `private/model/api`: …
> Release v1.4.16

- aws/config.go
- service/s3/host_style_bucket.go
- service/s3/host_style_bucket_test.go
Adds support for using S3 accelerate with dual stack IPv4 with IPv6. To
enable dual stack with accelerate set the `Config.UseDualstack` and
`Config.S3UseAccelerate`.
```go
sess := session.New()
svc := s3.New(sess, &aws.Config{
S3UseAccelerate: aws.Bool(true),
UseDualStack:    aws.Bool(true),
})
result, err := svc.GetObject(&s3.GetObjectInput{
Bucket: aws.String("my_bucket"),
Key:    aws.String("my_key"),
})
// Request made to:
// https://my_bucket.s3-accelerate.dualstack.amazonaws.com/my_key
```
> service/s3: Add support for accelerate with dual stack

- Makefile
- awsmigrate/awsmigrate-renamer/renamer.go
- private/endpoints/endpoints.go
- private/model/api/api.go
- private/model/api/api_test.go
- private/model/api/customization_passes.go
- private/model/api/docstring.go
- private/model/api/exportable_name.go
- private/model/api/load.go
- private/model/api/load_test.go
- private/model/api/operation.go
- private/model/api/pagination.go
- private/model/api/param_filler.go
- private/model/api/passes.go
- private/model/api/shape.go
- private/model/api/shape_validation.go
- private/model/api/shapetag_test.go
- private/model/api/waiters.go
- private/model/endpoints.go
- private/protocol/ec2query/build.go
- private/protocol/ec2query/unmarshal.go
- private/protocol/jsonrpc/jsonrpc.go
- private/protocol/query/build.go
- private/protocol/query/unmarshal.go
- private/protocol/restjson/restjson.go
- private/protocol/restxml/restxml.go
- service/generate.go
Adds build tags for all of the SDK's code gen logic. Since the code gen is only for SDK development this will prevents the code gen packages and dependencies from impacting normal usage runtime environments.
Any non-std lib dependency added to the code gen packages will need to be explicitly retrieved because `go get` will ignore the tagged files.
e.g.
```makefile
get-codegen-deps:
@go get golang.org/x/net/html
```
> Fix codegen build tags to be used in all cases not just main files

- example/service/dynamodb/scanItems/README.md
- example/service/dynamodb/scanItems/scanItems.go
- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/decode_test.go
Adds support for unmarshaling a list of maps. This is useful for
unmarshaling the DynamoDB AttributeValue list of maps returned by APIs
like Query and Scan.
Example can be found in example/service/dynamodb/scanItems.
Fix #810, #696
> service/dynamodb/dynamodbattribute: Add UnmarshalListOfMaps

- README.md
- aws/session/doc.go
Changed some references of the deprecated `session.New` in the documentation to `session.NewSession`.
Also dropped trailing spaces in README.md
> Changed refs for session.New to session.NewSession

- aws/corehandlers/handlers_test.go
- awstesting/sandbox/Dockerfile.golang-tip
Test was incorrectly checking the content length value when it shouldn't of have.
> Fix Test for Go Tip

- private/model/api/shape.go
This removes the broken shape `aws.ReadSeekerCloser` which isn't defined in the `aws` package. In addition, the logic seems to not make too much sense.
> Removing broken shape

- CHANGELOG.md
- aws/credentials/ec2rolecreds/ec2_role_provider.go
- aws/ec2metadata/api.go
Saw similar [cr/discussion](https://groups.google.com/forum/#!topic/golang-codereviews/s_SRCVXXpws) in Go stdlib, and noticed the SDK has a few inconsistencies with the spelling also.
> Use consistent spelling of (un)marshal(ed|ing)

- aws/config.go
- private/protocol/rest/build.go
- private/protocol/rest/build_test.go
Fixes #920 by adding flag to dictate whether or not the SDK cleans the URL path.
> private/protocol/rest: Adding boolean disable protocol uri cleaning

- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
The signer should sort array of values when building the canonical request.
> aws/signer/v4/: v4 signer should sort array values

- aws/awsutil/prettify.go
- service/dynamodb/dynamodbattribute/marshaler_examples_test.go
Change the current behavior of the prettifier for `[]byte`:
```
Data: [
42,
36,
69,
1
]
```
With something more friendly:
```
Data: <binary>
```
> Make awsutil.Prettify more friendly for blobs

- private/protocol/xml/xmlutil/unmarshal.go
- private/protocol/xml/xmlutil/xml_to_struct.go
- private/protocol/xml/xmlutil/xml_to_struct_test.go
> Properly using namespaces when unmarshaling in XML

- private/protocol/xml/xmlutil/unmarshal.go
- private/protocol/xml/xmlutil/xml_to_struct.go
This fixes an xml bug with marshaling due to encoding back and forth returning extra invalid data.
> Fixing xml bug

- aws/session/session.go
> Fix typo in aws/session/session.go comment

- example/service/s3/concatObjects/concatObjects.go
- private/model/api/api.go
- private/protocol/ec2query/build_test.go
- private/protocol/ec2query/unmarshal_test.go
- private/protocol/jsonrpc/build_test.go
- private/protocol/jsonrpc/unmarshal_test.go
- private/protocol/query/build_test.go
- private/protocol/query/unmarshal_test.go
- private/protocol/restjson/build_test.go
- private/protocol/restjson/unmarshal_test.go
- private/protocol/restxml/build_test.go
- private/protocol/restxml/unmarshal_test.go
- private/protocol/xml/xmlutil/xml_to_struct_test.go
ServiceName was not correctly being rendered when the NoServiceNameConst
flag was set. Fixes this allowing protocol tests to be generated
correctly.
> private/model/api: Fix ServiceName being rendered correctly for service files

- private/model/api/api.go
- service/cloudsearchdomain/service.go
- service/cognitosync/service.go
- service/pinpoint/service.go
This change ensures that all service models that model the JSONVersion
and TargetPrefix metadata fields are generated correctly into the
service.go file for the service.
> private/model/api: Generate REST-JSON JSONVersion correctly

- service/route53/customizations.go
- service/route53/customizations_test.go
In SDK release v1.6.3 fix for REST protocol aboslute URL and HTTP2 broke
Route53's URL cleaning logic that removed duplicate "hostedzone"
elements from the URL. This change fixes the URL cleaning to ensure that
the modified URL RawPath is propagated to the URL's base path. RawPath
was being ignored by URL's EscapedPath method because it was not a valid
escaping of the original uncleaned Path.
Fix #1005
> service/route53: Fix URL path cleaning for Route53 API requests

- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/decode_test.go
- service/dynamodb/dynamodbattribute/shared_test.go
PR proposes handling bool-overlying types (`type MyType bool`) by converting when unmarshalling. The same handling can be seen here for string-overlying types: https://github.com/aws/aws-sdk-go/blob/master/service/dynamodb/dynamodbattribute/decode.go#L511
Background: We have a bool-overlying type, whose JSON encoding is 0|1, that exists for backward-compatibility. As my type cannot be assigned to bool, unmarshalling from dynamodbattribute to this type results in panic.
> convert value to actual type when unmarshalling from BOOL

- private/protocol/json/jsonutil/build.go
Benchmark was originally returning 30 allocs/op. This reduces json's proto marshaler to 24 allocs/op.
> Optimizing marshaling

- aws/types.go
Removes the extra restrictions put on the slice returned by `WriteAtBuffer.Bytes` method. Bytes call should act similar to `bytes.Buffer`
Fix #1040
> aws: Simplify WriteAtBuffers return

- example/aws/request/handleServiceErrorCodes/handleServiceErrorCodes.go
Updates error code handling example to use const instead of string.
Related #1061
> example: Update Error code handling example to use const

- aws/client/client.go
- aws/endpoints/endpoints.go
- aws/endpoints/v3model.go
- aws/endpoints/v3model_test.go
- aws/session/session.go
- private/model/api/api.go
- private/model/api/customization_passes.go
- service/cloudsearchdomain/service.go
- service/iotdataplane/service.go
Adds an option to the endpoint resolver that allows resolving endpoints
for a service that is not included in the endpoints metadata. In order
for this to work with the partitions list the region must be valid. When
using a specific partition the endpoint will be resolved regardless if
the region is also valid.
This option is ignored if StrictMatching option is enabled.
> aws/endpoints: Add option to resolve unknown service in a partition

- example/service/dynamodb/unitTest/README.md
Was reading the example's README and noticed the typo. Let's fix it.
> Fix typos in DynamoDB example README

- CHANGELOG_PENDING.md
- aws/credentials/stscreds/assume_role_provider.go
- aws/credentials/stscreds/assume_role_provider_test.go
- aws/session/doc.go
- aws/session/session.go
- aws/session/session_test.go
- aws/session/shared_config_test.go
- aws/session/testdata/shared_config
Adds support for assuming IAM roles with MFA enabled. A TokenProvider
func was added to`stscreds.AssumeRoleProvider` that will be called each
time the role's credentials need to be refreshed. A basic token provider
that sources the MFA token from stdin as `stscreds.StdinTokenProvider`.
This change also adds a new session option, `AssumeRoleTokenProvider`.
The value of this field will be passed to the `stscreds.AssumeRoleProvider`
if the shared configuration is enabled and the config (`~/.aws/config`) or 
credentials files (`~/.aws/credentials`) specify a role to assume
with MFA.
In order for the SDK to assume a role with MFA the `SharedConfigState`
session option must be set to `SharedConfigEnable`, or `AWS_SDK_LOAD_CONFIG`
environment variable set.
Creating an AssumeRoleProvider with …
> aws/session: Add support for AssumeRoles with MFA

- awstesting/assert.go
- awstesting/assert_test.go
- models/protocol_tests/input/ec2.json
- models/protocol_tests/input/json.json
- models/protocol_tests/input/query.json
- models/protocol_tests/input/rest-json.json
- models/protocol_tests/input/rest-xml.json
- private/protocol/ec2query/build_test.go
- private/protocol/jsonrpc/build_test.go
- private/protocol/query/build_test.go
- private/protocol/query/queryutil/queryutil.go
- private/protocol/restjson/build_test.go
- private/protocol/restxml/build_test.go
This change fixes an issue regarding lists with a list name not being used.
In addition, this regenerates and updates the protocol tests
> `private/protocol`: Fixing bugs and asserts in query protocol

- CHANGELOG_PENDING.md
- aws/session/custom_ca_bundle_test.go
- aws/session/doc.go
- aws/session/env_config.go
- aws/session/env_config_test.go
- aws/session/session.go
Adds supports for side loading Certificate Authority bundle files to the
SDK using `AWS_CA_BUNDLE` environment variable or `CustomCABundle` session option.
TODO:
> aws/session: Add support for side loaded CA bundles

- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/decode_test.go
- service/dynamodb/dynamodbattribute/encode.go
- service/dynamodb/dynamodbattribute/encode_test.go
- service/dynamodb/dynamodbattribute/tag.go
Adds support for an additional struct tag `unixtime` and a new type
`UnixTime` that make it easier to marshal time as seconds since January
1, 1970 UTC. This is useful for marshaling time values into unix time
for DynamodDB features such as TTL and CreatedAt.
> service/dynamodb/dynamodbattribute: Add helper to  marshal time as Unix time.

- service/rds/customizations.go
- service/rds/customizations_test.go
Also add support for `CopyDBClusterSnapshot` and `CreateDBCluster`.
Fixes #1127
> service/rds: Fixes issue with not specifying `SourceRegion`

- aws/jsonvalue.go
- models/protocol_tests/generate.go
- models/protocol_tests/input/rest-json.json
- models/protocol_tests/output/query.json
- models/protocol_tests/output/rest-json.json
- private/model/api/api.go
- private/model/api/operation.go
- private/model/api/passes.go
- private/model/api/shape.go
- private/protocol/ec2query/build_test.go
- private/protocol/ec2query/unmarshal_test.go
- private/protocol/jsonrpc/build_test.go
- private/protocol/jsonrpc/unmarshal_test.go
- private/protocol/query/build_test.go
- private/protocol/query/unmarshal_test.go
- private/protocol/rest/build.go
- private/protocol/rest/unmarshal.go
- private/protocol/restjson/build_test.go
- private/protocol/restjson/unmarshal_test.go
- private/protocol/restxml/build_test.go
- private/protocol/restxml/unmarshal_test.go
The JSON value trait will be a way of signifying unstructured header types. This modifies the `restjson` protocol to support the type. When encountering this tag field on marshaling, `jsonvalue:"true"`, we will `json` and `base64 encode the object.
> private/model/api: This adds support for jsonvalue trait for restjson

- service/s3/host_style_bucket_test.go
- service/s3/unmarshal_error.go
- service/s3/unmarshal_error_test.go
Adds a new type s3.RequestFailure which exposes the S3 HostID value from
a S3 API operation response. This is helpful when you have an error with
S3, and need to contact support. Both RequestID and HostID are needed.
When logging the error message both will be logged. The HostID value can
also be retrieved by casting the returned error to a s3.RequestFailure
type.
result, err := svc.GetObject(&s3.GetObjectInput{
Bucket: aws.String("myBucket"),
Key:    aws.String("myKey"),
})
if err != nil {
if s3Err, ok := err.(s3.RequestFailure); ok {
fmt.Printf("Request failed: id: %q, host: %q\n", s3Err.RequestID(), s3Err.HostID())
return
}
}
Fix #1123
> service/s3: Fix S3 HostID to be available in S3 request error message

- aws/request/handlers.go
Use `make([]NamedHandler, 0, len(original))` instead of `[]NamedHandler{}` when copying handlers.
Some profiling via `go test -bench` and `pprof` shows that this change is significant on `request.New`, which is a hot path. In a small utility, the cost of `request.New` fell by anywhere from 0.5% to 2%.
> aws/request: Optimization to handler list copy to prevent multiple alloc calls.

- aws/credentials/credentials.go
I believe the `Provider` interface documentation/comment contained a typographical error.
> Fix Provider interface typo

- private/model/api/api_test.go
- private/model/api/docstring_test.go
- private/model/api/list_of_shame.go
- private/model/api/load_test.go
- private/model/api/passes.go
- private/model/api/passes_test.go
- private/model/api/shapetag_test.go
- private/protocol/ec2query/build_test.go
- private/protocol/jsonrpc/build_test.go
- private/protocol/jsonrpc/unmarshal_test.go
- private/protocol/query/build_test.go
- private/protocol/restjson/build_test.go
- private/protocol/restxml/build_test.go
- private/protocol/restxml/unmarshal_test.go
This will generate unique input and output shapes for new operations. Prior we were using the base shape name if it was shared between operations. This fixes that.
> private/model/api: always generate new input/output shapes, while preserving old operations

- aws/request/retryer.go
Adds support for retrying `RequestTimeoutException` error code that is returned by some services.
Fix #1155
> aws/request: Add retry support for  RequestTimeoutException

- CONTRIBUTING.md
Updates the contributing guide highlighting that the SDK is unable to take model change PRs directly, but to create an issue instead.
> Update contributing guide for models

- service/glacier/treehash.go
- service/glacier/treehash_test.go
Exports the ComputeTreeHash function in the Glacier service client package. This allows you to use the SDK's built in tree hash function for multipart uploads.
Fix #1149
> service/glacier: Export ComputeTreeHash

- aws/request/request.go
- aws/request/request_test.go
Adds two request options to make retrieving API response headers easier
to the request package.
* WithGetResponseHeader - For a single header value
* WithGetResponseHeaders - For all response headers
Related #1162
> aws/request: Add request option helpers for response headers

- example/aws/request/withContext/withContext.go
Cleans up the S3 PutObjectWithContext example to include more documentation.
> example/aws/withContext: Cleanup S3 PutObjectWithContext example

- aws/request/handlers.go
- aws/request/handlers_test.go
- aws/request/request_internal_test.go
Minor optimization to the handler list's handling of copying and pushing
request handlers to the handler list.
benchmark                        old ns/op     new ns/op     delta
BenchmarkOffsetReader-4          54.7          55.4          +1.28%
BenchmarkBytesReader-4           0.76          0.74          -2.63%
BenchmarkNewRequest-4            2629          2682          +2.02%
BenchmarkHandlersCopy-4          462           366           -20.78%
BenchmarkHandlersPushBack-4      439           160           -63.55%
BenchmarkHandlersPushFront-4     633           515           -18.64%
BenchmarkHandlersClear-4         688           516           -25.00%
BenchmarkCodegenIterator-4       746562        750308        +0.50%
BenchmarkEachPageIterator-4      746546        766297        +2.65% …
> aws/request: Minor perf improvement for HandlerList copy, push, and clear

- service/dynamodb/customizations.go
- service/dynamodb/customizations_test.go
Fixes the DynamoDB service client clobbering any custom retryer that was
passed into the service client or Session's config.
Also replaces assert tests cases with conditionals.
Related #1139
> service/dynamodb: Fix DynamoDB using custom retryer

- example/service/dynamodb/scanItems/README.md
Updates the example documentation to include missing information on tags and options.
Fixup of #938
> example/service/dynamodb: Update example documentation

- aws/request/waiter.go
- aws/request/waiter_test.go
Fixes the waiters's matching overwriting the request's `err`, effectively ignoring the error condition. This broke waiters with the `FailureWaiterState` matcher state.
Updated waiter tests to verify error failure condition correctly, not just error retry.
Fix #1193
> aws/request: Fix waiter error match condition

- aws/client/client.go
- aws/client/client_test.go
Fixes the clients potentially polluting the passed in handler list with
the client's customizations. This change ensures every client always works
with a clean copy of the request handlers and it cannot pollute the handlers
back upstream.
This issue was exposed in ec2metadata client created by the default
credentials chain. The client would inject request handlers, which would
pollute the backing handler list array. This caused service clients that
were created from a session to not have their Send request handler in
their list. This issue was not present in service clients such as S3
which were created with a Session's ClientCoinfig because the
ClientConfig would of always created a copy of the session.
Fix #1184
> aws/client: Fix clients polluting handler list

- aws/credentials/credentials.go
- aws/defaults/defaults.go
- aws/defaults/defaults_test.go
- aws/url.go
- aws/url_1_7.go
Adds support for the `AWS_CONTAINER_CREDENTIALS_FULL_URI` environment
variable to the default credential chain. With the limitation that the host must be `localhost` or `127.0.0.1`.
> aws/defaults: Add support for generic http credential provider

- example/aws/endpoints/customEndpoint/README.md
- example/aws/endpoints/enumEndpoints/README.md
- example/aws/request/withContext/README.md
- example/service/dynamodb/scanItems/README.md
- example/service/dynamodb/unitTest/README.md
- example/service/ec2/filterInstances/README.md
- example/service/s3/concatObjects/README.md
- example/service/s3/listObjects/README.md
- example/service/s3/listObjectsConcurrently/README.md
- example/service/s3/putObjectAcl/putObjectAcl.go
- example/service/sqs/mockingClientsForTests/README.md
- example/service/sqs/mockingClientsForTests/ifaceExample.go
- example/service/sqs/mockingClientsForTests/ifaceExample_test.go
Corrects various example documentation instructions and typos. Also ensures all examples have the `example` build tag, and Usage examples are correct.
> example: Fixup example to have correct build tags and usage docs

- aws/request/retryer.go
Adds utility functions to identify the class of request errors.
Utilities added are: IsErrorThrottle, IsErrorRetryable, and IsErrorExpiredCreds.
Fix #1153
> aws/request: Add utility functions for comparing request errors

- aws/client/default_retryer.go
- aws/config.go
- aws/corehandlers/handlers.go
- aws/request/request_test.go
Fixes #1203 
Prior to this fix, requests that experience network issues would not call `ShouldRetry`. However, now we will call `ShouldRetry` if `EnforceShouldRetryCheck` is set. Additionally, the default retryer will check to see if the `Retryable` field is set. If it is, we will return that.
> aws/corehandlers: Ensure that ShouldRetry is being utlized

- private/model/api/customization_passes.go
- service/s3/api.go
The HeadObject's model incorrectly states that the operation can return
the `NoSuchKey` error code.
Fix #1208
> service/s3: Fix HeadObject's incorrect documented error codes

- Makefile
- aws/corehandlers/handlers.go
- aws/corehandlers/handlers_test.go
- aws/request/request.go
- awstesting/cmd/bucket_cleanup/main.go
- awstesting/integration/customizations/s3/s3manager/bucket_region_test.go
- awstesting/integration/customizations/s3/s3manager/integration_test.go
- service/s3/bucket_location.go
- service/s3/bucket_location_test.go
- service/s3/s3manager/bucket_region.go
- service/s3/s3manager/bucket_region_test.go
Adds two features which make it easier to get a bucket's region, `s3.NormalizeBucketLocation` and `s3manager.GetBucketRegion`.
* `s3.NormalizeBucketLocation` function will perform logic to ensure that the value returned by `GetBucketLocation` API operation always is a region ID. This adjusts the [documented behavior](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html), where empty string and `EU` values could be returned instead of region IDs. This is available as a standalone function, request option and request handler.
* `s3.WithNormalizeBucketLocation` - request option to always normalize `GetBucketLocation` response. Should be applied using the [`GetBucketLocationWithContext`](http://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.GetBucketLocationWithContext) …
> service/s3: Add utilities to make getting a bucket's region easier

- private/protocol/protocol_test.go
- private/protocol/xml/xmlutil/unmarshal.go
- private/protocol/xml/xmlutil/unmarshal_test.go
- private/protocol/xml/xmlutil/xml_to_struct.go
- private/protocol/xml/xmlutil/xml_to_struct_test.go
- service/s3/statusok_error_test.go
The XML unmarshaler would drop any serialization or body read error
that occurred on the floor effectively hiding any errors that would
occur.
This corrects the issue of TCP connection reset with XML services such as S3 
only partially unmarshal the response. Leaving some fields unset.
Fix #1205
> private/protocol/xml/xmlutil: Fix unmarshaling dropping errors

- aws/endpoints/defaults.go
- aws/endpoints/endpoints.go
- aws/endpoints/endpoints_test.go
- aws/endpoints/v3model_codegen.go
Adds several utilities to the endpoints packages to make looking up
partitions, regions, and services easier.
* `DefaultPartitions` - returns a list of Partitions. Removing the need
to cast the DefaultResolver to EnumPartitions interface.
* `RegionsForService` - returns the regions a service is in given the
partition list, partition id and service id.
* `PartitionForRegion` - returns the first partition that matches a given region.
* `Service.Regions` - returns a list of regions for a service. Excluding
additional meta endpoints such as `aws-global`
This change also changes the Partition, Region, Service and Endpoint
receiver methods to be value instead of pointer. This change improves
the usage of the AwsPartition functions allowing the methods calls to be
used without taking the address …
> aws/endpoints: Add utilities improving endpoints lookup

- README.md
- aws/credentials/chain_provider.go
- aws/credentials/credentials.go
- aws/endpoints/endpoints.go
- aws/jsonvalue.go
- aws/session/session.go
- example/service/dynamodb/scanItems/README.md
- service/cloudfront/sign/sign_cookie.go
- service/s3/bucket_location.go
- service/s3/s3crypto/cipher_builder.go
Hello again, I am back with some more documentation fixes! :)
This time I went out of my way to hunt for both big and small issues. Let me know if you find any mistakes in my corrections.
Additionally, there are some bugs in the generated documentation. Since it appears the tool that is actually used to generate https://docs.aws.amazon.com/sdk-for-go/api/ is not open source, I couldn't actually fix these bugs, but here are some screenshots:
> Fix documentation bugs

- service/s3/s3manager/download.go
- service/s3/s3manager/download_test.go
Fixes an edge case in the S3 Download Manager that will hang for ever if
the connection errors out on all workers, and the download manager is
blocked on pushing additional items to the queue. The bug occurred
because the download workers where existing.
Fix #1227
> service/s3/s3manager: Fix download hang on connection error

- aws/session/doc.go
There are several places in a row in the `session` doc that mention the
credentials file (`~/.aws/credentials`) and the config file
(`~/.aws/config`) file back to back. In one case they were both called
the "shared credentials" file so I changed the appropriate one to
"config file."
> Change dup. mention of "credentials" to "config"

- aws/doc.go
Adds package docs for the `aws` package. Highlighting the value and pointer conversion utilities. Also adds pointing out the DefaultClient usage.
> aws: Add pkg docs for conversion utils, and aws pkg

- service/dynamodb/dynamodbattribute/encode.go
There is a typo in the comment which cause the official documentation to be inaccurate:
```go
type (m *ExampleMarshaler) 	MarshalDynamoDBAttributeValue(av *dynamodb.AttributeValue) error {
n := fmt.Sprintf("%v", m.Value)
av.N = &n
return nil
}
```
should be
```go
func (m *ExampleMarshaler) 	MarshalDynamoDBAttributeValue(av *dynamodb.AttributeValue) error {
n := fmt.Sprintf("%v", m.Value)
av.N = &n
return nil
}
```
> service/dynamodb/dynamodbattribute: Fix typo in the comment of type Marshaler

- aws/client/client.go
- aws/client/logger.go
- aws/client/logger_test.go
- aws/request/request_test.go
Logging responses will now only log when the body is being read. This moves error handling from the logging to the protocol unmarshalers.
> aws/client: logging on response will do any body manipulation or error handling

- aws/request/connection_reset_error.go
- aws/request/connection_reset_error_other.go
- aws/request/connection_reset_error_other_test.go
- aws/request/connection_reset_error_test.go
Plan9 doesn't have the syscall.ECONNRESET symbol so work around in the
same way as appengine.
>  aws/request: Fix for syscall pkg not available on plan9

- aws/session/session.go
- aws/session/session_test.go
Add SharedConfigFiles option for users to load custom config files.
This will override any related ENV.
Fix https://github.com/aws/aws-sdk-go/issues/1258
> session: add SharedConfigFiles option

- service/s3/s3manager/download.go
- service/s3/s3manager/upload.go
The docs for the Downloader and Uploader struct's PartSize members refer to a default value const DefaultPartSize that does not exist. This makes grepping for the value difficult.
> Fix DefaultPartSize reference in s3manager docs

- example/service/rds/rdsutils/authentication/README.md
- example/service/rds/rdsutils/authentication/iam_authentication.go
- service/rds/rdsutils/connect.go
- service/rds/rdsutils/connect_test.go
> service/rds/rdsutils: example and updating rdsutils to not require scheme

- Makefile
- aws/corehandlers/handlers.go
- aws/corehandlers/handlers_1_8_test.go
- aws/request/request.go
- aws/request/request_1_7.go
- aws/request/request_1_8.go
- aws/request/request_resetbody_test.go
- aws/request/request_test.go
- aws/session/custom_ca_bundle_test.go
- awstesting/custom_ca_bundle.go
Updates the SDK's usage of NoBody so that HTTP requests substitute nil
for http.NoBody. Once the request is sent the Body value will be reset
back to NoBody. This ensures that the SDK sends requests will a nil Body
when no request body is intended to be sent, and the usage of
Request's HTTPRequest.Body will not be a breaking change.
Also moves the aws/session's custom CA bundle test to awstesting to make the bundle and server reusable for other SDK tests.
Fix #1264
> aws/corehandlers: Do request with nil Body if was NoBody value

- aws/request/retryer.go
The LimitExceededException error code should not be treated as a
throttling condition. This error code implies that resources are
exhausted or too many tasks are being attempted at once. The SDK does
not have the information it needs to distinguish between the resources
exhausted and too many tasks attempted at once.
This logic is best implemented by user applications as they will have
the most context about what is being attempted.
To add custom retry with this error code a custom implementation of the
`request.Retryer` interface should be used.
Fix #1271
> aws/request: Do not treat LimitExceededException as throttle error

- aws/client/logger.go
- aws/request/handlers.go
- aws/request/handlers_test.go
- aws/request/request.go
Fixes the SDK's retry request logging to report the the actual error
that occurred, not a stubbed Unknown error message.
Fixes the SDK's response logger to not output the response log multiple
times per retry.
> aws/request: Fix logging from reporting wrong retry request errors

- CHANGELOG_PENDING.md
- aws/request/request.go
- aws/request/request_1_7.go
- aws/request/request_1_8.go
- aws/request/request_1_8_test.go
Adds support for Go 1.8's GetBody function allowing the SDK's http
request using PUT and POST methods to be redirected with temporary
redirects with 307 status code.
Fix #1267
> aws/request: Add support for PUT temporary redirects (307)

- aws/request/request_test.go
- aws/request/retryer.go
- aws/request/retryer_test.go
Adds support for retrying temporary errors that occur during
unmarshaling of a request's response body.
Fix #1275
> aws/request: Add handling for retrying temporary errors during unmarshal

- aws/session/shared_config.go
Fixes the SharedConfigLoadError not including the underlying error
message if there was one when the SDK loads the config file, and the ini
parser fails to parse the file.
> aws/session: Fix Shared Config Load Error

- CHANGELOG_PENDING.md
- aws/credentials/shared_credentials_provider.go
- aws/defaults/shared_config.go
- aws/session/custom_ca_bundle_test.go
- aws/session/env_config.go
- aws/session/env_config_test.go
- aws/session/session.go
- aws/session/session_test.go
- awstesting/assert.go
- awstesting/util.go
- internal/shareddefaults/shared_config.go
- internal/shareddefaults/shared_config_other_test.go
- internal/shareddefaults/shared_config_windows_test.go
Exports the shared credentials  and shared config filename helper functions to make it easier to get the filename of the credentials and config file.
Corrects a bug in the shared credentials and config HOME path that would return an invalid filename on windows if the `HOME` environment variable was defined.
Replaces #1293
> aws/defaults: Export Shared Config/Creds filename helpers

- CHANGELOG_PENDING.md
- service/s3/s3manager/download.go
- service/s3/s3manager/download_test.go
Fixes the S3 Download Manager ignoring the GetObjectInput's Range
parameter. If this parameter is provided it will force the downloader to
fallback to a single GetObject request disabling concurrency and
automatic part size gets.
Fix #1296
> service/s3/s3manager: Fix Downloader ignoring Range get parameter

- aws/credentials/shared_credentials_provider.go
In #1308 the filename was being retrieved with the SharedConfigFilename
utility function not SharedCredentialsFilename function.
This bug caused the `session.New` with the SharedCredentials file to break.
Fix #1313
> aws/credentials: Fix shared credential providers filename

- aws/credentials/shared_credentials_provider_test.go
Adds tests for SharedCredentialProvider ensuring the correct default shared credential file is used if none is provided.
Related #1308 #1312 #1313
> aws/credentials: Add tests for default shared credential filename

- private/model/api/docstring.go
Corrects the SDK's docstring generation to ignore unexpected shape references.
> private/model/api: Warn on unexpected shape model doc reference

- doc-src/aws-godoc/templates/package_default.html
- doc-src/aws-godoc/templates/package_service.html
- doc-src/aws-godoc/templates/style.css
Improves the SDK's API reference guide generation of API operation list by removing the function signature from the operation method in the link. This reduces noise and makes it easier to navigate through the list of API operations per service. The operation method detail doc generation is unchanged.
Also updates the doc generation to include header permalinks to types and methods making sharing links easier.
> Improve AWS generated godocs for API generation list, and type linking

- private/model/api/shape.go
- private/protocol/restxml/build_test.go
- service/cloudfront/api.go
- service/s3/api.go
Fixes a bug with the SDK's generation of services using the REST XML
protocol not annotating shape references with the XML Namespace
attribute.
The XML Namespace URI was incorrectly being limited to the top level
API shape, where it should of applied to all levels.
Fix #1334
> private/model/api: Fix RESTXML support for XML Namespace

- doc-src/aws-godoc/templates/package_default.html
- doc-src/aws-godoc/templates/package_service.html
Fixes the SDK's API Reference doc service client pages to generate the
fragment links correctly.
> Update doc generation templates

- aws/credentials/plugincreds/doc_1_7.go
- aws/credentials/plugincreds/provider.go
- aws/credentials/plugincreds/provider_test.go
- example/aws/credentials/plugincreds/README.md
- example/aws/credentials/plugincreds/main.go
- example/aws/credentials/plugincreds/plugin/plugin.go
Adds support for using plugins to retrieve credentials for API requests.
This change adds a new package `plugincreds` under `aws/credentials`.
As of Go 1.8 this functionality is only available for Linux.
See the example/aws/credentials/plugincreds folder in the SDK for
example usage.
> aws/credentials/plugincreds: Add support for Go plugin for credentials

- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
Go defines that for clients Request.Host overrides the Host header to send and only if this is empty does the Request.Write method use the value of URL.Host.
This fixes v4 signing to abide by these rules and use Request.Host in preference to URL.Host if set.
Fixes #1359
> Fixed v4 Signing for requests with Host set

- example/aws/credentials/plugincreds/README.md
- example/aws/credentials/plugincreds/main.go
- example/aws/credentials/plugincreds/plugin/plugin.go
Updates the credential plugin provider example to be more robust and realistic use case. Switches the example form using mock static credentials to retrieving credentials from a custom JSON file.
> example/aws/credentials/plugincreds: Improve plugin credentials example

- aws/client/default_retryer.go
- aws/config.go
- aws/request/retryer.go
Minor fixes in godoc for `client.DefaultRetryer`.
> Fix wrong documentation for client.DefaultRetryer

- service/s3/s3manager/batch.go
- service/s3/s3manager/batch_test.go
I wanted to use DeleteListIterator to delete an S3 prefix before running an integration test. I noticed that if there were no keys with the prefix I was deleting the AWS SDK would panic. This is down to a faulty assumption about `Pagination.Next()`, specifically `DeleteListIterator` assumes that if `Pagination.Next()` is true there will be more elements. However `Pagination.Next()` is _always_ true the first time it is called (save for an request error), so if the listing is empty the iterator indicates it has a next element which leads to the panic.
The first commit extends the test to demonstrate the bug, and the second commit fixes it. If you would like me to squash these I will.
> service/s3/s3manager: Fix panic from DeleteListIterator when listing is empty

- private/model/api/customization_passes.go
- private/model/api/shape.go
- service/s3/api.go
- service/s3/customizations.go
- service/s3/host_style_bucket.go
- service/s3/sse.go
Improves the performance across the board for all S3 API calls by removing the usage of `ValuesAtPath` being used for every S3 API call.
With a simple S3 HeadObject call the following benchmarks improved the performance of the API call significantly.
```
benchmark                   old ns/op     new ns/op     delta
BenchmarkS3HeadObject-4     190419        169992        -10.73%
benchmark                   old allocs     new allocs     delta
BenchmarkS3HeadObject-4     511            444            -13.11%
benchmark                   old bytes     new bytes     delta
BenchmarkS3HeadObject-4     68694         61968         -9.79%
```
```go
package main
import (
"net/http"
"net/http/httptest"
"testing"
"github.com/aws/aws-sdk-go/aws"
"github.com/aws/aws-sdk-go/aws/credentials" …
```
> service/s3: Use interfaces assertions instead of ValuesAtPath for S3 field lookups.

- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
Fixes the out of bands panic in stripExcessSpaces caused by an incorrect
calculation of the stripToIdx value. Simplified to code also.
Fix #1411
> aws/signer/v4: Fix out of bounds panic in stripExcessSpaces

- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
Optimised stripExcessSpaces by using a hand rolled trim space avoiding the overhead of strings.TrimSpace and ensuring we only do a single pass on the string for both search and copy when stripping multiple spaces.
This improves the performance on the test machine from 2378 ns/op to 1528 ns/op while keeping allocs the same.
Also:
* Added a blank and only trialing spaces test cases.
> aws/signer/v4: Optimize stripExcessSpaces

- aws/convert_types.go
- aws/convert_types_test.go
See: #1432 for discussion around adding this feature.
> Add pointer conversion utilities to transform int64 to time.Time

- aws/arn/arn.go
- aws/arn/arn_test.go
This package allows for parsing and producing Amazon Resource Names (ARNs).  ARNs are parsed in accordance with the [documentation](http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html).
This package avoids parsing the *Resource* section of the ARN, as that can vary widely by AWS service.
> aws/arn: Package for parsing and producing ARNs

- aws/request/request.go
- aws/signer/v4/functional_test.go
- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
Updates the V4 signer so that when a Presign is generated the
X-Amz-Content-Sha256 header is added to the query string instead of
being required to be in the header. This allows you to generate
presigned URLs for GET requests, e.g S3.GetObject that do not require
additional headers to be set by the downstream users of the presigned
URL.
Related to #1467
> aws/signer/v4: Correct V4 presign signature to include content sha25 in URL

- .travis.yml
- Makefile
- awstesting/sandbox/Dockerfile.test.go1.9
- service/s3/s3crypto/envelope.go
Adds Travis testing for Go 1.9, as well as fixes a bug in the S3 Crypto's Envelope struct tag
> Add Go1.9 testing

- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
Remove sorting of query string values when calculating v4 signing as this is not part of the spec:
http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
The spec only requires the keys, not values, to be sorted which is achieved by Query.Encode().
Also fixed TestBuildCanonicalRequest, which was incorrectly testing without this important part of the build process leading to a false success.
> Fixed v4 signing for unordered multi value query parameters

- CHANGELOG_PENDING.md
- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
Reverts #1491 change since it conflicts with the AWS v4 signer test cases found in #1495. This case is not documented in the V4 spec. Additional research is needed before #1491 can be accepted. As either a implementation detail of the test cases, or an undocumented requirement of the spec.
> aws/signer/v4: Revert #1491, conflicts with undocumented spec test cases

- service/dynamodb/expression/expression.go
- service/dynamodb/expression/expression_test.go
- service/dynamodb/expression/operand.go
- service/dynamodb/expression/update.go
- service/dynamodb/expression/update_test.go
> Implement Update Expression

- service/s3/s3manager/upload.go
Clarifies the S3 Upload Managers concurrency configuration is per call
to Upload, not shared across the instance of the Upload manager.
Fix #1458
> service/s3/s3manager: Clarify S3 Upload manager Concurrency config

- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/decode_test.go
- service/dynamodb/dynamodbattribute/encode.go
- service/dynamodb/dynamodbattribute/encode_test.go
The `dynamodbattribte` package handles aliases of builtin types (e.g. aliased strings, ints, etc.), but not `time.Time`. This PR adds support for aliased `time.Time` types. I added encode/decode tests that mirror the tests for non-aliased `time.Time`.
Modification of #1505
> service/dynamodb/dynamodbattribute: Add support for time alias.

- private/model/api/api.go
- private/model/api/operation.go
- private/model/api/shape.go
- service/elasticsearchservice/api.go
- service/elasticsearchservice/doc.go
- service/iotdataplane/api.go
- service/iotdataplane/doc.go
- service/lambda/api.go
- service/lambda/doc.go
Fixes the SDK's code generation for service API operations and types for
services that do not support crosslinking. The GetCrosslinkURL function
was incorrectly checking for excluded services using the service name,
not the first component of the service's identifier.
> Fix service API crosslinks

- aws/session/env_config.go
Fixes #1444 by moving the `"EnvConfigCredentials" ` string literal into the `EnvProviderName` constant.
> Create EnvProviderName constant.

- models/protocol_tests/generate.go
- private/model/api/api.go
- private/model/api/customization_passes.go
- private/model/api/passes.go
- private/model/api/shape.go
- private/model/api/shape_marshal.go
- private/protocol/decode.go
- private/protocol/encode.go
- private/protocol/fields.go
- private/protocol/header_encoder.go
- private/protocol/metadata.go
- private/protocol/path_replace.go
- private/protocol/path_replace_test.go
- private/protocol/query_encoder.go
- private/protocol/rest/encode.go
- private/protocol/rest/encode_test.go
- private/protocol/restxml/build_test.go
- private/protocol/restxml/encode.go
- private/protocol/restxml/encode_test.go
- private/protocol/restxml/restxml.go
- private/protocol/restxml/unmarshal_test.go
- private/protocol/target.go
- private/protocol/xml/encode.go
- private/protocol/xml/encode_test.go
- service/cloudfront/api.go
- service/route53/api.go
- service/s3/api.go
This change is the start of an iterative set of changes that will
replace the SDK's current reflection base protocol marshalers with
generated code for each API type.
This works starts with the RESTXML protocol's encoders. The following
benchmarks show a significant improvement of execution speed and reduced
memory usage.
Benchmarks of RESTXML build and full request lifecycle between master and this change. `Build` benchmarks focus on just the marshaling of the request's input parameters. `Request` benchmarks provide a view of the impact of the changes in context to a full request lifecycle. Does not include network latency, nor umarshaling of a response object.
```
go test -tags bench -run NONE -bench ".*" -benchmem ./private/protocol/restxml
```
```
benchmark …
```
> API Marshaling: Add generated marshalers for RESTXML protocol

- models/protocol_tests/input/query.json
- private/protocol/query/build_test.go
- private/protocol/query/queryutil/queryutil.go
Fixes the query protocol to correctly marshal nested []byte values of
API operations.
> Fix query protocol handling of nested byte slices

- private/protocol/query/build_test.go
Merge of 62ba2fa9 broke the build because while git though the code was merge-able, but was not. The code generation needed to be re-run, because new test cases were added.
> Fix protocol tests merge error in 62ba2fa9

- private/model/api/customization_passes.go
- service/s3/api.go
- service/s3/s3manager/upload.go
Fixes the SDK's S3 PutObject and UploadPart API code generation to
correctly render the ContentMD5 field into the associated input types
for these two API operations.
Fix #1553
> service/s3: Fix PutObject and UploadPart API to include ContentMD5 field

- service/s3/s3crypto/encryption_client.go
Fixes the documentation example on PutObjectRequest to use a type that implements io.ReadSeeker.
> service/s3/s3crypto: Correct PutObjectRequest documentation

- CONTRIBUTING.md
Just a minor typo fix: `Github` -> `GitHub`. It also fixes a broken link. The current link incorrectly points to non-existing blob/master/issues
> Fix GitHub spelling

- aws/session/session_test.go
Updates the session tests to not depended on the modeled endpoint content.
> aws/session: Fix session test to not depend on modeled endpoint directly

- aws/session/session_test.go
Fixes a session testing bug that caused the test to fail if not run in an environment with shared credentials file.
> aws/session: Fix testing bug in non-dev environment

- .travis.yml
Updates the travis auto builds to only build on `master` branch commits.
PRs are still all built.
This prevents travis from building branch+PR twice. Creating unneeded build jobs.
> Update Travis build on branches

- CHANGELOG_PENDING.md
- aws/client/default_retryer.go
- aws/client/default_retryer_test.go
- aws/request/request_test.go
> aws/client: adding 429, too many requests, to throttling error codes

- aws/request/request.go
- aws/request/request_test.go
- aws/signer/v4/v4.go
Fixes a bug the Request Presign and PresignRequest methods that would
allow a invalid expire duration as input. A expire time of 0 would be
interpreted by the SDK to generate a normal request signature, not a
presigned URL. This caused the returned URL unusable.
Added validation to the presign methods to return an error if the expire
duration is 0 or less.
Even though this is a change in functionality a expire duration less
than 1 is invalid and would not work. http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html
Fix #1617
> aws/request: Fix bug in request presign creating invalide URL

- private/model/api/passes.go
Updates the SDK's code generation stutter filter to not  perform the stutter correction if the correction would result in an empty string.
e.g. ServiceName `ABC` with API operation `ABC` will no longer be converted to an empty string, but stay as `ABC`
> codegen: Fix SDK codegen to not create empty string API names

- models/protocol_tests/generate.go
- models/protocol_tests/input/rest-json.json
- models/protocol_tests/output/rest-json.json
- private/model/api/param_filler.go
- private/protocol/json/jsonutil/build.go
- private/protocol/json/jsonutil/unmarshal.go
- private/protocol/jsonvalue.go
- private/protocol/jsonvalue_test.go
- private/protocol/rest/build.go
- private/protocol/rest/unmarshal.go
- private/protocol/restjson/build_test.go
- private/protocol/restjson/unmarshal_test.go
Adds support for APIs which use JSONValue for body and querystring targets.
Fix #1636
> private/protocol/restjson: Define JSONValue marshaling for body and querystring

- CHANGELOG_PENDING.md
- aws/client/default_retryer.go
- aws/client/default_retryer_test.go
> aws/client: fixing bug where throttled retry's math was off

- service/s3/s3manager/batch.go
- The code examples are missing first argument `aws.Context`
- Originally from
- https://github.com/aws/aws-sdk-go/commit/06f6a4aab0aa9a66df003d882b4224677ff38a64#diff-ce4c43e777b437102576d41814658cd1R111
- https://github.com/aws/aws-sdk-go/commit/06f6a4aab0aa9a66df003d882b4224677ff38a64#diff-ce4c43e777b437102576d41814658cd1R197
- https://github.com/aws/aws-sdk-go/commit/06f6a4aab0aa9a66df003d882b4224677ff38a64#diff-ce4c43e777b437102576d41814658cd1R111 (correct example)
- This change will save time for SDK users who try to figure out the usage from code example.
- Update code examples in comments
> Fix code examples in s3manager/batch comments

- models/customizations/service-aliases.json
- private/model/api/api.go
- private/model/api/api_test.go
Fixes the SDK's code generation for services with lowercase names in the
abbreviation field of the model. This also fixes Title casing
bugs in the StructName method.
Added alias special case for Cost and Usage Report service since the `and` was not being title cased.  For service client names, all words should of been title cased.
> private/model/api: Fix SDK service client name gen for lowercase names

- models/protocol_tests/generate.go
- private/signer/v2/v2_test.go
Fixes Go 1.10 shadowing errors by removing the assert testing util.
> private/signer/v2: remove assert testing util

- aws/defaults/defaults.go
- aws/defaults/defaults_test.go
Refines how the AWS_CONTAINER_CREDENTIALS_FULL_URI endpoint's host value
is validated to include resolving the host only resolves to loopback IPs.
This also makes the loopback validation be more generic including ipv6
::1/128 and 127.0.0.1/8.
> Refine AWS_CONTAINER_CREDENTIALS_FULL_URI host validation

- example/aws/request/customRetryer/README.md
- example/aws/request/customRetryer/custom_retryer.go
Adds and example for writing a custom retryer that will provide
alternative rules for when a request is retried.
In addition to showing how the credentials can be force expired based
on rules in addition to the SDK's defaults.
> example: Add Custom Retry strategy example.

- service/s3/s3crypto/strategy.go
- service/s3/s3crypto/strategy_test.go
> service/s3/s3crypto: only set header tag len if set

- service/s3/bench_test.go
Adds benchmarks for get and put object presign operations.
> service/s3: Add Get/Put object presign benchmark tests

- aws/endpoints/decode.go
- aws/endpoints/decode_test.go
- aws/endpoints/defaults.go
- awstesting/integration/smoke/cloudhsmv2/client.go
- awstesting/integration/smoke/cloudhsmv2/cloudhsmv2.feature
Provides a endpoint customization as a workaround CloudHSMv2 not
modeling the service's signing name correctly. When the model is
eventually updated this change should be removed.
Fix #1745
> aws/endpoints: Workaround CloudHSMv2 signing name not modeled

- aws/request/request_pagination.go
- aws/request/request_pagination_test.go
Fixes the SDK's handling of a Pagination NextToken's value being an
empty string compared to a nil value. The SDK was expecting NextToken's
to always be unset (nil) and treating any non-nil value as a valid
value. This was not the case in MediaLive's List APIs. As those APIs
return a empty string value instead of null or not setting the field at
all.
V1 SDK port of aws/aws-sdk-go-v2#94
> aws/request: Fix Pagination handling of empty string NextToken

- models/apis/check_collisions_test.go
- models/apis/stub.go
- private/model/cli/gen-api/main.go
This change prevents service teams from releasing multiple apis under different names. This has caused dep and builds to fail for some due to insensitive casing and folder naming collisions on specific OS builds.
#1753 
#1755
> models/apis: adds validation to ensure no collision are happening in models/apis

- example/service/ec2/instancesbyRegion/README.md
- example/service/ec2/instancesbyRegion/instancesByRegion.go
Fixed a few typos that I came across while looking at examples.
> Fix typos in ec2 instancesbyRegion example

- aws/session/env_config.go
- aws/session/env_config_test.go
- aws/session/session.go
Fixes a bug in the session.New function that was not correctly sourcing
the shared configuration files' path.
5f43689 broke the session.New's handling of the shared configfuration
files when AWS_SDK_LOAD_CONFIG was enabled, because the default file
paths were moved from the envConfig to NewSessionWithOptions. This
prevented session.New from having access to these values.
Fix #1771
Related to awslabs/amazon-ecr-credential-helper#84
>  aws/session: Fix bug in session.New not supporting AWS_SDK_LOAD_CONFIG

- aws/client/logger.go
- aws/client/logger_test.go
- aws/corehandlers/handlers.go
- aws/corehandlers/handlers_test.go
- aws/request/request.go
- aws/request/request_resetbody_test.go
- aws/request/request_test.go
- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
- aws/types.go
- service/glacier/treehash.go
- service/s3/s3crypto/encryption_client.go
- service/s3/s3manager/upload.go
Fixes the SDK's handling of the SDK's `ReaderSeekerCloser` helper type to
not allow erroneous request retries, and request signature generation.
This fix allows you to use the `aws.ReaderSeekerCloser` to wrap an
arbitrary `io.Reader` for request `io.ReadSeeker` input parameters.
APIs such as lex-runtime's PostContent can now make use of the
ReaderSeekerCloser type without causing unexpected failures.
```go
resp, err := svc.PostContent(&lexruntimeservice.PostContentInput{
BotAlias:    aws.String("botAlias"),
BotName:     aws.String("botName"),
ContentType: aws.String("audio/l16; rate=16000; channels=1"),
UserId:      aws.String("userID"),
InputStream: aws.ReadSeekCloser(myReader),
})
```
Fix #1776
> aws/request: Fix support for streamed payloads for unsigned body request

- aws/ec2metadata/service.go
- aws/ec2metadata/service_test.go
Adds support for the new cross SDK, AWS_EC2_METADATA_DISABLED
environment variable. When this environment variable is set. The SDK's
EC2 Metadata Client will not attempt to make requests. All requests made
with the EC2 Metadata Client will fail.
> aws/ec2metadata: Add support for AWS_EC2_METADATA_DISABLED env var

- service/s3/s3manager/upload.go
Hey all, I use aws-sdk-go in another project that's responsible for doing database backups into S3. We noticed that during s3 upload our process memory was sharply spiking when handling larger files. When I looked into multipart upload, I saw that it wasn't recycling buffers, so I decided to throw this together.
This significantly decreases memory consumption during multipart upload, which should now be `concurrency * partSize`.
I decided to just start working on a fix, but if you would like I could open an issue for this as well to correspond with this PR. Really appreciate your time!
> service/s3/s3manager: Rework multipart upload so that it reuses the same buffers

- aws/session/session.go
`client.ClientConfigProvider` does not exist anywhere in the source.
> Update documentation to point at the correct interface

- .travis.yml
Adds Go 1.10 to travis test matrix.
> Update travis CI tests to include Go 1.10

- service/s3/s3manager/bucket_region.go
- service/s3/s3manager/bucket_region_test.go
Updates the GetBucketRegion to fallback to the provided ConfigProvider's
(aka Session) region value if the regionHint parameter is not specified.
The call will still fail if no region value can be found.
Related #1600
> service/s3/s3manager: Update GetBucketRegion region hint fallback

- aws/corehandlers/handlers.go
- aws/corehandlers/user_agent.go
- aws/corehandlers/user_agent_test.go
- aws/defaults/defaults.go
Adds support for the `AWS_EXECUTION_ENV` environment variable to the SDK's user agent string.
> aws/corehandlers: Add support for AWS_EXECUTION_ENV env var

- aws/client/default_retryer.go
- aws/request/request_test.go
Prevents the SDK from retrying HTTP status code 501 by default. This brings the AWS SDK for Go in parity with other SDKs which were not retrying this status code.
Fix #1819
> aws/client: 501, 'NotImplemented', will no longer be retried

- aws/endpoints/decode.go
- aws/endpoints/defaults.go
- awstesting/integration/smoke/sagemakerruntime/client.go
- awstesting/integration/smoke/sagemakerruntime/sagemakerruntime.feature
Missing endpoint information. This customization will use the correct signing name when generating endpoint data.
Fix #1836
> aws/endpoints: adding custom signing name for runtime.sagemaker

- aws/config.go
- awstesting/integration/customizations/s3/object_checksum_test.go
- service/s3/customizations.go
Updates the S3 client to disable automatic ContentMD5 validation of S3
Put and Get objects. This disables the validation added in #1827.
Unexpected case where`Content-Length` response header not set in an a GetObject API call prevents this the content MD5 validation feature from being successfully used until the SDK can handle the case.
The SDK will still set the `Content-MD5` header for PutObject and UploadPart API calls.
Related to: #1837
> service/s3: Disable S3 object ContentMD5 automatic validation

- service/s3/s3manager/batch.go
- service/s3/s3manager/batch_test.go
Amazon S3 error messages from `DeleteObjects` would get dropped and provide no meaningful error message back to the user. This fix will create a new error from that message, if one exists. In addition, `BatchError` had a specific message of uploading even if the operation being performed wasn't uploading. This has been resolved to being more generic.
Fix #1849
> service/s3/s3manager: fixing error string and error messages being lost

- aws/request/request.go
Fix the typo "Anny" in the comment for `Build`.
> aws/request: Fix a typo in a comment

- private/model/api/api.go
- private/model/api/eventstream.go
- private/model/api/eventstream_test.go
- private/model/api/load.go
- private/model/api/passes.go
- private/model/api/shape.go
Supresses API operations decorated with EventStream traits. This
suppression is needed until the SDK implements support for event streams.
> private/model/api: Add suppression of Eventstream models

- private/model/api/operation.go
Typo: "complets" -> "completes"
> private/model/api: Fix typo in docs.

- models/protocol_tests/output/rest-xml.json
- private/protocol/restxml/unmarshal_test.go
- private/protocol/xml/xmlutil/unmarshal.go
Fixes a bug in the XML unmarshaler that would incorrectly try to
unmarshal "time.Time" parameters that did not have the struct tag `type`
on them. This would occur for nested lists like CloudWatch's
`GetMetricDataResponse` `MetricDataResults` timestamp parameters.
Adds protocol tests for XML unmarshaling with list of timestamps.
Fix #1892
> Fix XML unmarshaler not correctly unmarshaling list of timestamp values

- aws/endpoints/endpoints.go
- aws/endpoints/endpoints_test.go
Exposing the description field of the Region struct.
Issue for this PR is: https://github.com/aws/aws-sdk-go/issues/1194
> aws/endpoints: Add Get Region description

- private/protocol/xml/xmlutil/unmarshal.go
Updates the xmlutil unmarshaler removing processing of JSONValue types
as the JSONValue is not supported by RESTXML yet by the SDK.
Related #1894
> private/protocol/xml/xmlutil: Remove processing of JSONValue from unmarhsaler

- aws/request/request_pagination.go
- aws/request/request_pagination_test.go
- private/model/api/operation.go
- private/model/api/pagination.go
- service/cloudwatchlogs/api.go
- service/s3/s3manager/batch_test.go
This PR expands on #1908 allowing for a boolean to specify whether or not a paginator needs to stop in the case where two tokens are the same.
To use this in the general paginator simply set the `EndPageOnSameToken` to true.
cc @johanneswuerbach
> aws/request: fixing pagination with cloudwatchlogs

- service/s3/host_style_bucket_test.go
- service/s3/testdata/virtual_host.json
Adds unit tests to verify the S3 endpoint format building is correct in the SDK.
> service/s3: Add endpoint format  test

- models/protocol_tests/generate.go
- private/protocol/jsonrpc/unmarshal_test.go
- private/protocol/query/unmarshal_test.go
- private/protocol/rest/build.go
- private/protocol/rest/unmarshal.go
- private/protocol/restjson/unmarshal_test.go
- private/protocol/restxml/unmarshal_test.go
Updates the REST protocol's timestamp format to not require GMT as the
timezone value parsed. Switching to MST in the parse format string
allows the SDK to parse other timezones.
The SDK will continue to format the timezone as GMT when serialzing out
the timestamp value for REST protocol.
Related to aws/aws-sdk-go-v2#178
Fix #1937
> private/protocol/rest: Update REST protocol timestamp parse format

- service/dynamodb/expression/expression.go
- service/dynamodb/expression/expression_test.go
Fix method according to the comment.
https://github.com/aws/aws-sdk-go/blob/master/service/dynamodb/expression/expression.go#L486
> service/dynamodb/expression: Return nil when expression dose not exists

- private/model/api/api.go
- service/mediatailor/service.go
- service/neptune/service.go
- service/pi/service.go
Updates the protocol test code generation to not duplicate the ServiceID const for each protocol tests within the same package.
>  private/model/api: Update protocol test codgen for ServiceID duplication

- .travis.yml
- Makefile
- buildspec.yml
Updates the Travis tests to ensure that any code generation changes are accounted for in the PR, and that there were no mistaken changes made without also running code generation. This change should also help ensure that code generation order is stable, and there are no ordering issues with the SDK's codegen.
> Update Travis tests to ensure all codegen changes are accounted for in PR

- doc-src/aws-godoc/templates/style.css
iPhone devices were unable to scroll the service package menu in the doc website. This fixes the CSS to allow for all devices to be able to scroll.
> doc-src/aws-godoc/templates: fixing iOS scrolling issue

- aws/credentials/credentials.go
- aws/credentials/credentials_bench_test.go
Updates the Credentials type's cache of the CredentialsValue to be synchronized with a RWMutex instead of Mutex. This reduces the overhead applications will encounter when many concurrent API requests are being made.
Benchmarks of Credential.Get improvements. This will be the normal case until credentials expire. Each benchmark increases the number of concurrent gets.
benchmark                                         old ns/op     new ns/op     delta
BenchmarkCredentials_Get/1-4                      64.0          33.5          -47.66%
BenchmarkCredentials_Get/10-4                     1162          545           -53.10%
BenchmarkCredentials_Get/100-4                    16016         5424          -66.13%
BenchmarkCredentials_Get/500-4                    62655         27175         -56.63% …
> aws/credentials: Update Credentials cache to use RWMutex

- .godoc_config
Update the SDK's doc generation to ignore the private folder when generating docs.
> Ignore private folder for doc generation

- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/decode_test.go
- service/dynamodb/dynamodbattribute/doc.go
The sdk docs explain how the Convert* functions are deprecated and (Un)marshal should be used instead. But Unmarshalling data originally created with Convert* can have issues which I've not seen mentioned in the docs. We ran into this issue in our most recent Vault release: https://github.com/hashicorp/vault/issues/4721
This PR adds special handling if string data is the source for a byte slice field. Previously, an Unmarshalling error would be returned. Now, if the string is valid base64 data--as it would be if it came from Convert*--then it will be decoded as base64 and saved as bytes.
> service/dynamodb/dynamodbattribute: Retain backwards compatibility with ConvertTo

- aws/signer/v4/functional_test.go
- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
Fixes the bug which would allow the X-Amz-Content-Sha256 header to be
promoted to the query string when presigning a S3 request.
This bug also was preventing users from setting their own sha256 value
for a presigned URL. Presigned requests generated with the custom sha256
would of always failed with invalid signature.
S3 presign requests without a user specified X-Amz-Content-Sha256 will
no longer include the X-Amz-Content-Sha256 in the header nor query. The
X-Amz-Content-Sha256 header only needs to be set if it contains a non
UNSIGNED-PAYLOAD value.
Fix #1974
> aws/signer/v4: Fix X-Amz-Content-Sha256 being in to query for presign

- service/s3/eventstream_test.go
Moves the SelectObjectContent doc example to the SelectObjectContent API instead of under the nested EventStream shape.
> service/s3: Move SelectObjectContent doc example to API

- aws/client/client.go
- aws/client/logger.go
- aws/client/logger_test.go
- private/model/api/operation.go
- service/s3/api.go
Fixes the SDK's HTTP client debug logging to not log the HTTP response
body for EventStreams. This prevents the SDK from buffering a very large
amount of data to be logged at once. The aws.LogDebugWithEventStreamBody
should be used to log the event stream events.
Also fixes a bug in the SDK's response logger which will buffer the
response body's content if LogDebug is enabled but LogDebugWithHTTPBody
is not.
> aws/client: Fix HTTP debug log EventStream payloads

- example/service/s3/putObjectWithProcess/README.md
- example/service/s3/putObjectWithProcess/putObjWithProcess.go
I added a simple way to  track the upload progress, a little trick only
> add example for file upload with progress

- aws/session/doc.go
> Fixing typo "arfrom" to "are from"

- private/model/api/codegentest/models/jsonrpc/0000-00-00/api-2.json
- private/model/api/codegentest/models/restjson/0000-00-00/api-2.json
- private/model/api/codegentest/models/restxml/0000-00-00/api-2.json
- private/model/api/codegentest/service/restjsonservice/api.go
- private/model/api/codegentest/service/restjsonservice/eventstream_test.go
- private/model/api/codegentest/service/restjsonservice/restjsonserviceiface/interface.go
- private/model/api/codegentest/service/restxmlservice/api.go
- private/model/api/codegentest/service/restxmlservice/eventstream_test.go
- private/model/api/codegentest/service/restxmlservice/restxmlserviceiface/interface.go
- private/model/api/codegentest/service/rpcservice/api.go
- private/model/api/codegentest/service/rpcservice/eventstream_test.go
- private/model/api/codegentest/service/rpcservice/rpcserviceiface/interface.go
- private/model/api/eventstream.go
- private/protocol/eventstream/header_value.go
- service/s3/eventstream_test.go
Fixes eventstream generated tests for APIs without any response members. Adds additional empty response modeled APIs to codegentests covering this case.
> private/model/api: Add tests for empty response event stream API codegen

- service/s3/s3crypto/decryption_client_test.go
- service/s3/s3crypto/kms_key_handler.go
Providing a custom KMS client into the wrap entries was impossible without implementing a separate interface. This allows customers to use the existing decrypt handler built in `kmsDecryptHandler`
> service/s3/s3crypto: adding NewKMSWrapEntry

- private/model/api/codegentest/service/restjsonservice/api.go
- private/model/api/codegentest/service/restxmlservice/api.go
- private/model/api/codegentest/service/rpcservice/api.go
- private/model/api/eventstream.go
Fixes the EventStream's exception message member not being code
generated into the Message method.
> private/model/api: Fix EventStream Exception message codegen

- private/model/api/api.go
- private/model/api/load.go
- private/model/api/passes.go
- private/model/api/passes_test.go
Prevents the SDK from generating EventStream based API operation which
are required to be performed over HTTP/2.
> private/model/api: Prevent codegen of EventStream over HTTP/2 until supported

- service/s3/eventstream_exampe_test.go
Stats.BytesProcessed is an *int64, needs to be dereferenced before formatting.
This produced some surprising (and rather alarming in terms of cost :) ) output while I was playing around with S3 select, e.g.
Processed 842353860960 bytes
> Dereference *int64 BytesProcessed in S3 select example

- private/model/api/eventstream.go
- private/model/api/load.go
- private/model/api/passes.go
- private/model/api/passes_test.go
- private/model/api/shape.go
Fixes the SDK's eventstream over HTTP/2 suppression, and fixes the SDK's code generation test cases incorrectly being skipped due to an invalid build tag.
> private/model/api: Fix eventstream over HTTP/2 suppression and tests

- aws/credentials/ec2rolecreds/ec2_role_provider.go
- aws/credentials/ec2rolecreds/ec2_role_provider_test.go
- aws/ec2metadata/api.go
- internal/sdkuri/path.go
- internal/sdkuri/path_test.go
Updates #2002 to preserve the trailing slash on EC2 Metadata requests. This removes the unnecessary redirect for `/latest/meta-data/iam/security-credentials/`.
> aws/credentials/ec2rolecreds: Avoid unnecessary redirect

- aws/csm/reporter.go
This allows nested error messages to be added
> aws/csm: adding more verbose error messages

- Makefile
- private/model/api/passes.go
Fixes the SDK's CI validation of generated models to ignore whitespace changes. Addresses the issue with gofmt formatting differing between versions of Go
> Ignore whitespace changes in model generation checks

- service/s3/s3manager/upload.go
Updates the S3 Upload Manager's default behavior for MaxNumParts, and
ensures that the Uploader.MaxNumPart's member value is initialized
properly if the type was created via struct initialization instead of
using the `NewUploader` function.
Fix #2015
> service/s3/s3manager: Document default behavior for Upload's MaxNumParts

- service/s3/s3manager/batch.go
iter.Next() can run into a permissions issue (ie can't s3:ListBucket) and populate iter.Err() while returning false. currently the code will just silently eat the error and calls like NewBatchDeleteWithClient().Delete() will indicate success but leave later DeleteBucket() calls to fail because the bucket is not empty.
after exiting the iter.Next() loop, check for any error that might have been set. while the output is not ideal, some error is better than none. it now looks like:
BatchedDeleteIncomplete: some objects have failed to be deleted.                        
caused by: failed to perform batch operation on "" to "":
AccessDenied: Access Denied
status code: 403, request id: REQUEST_ID, host id: HOST_ID
For changes to files under the `/model/` folder, and manual edits to …
> check for error on iter.Next()

- CHANGELOG_PENDING.md
- private/protocol/xml/xmlutil/build.go
- private/protocol/xml/xmlutil/build_test.go
Fixes the SDK's marshaling of types without members. This corrects the
issue where the SDK would not marshal an XML tag for a type, if that
type did not have any exported members.
Fix #2015
> private/protocol/xml/xmlutil: Fix SDK marshaling of empty types

- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/encode.go
- service/dynamodb/dynamodbattribute/field.go
- service/dynamodb/dynamodbattribute/marshaler_test.go
- service/dynamodb/dynamodbattribute/tag.go
- service/dynamodb/dynamodbattribute/tag_test.go
This allows structs defined with the `yaml` struct tag to be parsed in the same fashion as the `json` struct tag.
Where I work, we have many YAML configurations we map directly to DynamoDB tables. Being able to have the struct tags supported would be tremendously useful for us.
> service/dynamodb/dynamodbattribute: Add support for custom struct tag keys

- aws/credentials/credentials.go
- aws/credentials/credentials_test.go
Removes the unnecessary setting Expiry's CurrentTime member when
IsExpired method is called. This prevents the possibility of a data race
with the Expiry's IsExpired method.
> aws/credentials: Remove unnecessary modification of Expiry CurrentTime

- example/service/s3/sync/sync.go
Not sure if this is preferred, but I used this in some code for uploading some static HTML / CSS / JS, and S3 needed the ContentType to not just send the content as binary/octet-string. 
This will work when there's no file extension, as it will look up ".name".  This only gets funky if you have a file called "js", "html", etc.
> example/service/s3/sync: Adding mimetype handling to the sync example

- aws/signer/v4/v4.go
- aws/signer/v4/v4_test.go
Determine the body length and use `io.CopyN` instead of `io.Copy`
because the latter would otherwise allocate a 32KB temporary buffer.
This provides a 4x reduction in bytes allocated by Sign and a little performance bump:
```
name                 old time/op    new time/op    delta
PresignRequest-4       38.1µs ±13%    29.6µs ± 2%  -22.42%  (p=0.008 n=5+5)
SignRequest-4          28.4µs ±14%    20.1µs ± 2%  -29.07%  (p=0.008 n=5+5)
StripExcessSpaces-4     868ns ± 2%     892ns ± 1%   +2.76%  (p=0.032 n=5+5)
name                 old alloc/op   new alloc/op   delta
PresignRequest-4       46.1kB ± 0%    13.3kB ± 0%     ~     (p=0.079 n=4+5)
SignRequest-4          42.6kB ± 0%     9.9kB ± 0%  -76.83%  (p=0.008 n=5+5)
name                 old allocs/op  new allocs/op  delta
PresignRequest-4 …
```
> aws/signer/v4: avoid 32KB alloc when hashing body

- private/model/api/api.go
- private/model/api/operation.go
- private/model/api/shape.go
- service/applicationdiscoveryservice/api.go
- service/appstream/api.go
- service/cloudfront/api.go
- service/cloudtrail/api.go
- service/databasemigrationservice/api.go
- service/directconnect/api.go
- service/elasticache/examples_test.go
- service/elastictranscoder/api.go
- service/emr/api.go
- service/firehose/api.go
- service/iam/examples_test.go
- service/iot/api.go
- service/lambda/api.go
- service/lightsail/api.go
- service/mediapackage/api.go
- service/mturk/api.go
- service/neptune/api.go
- service/opsworkscm/api.go
- service/rds/examples_test.go
- service/route53domains/api.go
- service/s3/api.go
- service/s3/bucket_location_test.go
- service/s3/s3crypto/decryption_client.go
- service/s3/sse_test.go
- service/shield/api.go
- service/workdocs/api.go
> private/model/api: adding deprecation string to doc string

- service/s3/s3manager/download.go
Fixes the S3 Download manager's DownloadWithIterator documentation
example.
Fix #1824
> service/s3/s3manager: Fix Download Manager with iterator docs

- private/protocol/ec2query/unmarshal.go
- private/protocol/jsonrpc/jsonrpc.go
- private/protocol/query/unmarshal.go
- private/protocol/query/unmarshal_error.go
- private/protocol/restjson/restjson.go
- private/protocol/restxml/restxml.go
- private/protocol/unmarshal_test.go
This change will allow serialization errors that were being returned during unmarshaling to be wrapped in a `awserr.RequestFailure` instead. This allows for custom retryers to get at the status code more easily.
> private/protocol: wrapping serialization errors 

- private/protocol/json/jsonutil/unmarshal.go
closed: #2114 
https://gist.github.com/atsushi-ishibashi/2d7d13cf1df9a84251ed175816a04b14
The below shows that the new `UnmarshalJSON` decrease memory capacity by 50%.
```
//current
BenchmarkUnmarshalJSON-4    	 1000000	      2122 ns/op	    2928 B/op	      18 allocs/op
//new one
BenchmarkUnmarshalJSON2-4   	 1000000	      1654 ns/op	    1480 B/op	      17 allocs/op
```
>  private/protocol/json/jsonutil: Use json.Decoder to decrease memory allocation

- aws/config.go
fix typo in `Config struct` documentation in [aws-sdk-go/aws/config.go](https://github.com/aws/aws-sdk-go/blob/2c6fb0737fb299300b5f082701aac627244ab28a/aws/config.go#L21)
> fix typo in Config struct documentation

- service/cloudfront/sign/policy.go
- service/cloudfront/sign/policy_json_1_6.go
- service/cloudfront/sign/policy_json_1_7.go
- service/cloudfront/sign/policy_test.go
- service/cloudfront/sign/sign_url_test.go
> Do not Escape HTML when encode the cloudfront sign policy

- private/model/api/api.go
- service/s3/service.go
Updates the SDK's code generate to make use of the model's service
signature version when generating the client for the service. This
allows the SDK to generate a client using the correct signature version,
e.g v4 vs s3v4 without the need for additional customizations.
> private/model/api: Use modeled service signing version in code generation

- aws/request/validation.go
- private/protocol/host.go
- private/protocol/host_test.go
Adds support for validation of host domain name labels based on RFC 1123
specification.
> private/protocol: Add domain host name label validation

- README.md
Updates the README.md to use HTTPs endpoints for the badge links.
> Update README to use HTTPs endpoint for badges

- aws/csm/metric.go
- aws/csm/reporter.go
- aws/csm/reporter_internal_test.go
- aws/csm/reporter_test.go
Adds an additional metric, `MaxRetriesExceeded`. This will compare the `request.RetryCount` with the `request.Config.MaxRetries` and will set `1` is retry count is at least the `MaxRetries` and `0` otherwise.
> aws/csm: adding MaxRetriesExceeded metric

- Makefile
Updates the SDK's Makefile to use `golang.org/x/lint/golint` instead of `github.com/golang/lint/golint`. lint package was updated to use `golang.org/x` root in golang/lint@9a272034
> Update SDKs Makefile to use golang.org/x/lint/golint pkg rename

- .travis.yml
- Makefile
Golang version 1.7 and 1.8 were failing in Travis. This now will skip the verify test which runs vet and lint.
> adding ci-test-no-verify in make

- aws/request/request.go
Clarifies the request Presign method's expire parameter only will be used for Amazon S3 presigned API requests. All other AWS services will use a fixed request signature expiration of about 15 minutes.
Fix #2167
> aws/request: Clarify Presign expire parameter

- aws/config.go
- aws/credentials/chain_provider.go
- aws/credentials/credentials.go
- aws/credentials/env_provider.go
- aws/credentials/static_provider.go
- aws/errors.go
Cleans up @ annotations in the SDK's documentation. Use Go style "Note:"
instead of @note, and improve the wording of @see to be natural text
instead of annotation.
> Cleanup SDK documentation annotations

- internal/ini/comment_token.go
- internal/ini/doc.go
- internal/ini/ini_parser.go
- internal/ini/ini_parser_test.go
- internal/ini/skipper.go
- internal/ini/statement.go
This change fixes a bug where `//` were parsed to be comments which was not previously supported. In addition, fixed the skipper to break out of the parse loop if there are no tokens left to parse and we are in a skip state which was discovered to be a bug during updating of the `//` comment tests.
Fixes #2239
> internal/ini: fixing bug where '//' was assumed to be a comment

- aws/signer/v4/v4.go
Adds "X-Amz-Tagging" header to `requiredSignedHeaders` so tagging is included in S3 presigned URLs.
Fix #2221
> aws/signer/v4: Add "x-amz-tagging" to whitelist

- internal/ini/ini_parser.go
- internal/ini/testdata/valid/space_lhs
- internal/ini/testdata/valid/space_lhs_expected
Fixes #2263 
The LHS of equal expression did not allow for spaces unless they were quoted. This is was supported previously and this PR is to maintain that.
> internal/ini: allowing LHS of equal expression to contain spaces

- CHANGELOG.md
Fixes the CHANGELOG's Bug entry not having a trailing new line, and causing the following Release to be squashed together in the same paragraph.
> Fixup CHANGELOG release separation

- internal/ini/ini_parser.go
- internal/ini/testdata/valid/issue_2281
- internal/ini/testdata/valid/issue_2281_expected
- internal/ini/trim_spaces_test.go
Fixes #2281 
Copy pasta bug. Do not need to decrement i twice when trimming RHS.
> internal/ini: trimming rhs spaces issue

- README.md
Updates the SDK's README.md to clarify the instructions for getting the SDK. This also avoids the potential issues getting the SDK with Go modules and retrieving a non-working version of SDK dependencies.
Related to golang/go#28396
> Update README to clarify getting SDK with go modules

- aws/session/session.go
- private/model/api/codegentest/service/awsendpointdiscoverytest/endpoint_discovery_test.go
- service/s3/s3manager/upload_test.go
Fixes EndpointDiscovery mock client's test to consistently pass. The
previous test would periodically fail based on timing.
Fixes S3 Upload Manager's unstable unexpected EOF test to be stable.
> Fix SDK's EndpointDiscovery and S3 Upload Manager unstable tests

- private/model/api/load.go
- private/model/api/load_test.go
Updates the model loading to preserve the filename provided in the glob.
This allows loading model filenames that are not "api-2.json".
Fixes the bug where the code generation would fail to load a model with
a custom filename.
> private/model/api: Update model loading to preserve model filename

- aws/crr/cache.go
- go.mod
- go.sum
- private/model/api/codegentest/service/awsendpointdiscoverytest/endpoint_discovery_test.go
Fixes the SDK's endpoint discovery async unit test to be stable, and
produce consistent unit test results.
> Fixup endpoint discovery unit test to be stable

- private/model/api/load.go
Fixes the SDK's model loading to not require that the docs model be
present. This model isn't explicitly required.
> private/model/api: Fix model loading to not require docs model.

- aws/request/retryer.go
Adds a new throttle error code the SDK should react to when determining if
a request should be throttled.
> aws/request: Add additional throttle error code

- aws/config.go
- aws/request/validation.go
- models/protocol_tests/generate.go
- models/protocol_tests/input/ec2.json
- models/protocol_tests/input/json.json
- models/protocol_tests/input/query.json
- models/protocol_tests/input/rest-json.json
- models/protocol_tests/input/rest-xml.json
- private/model/api/api.go
- private/model/api/endpoint_trait.go
- private/model/api/operation.go
- private/model/api/shape.go
- private/model/api/shape_validation.go
- private/protocol/ec2query/build_test.go
- private/protocol/host.go
- private/protocol/host_prefix.go
- private/protocol/host_prefix_test.go
- private/protocol/host_test.go
- private/protocol/jsonrpc/build_test.go
- private/protocol/query/build_test.go
- private/protocol/restjson/build_test.go
- private/protocol/restxml/build_test.go
Adds support for an operation to be modeled with a endpoint host prefix
template. The template will be expanded when the request is built. The
template may use members from the operation's input struct to populate
the template.
> private/model/api: Add support for modeled operation endpoint

- service/s3/customizations.go
Updates the S3 client to autofill the Content-MD5 header for the
PutObjectLegalHold, PutObjectRetention, and PutObjectLockConfiguration
operations.
> service/s3: Update S3 operations to autofill Content-MD5 header

- aws/session/doc.go
This PR fixes a minor issue in `aws/session/doc.go` where the developer mistakenly used format specifiers in `logger.Println`.
Changes committed:
modified:   aws/session/doc.go
Signed-off-by: Abhishek Kashyap <avskksyp@gmail.com>
> aws/session: Fix formatting bug in doc.

- Makefile
Updates the SDK's CI integration make task to ignore the environment's
specified region. SDK integration tests are generated for specific
regions. The environment's overrides the integration test's specified
region.
> Update SDK's CI integration test to ignore environment's region.

- aws/csm/reporter.go
- aws/csm/reporter_test.go
- aws/request/handlers.go
- aws/request/request.go
- aws/request/timeout_read_closer_test.go
Fixes duplicate request attempt metrics being reported when the request fails or retries.
> aws/request: Fix duplicate request attempt metric reporting

- private/model/api/api.go
- private/model/api/shape.go
- service/athena/api.go
- service/robomaker/api.go
- service/servicecatalog/api.go
- service/signer/api.go
Fixes the SDK's usage of API operation request members marked as
idempotency tokens to not require validation. These fields will be
auto populated by the SDK if the user does not provide a value. The SDK
was requiring the user to provide a value or disable validation to use
these APIs.
> private/mode/api: Fix idempotency members not to require validation

- Gopkg.lock
Updates Go dep's lock file to contain the correct tracking hash. The Gopkg.toml file was updated in #2284 but the lock file was missed.
> deps: Update Go Deps lock file to correct tracking hash

- aws/corehandlers/user_agent.go
- aws/corehandlers/user_agent_test.go
Fixes the execution environment variable's identifier used in the SDK's user agent. Was using underscore(_) instead of dash(-).
> aws/corehandlers: Fix execution environment user agent identifer

- private/model/api/load.go
Updates SDK code generation to remove unused shapes sooner in the process. This prevents unused shapes from colliding with the SDK's renamed type names.
> private/model/api: Remove unused shapes before processing model

- aws/credentials/chain_provider_test.go
- aws/credentials/credentials_test.go
- aws/credentials/ec2rolecreds/ec2_role_provider_test.go
- aws/credentials/env_provider_test.go
- aws/credentials/shared_credentials_provider_test.go
- aws/credentials/static_provider_test.go
- aws/credentials/stscreds/assume_role_provider_test.go
- aws/request/http_request_retry_test.go
- aws/request/offset_reader_test.go
- aws/request/request_1_6_test.go
- aws/request/request_pagination_test.go
- aws/request/waiter_test.go
- aws/session/session_test.go
- aws/session/shared_config_test.go
- private/protocol/idempotency_test.go
- private/protocol/json/jsonutil/build_test.go
- private/protocol/protocol_test.go
- private/protocol/unmarshal_test.go
Updates the SDK's unit tests to not use a testing framework and instead
use the Go standard library's provided testing calls directly.
> Update unit tests to not use testing framework.

- service/dynamodb/expression/expression.go
Clarifies the expression package's examples to distinguish the pkg expression from a expr value.
> service/dynamodb/expression: Clarify expression examples

- aws/ec2metadata/api.go
- aws/ec2metadata/api_test.go
We use the SDK to detect if our product is running in AWS via requesting EC2 metadata, however we've been made aware of instances of the SDK causing an [out-of-bounds panic](https://github.com/storageos/storageos.github.io/issues/251) during initialisation. After a bit of digging it is believed their environment includes an non-AWS API listening on the metadata IP (169.254.169.254) which is returning empty responses in response to Region metadata requests.
This crash has also been observed in the Amazon SSM agent (see [here](https://github.com/aws/amazon-ssm-agent/issues/81)). 
While the AWS SDK shouldn't really have to handle different customer environments, it probably should return an error when presented with invalid data rather than panicking. `Region()` could perform better …
> ec2metadata: bounds check region identifier before string split

- aws/session/doc.go
- doc-src/aws-godoc/templates/package_service.html
- Fix pkg-constants anchor in documentation.
- Reorder links in short-nav to match actual order in document.
Example page with broken Constants link: https://docs.aws.amazon.com/sdk-for-go/api/service/sts/
I also noticed that this link has the `examplesLink` class, which may also be a mistake? I didn't remove it since I'm not sure if it is a mistake or not.
> Documentation link fix

- aws/credentials/credentials.go
- aws/credentials/credentials_test.go
Add an Expirer interface that Providers can implement, and add a suitable
implementation to Expiry class used by most Providers. Add a method on
Credentials to get the expiration time of the underlying Provider, if
Expirer is supported, without exposing Provider to callers.
Provides partial solution to issue #1329 discussion.
> Support credential caching by sdk users.

- private/model/api/customization_passes.go
- service/s3control/api.go
- service/s3control/customizations.go
Updates the S3 Control services code generation to use the modeled endpoint trait if available. Will fallback to injecting the customization if no trait is set.
> service/s3control: Update codegen to use modeled endpoint

- aws/endpoints/decode.go
- aws/endpoints/decode_test.go
- aws/endpoints/defaults.go
Adds workaround to correct the endpoint for Application Autoscaling running in AWS GovCloud (US).
Fixes #2391
Verified via terraform-provider-aws acceptance testing:
```
--- PASS: TestAccAWSAppautoScalingTarget_basic (47.09s)
```
> aws/endpoints: Add customization for AWS GovCloud (US) Application Autoscaling

- aws/request/request.go
- aws/request/request_test.go
Updates the SDK to ensure refused connections are retried. url.Error
does not consider these errors to be temporary. This was preventing the
SDK from retrying refused connections.
Related to #2298
> aws/request: Add retrying refused connections

- aws/context_test.go
- aws/request/request.go
- aws/request/request_retry_test.go
Fixes unstable unit tests in the SDK's request package.
* TestSleepWithContext_Canceled - Adjusts the delay to be more reasonable, reducing the risk of timer triggering before the switch's ctx.Done is checked.
* TestShouldRetryCancel_cancelled - Ensure the request cancel doesn't occur until after the request has started to ensure the error returned from the request invoke is consistent.
> aws/request: Fix unstable sleep and request tests.

- aws/context_1_5.go
- aws/context_1_7.go
- aws/context_1_9.go
- aws/context_background_1_5.go
- aws/context_background_1_7.go
- aws/context_sleep.go
Updates `aws.Context` interface to be an alias of the standard libraries `context.Context` type instead of redefining the interface. This will allow IDEs and utilities to interpret the `aws.Context` as the exactly same type as the standard libraries `context.Context`.
> aws: Update Context to be an alias of context.Context for Go 1.9

- service/s3/unmarshal_error.go
- service/s3/unmarshal_error_test.go
Updates the BucketRegionError error message to include information about
the endpoint and actual region the bucket is in if known. This error
message is created by the SDK, but could produce a confusing error
message if the user provided a region that doesn't match the endpoint.
Fix #2426
> service/s3: Update BucketRegionError message to include more information

- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_test.go
Updates the Location returned value of S3 Upload's Multipart
UploadOutput type to be consistent with single part upload URL. This
update also brings the multipart upload Location inline with the S3
object URLs created by the SDK
Fix #1385
> service/s3/s3manager: Update S3 Upload Multipart location

- aws/request/request_test.go
Fixes the request User-Agent unit tests to be stable across all
platforms and environments.
Fix #2366
> aws/request: Fix RequestUserAgent tests to be stable

- aws/client/logger.go
- aws/ec2metadata/service.go
- aws/ec2metadata/service_test.go
Fixes a panic that could occur witihin the EC2 Metadata client when both
`AWS_EC2_METADATA_DISABLED` env var is set and log level is
LogDebugWithHTTPBody. The SDK's client response body debug functionality
would panic because the Request.HTTPResponse value was not specified.
Updates the client debug loggers to check if the response is set before
attempting to log.
> aws/ec2metadata: Fix EC2 Metadata client panic with debug logging

- models/protocol_tests/generate.go
- models/protocol_tests/input/rest-json.json
- models/protocol_tests/input/rest-xml.json
- models/protocol_tests/output/ec2.json
- models/protocol_tests/output/query.json
- models/protocol_tests/output/rest-json.json
- models/protocol_tests/output/rest-xml.json
- private/protocol/ec2query/unmarshal_test.go
- private/protocol/jsonrpc/build_test.go
- private/protocol/query/unmarshal_test.go
- private/protocol/rest/build.go
- private/protocol/restjson/build_test.go
- private/protocol/restjson/unmarshal_test.go
- private/protocol/restxml/build_test.go
- private/protocol/restxml/unmarshal_test.go
Updates the REST protocol marshaler to trip leading and trailing space from header keys and values before setting the HTTP request  header.
Fixes a bug when using S3 metadata where metadata values with leading spaces would trigger request signature validation errors when the request is received by the service.
Fix #2448
> private/protocol/rest: Trim space in header key and value

- service/s3/s3manager/upload_test.go
Fixes the brittle S3 Uploader test validating the message contents. The
original test was not correctly testing what it was supposed to.
Related to #2429
> service/s3/s3manager: Fix brittle upload test

- aws/session/cabundle_transport.go
- aws/session/cabundle_transport_1_5.go
- aws/session/cabundle_transport_1_6.go
- aws/session/custom_ca_bundle_test.go
- aws/session/session.go
Ensures HTTP_PROXY environment variable is read when specifying AWS_CA_BUNDLE environment variable.
Fix #2287
> aws/session: Use HTTP_PROXY environment variable when AWS_CA_BUNDLE is specified

- example/service/s3/getObjectWithProgress/README.md
- example/service/s3/getObjectWithProgress/getObjectWithProgress.go
* Uses io.WriterAt to determine progress
* `cheggaa/pb` is the most popular golang progress bar libraries
* Great example for future peoples!
> Adds example of S3 download with progress

- .travis.yml
- Makefile
- buildspec.yml
Updates the SDK's Makefile to and CI steps to explicitly get dependencies instead of implicitly via make commands. Improves behavior for CI environments with dependencies already vendored.
> Update SDKs CI tests to require explict get of dependencies

- aws/ec2metadata/api.go
output.Content in blank, and since its not a pointer the string is already copied for return, after which req.Send() is called.
This cause problem where req.Send() returns proper result but output.Content is not changed after calling req.Send() as its not a pointer but a string value.
#1861
> aws/ec2metadata: Improve readability of Send calls

- aws/request/retryer.go
Adds RequestThrottledException to the set of the SDK's throttled exceptions to retry and rate limit.
> aws/request: Add RequestThrottledException to set of throttled exceptions

- README.md
Updates wording of SDK README to be more clear.
> Fix typo in SDK's README

- service/dynamodb/dynamodbattribute/decode.go
- use exported interface in method
- convert int64 value to target field's int type
> service/dynamodb/dynamodbattribute: Fix Unmarshaler doc example

- .travis.yml
- Makefile
- awstesting/sandbox/Dockerfile.test.go1.10
- awstesting/sandbox/Dockerfile.test.go1.12
- awstesting/sandbox/Dockerfile.test.go1.5
- awstesting/sandbox/Dockerfile.test.go1.5-novendorexp
- awstesting/sandbox/Dockerfile.test.go1.6
- awstesting/sandbox/Dockerfile.test.go1.7
- awstesting/sandbox/Dockerfile.test.go1.8
- awstesting/sandbox/Dockerfile.test.go1.9
- awstesting/sandbox/Dockerfile.test.gotip
- example/service/s3/sync/sync.go
Updates the SDK's Travis CI tests to include Go 1.12.
> Update Travis CI tests for Go 1.12

- aws/credentials/stscreds/assume_role_provider.go
This is to make it possible to redirect/pipe output when using StdinTokenProvider and still seeing the prompt text
> aws/credentials/stscreds: Update StdinTokenProvider to prompt on stderr

- service/cloudfront/sign/policy.go
- service/cloudfront/sign/policy_test.go
Added `UnmarshalJSON` for `AWSEpochTime`.
I wanted to use `sign.Policy` for testing purposes, to validate generated policy. But AWSEpochTime is not unmarshaled correctly.
> Add json unmarshal for AWSEpochTime

- aws/awsutil/equal.go
Found a small typo on line 18. Changed 'the' to 'they'.
> aws/utils: Fix typo in DeepEqual

- Makefile
Updates the SDK's Makefile's test commands to use `go test` without a build cache by setting the `-count=1` flag.
> Update makes tests to not use build cache

- example/service/dynamodb/transactWriteItems/README.md
- example/service/dynamodb/transactWriteItems/error_handler.go
- example/service/dynamodb/transactWriteItems/error_handler_test.go
- TransactWriteItems can throw a TransactionCancelledExcption if one or more
writes on the items in the request fails because of user errors. In this
scenario, DynamoDB throws a TransactionCanclledException with a list of errors
for each item that caused the request to fail.
- Go SDK does not parse this list from wire and propagate up to the user. This
commit introduces a customer un-marshaller which can be attached to DynamoDB
client so that the error returned in case of TransactionCanclledException
contains list of item errors.
If there is an existing bug or feature this PR is answers please reference it …
> Introduces a custom un-marshaller example for TransactWriteItems response which is backwards compatibile

- aws/credentials/stscreds/assume_role_provider.go
This adds jitter to the `AssumeRoleProvider` which backs `stscreds.NewCredentials`. This helps to support large deployments.
> add jitter to AssumeRoleProvider

- example/aws/request/httptrace/README.md
- example/aws/request/httptrace/client.go
- example/aws/request/httptrace/config.go
- example/aws/request/httptrace/logger.go
- example/aws/request/httptrace/main.go
- example/aws/request/httptrace/trace.go
Adds an example how the Go standard library's `httptrace` package can be
used with the SDK to obtain request timing information on the individual
stages of a request.
> example/aws/request/httptrace: add example using httptrace with sdk

- aws/endpoints/dep_service_ids.go
I hate to make a PR for a one character fix but I was searching for the variable `EndpointID` in the docs and couldn't find it in s3 nor dynamodb. I was able to find the `EndpointsID` however in both:
[DynamodDB](https://github.com/aws/aws-sdk-go/blob/master/service/dynamodb/service.go#L35)
[S3](https://github.com/aws/aws-sdk-go/blob/master/service/s3/service.go#L33)
[EC2](https://github.com/aws/aws-sdk-go/blob/master/service/ec2/service.go#L33)
(feel free to close this and change yourself)
> Update to reference correct variable

- private/model/api/customization_passes.go
- private/model/api/shape.go
- private/protocol/rest/build.go
- service/s3/api.go
- service/s3/customizations.go
- service/s3/s3manager/upload_input.go
- service/s3/sse.go
- service/s3/sse_test.go
Fixes the S3 client's SSSECustomerKey and CopySourceSSECustomerKey API
input parameter's with leading or trailing whitespace being trimmed from
the parameter's value before sent. The parameters are modeled as strings
when they should be base64 encoded.
Fix #2604
> service/s3: Fix SSE Customer Key value whitespace trimming

- private/model/api/examples_builder.go
- private/model/api/s3manger_input.go
- private/model/cli/gen-api/main.go
Fixes minor SDK code generation import path logic to use helpers instead of explicit modification of import map.
> private/model/api: Fix minor SDK code gen import path logic

- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_test.go
> service/s3/s3manager: Fix uploader to check for empty part before max parts check

- service/dynamodb/expression/examples_test.go
Fixes the ExampleBuilder_WithKeyCondition example to include the
ExpressionAttributeNames member being set.
Related to aws/aws-sdk-go-v2#285
> service/dynamodb/expression: Fix Builder with KeyCondition example

- aws/request/request.go
All retriable-related fields and methods are using `retryable` term except in one comment.
> Fix "retriable" to "retryable" for the term consistency

- aws/types.go
- example/service/mediastoredata/streamingNonSeekableReader/README.md
- example/service/mediastoredata/streamingNonSeekableReader/main.go
- private/model/api/customization_passes.go
- private/model/api/load.go
- private/model/api/operation.go
- private/model/api/passes.go
- service/lexruntimeservice/api.go
- service/mediastoredata/api.go
Updates the SDK's documentation to clearify how you can use the SDK's
`aws.ReadSeekCloser` utility function to wrap an io.Reader to be used
with an API operation that allows streaming unsigned payload in the
operation's request.
Adds example using ReadSeekCloser with AWS Elemental MediaStore Data's
PutObject API operation.
> service/mediastoredata: Add support for nonseekable io.Reader

- Makefile
Suppress changes to the Go module definition files during CI
code generation validation testing. This change prevents validation
errors failing CI tests due to changes to the go.mod and go.sum files
being automatically updated during CI testing.
Fixup for [failing Travis CI tests](https://travis-ci.org/aws/aws-sdk-go/builds/538336526?utm_source=github_status&utm_medium=notification) with Go tip
> Update CI validation testing for Go module files

- internal/ini/ini_parser.go
Updates the INI parser's error message to not include unformatted string
struct values that are difficult to read, and do not provide meaningful
information.
> internal/ini: Update INI parser's error message.

- service/rds/customizations.go
- service/rds/customizations_test.go
Fixes the RDS API client's customization to not generate a presigned URL for same region calls for `CreateDBInstanceReadReplica` and `CopyDBSnapshot`.
Update of #1847
> aws/service/rds: Don't auto-sign (preSignUrl) for same region operations

- service/s3/s3crypto/kms_key_handler.go
The `KMSWrap` constant is part of the `s3crypto` package and therefore should be referenced as `s3crypto.KMSWrap` externally.
> service/s3/s3cyrpto: Fix NewKMSWrapEntry example documentation

- service/s3/s3manager/batch.go
Just some typos in the documentation comments
> fixing some typos in the docs

- aws/credentials/credentials.go
- aws/credentials/stscreds/assume_role_provider.go
- aws/request/handlers.go
- aws/session/credentials.go
- aws/session/credentials_test.go
- aws/session/session.go
- aws/session/session_test.go
- aws/session/shared_config.go
- aws/session/shared_config_test.go
- aws/session/shared_test.go
- aws/session/testdata/credential_source_config
- aws/session/testdata/shared_config
We have a scenario where our the first access will assume one cross account role and after it assume roles for each operation
We tried with the aws cli and everything works fine, but we have some operations that will use the go-sdk (aws-iam-authenticator)
Our conf will be something like:
```
[profile CIRole]
region = eu-central-1
role_arn = CIRole
credential_source = Ec2InstanceMetadata
external_id = external_id
[profile EKSRole]
region = eu-central-1
role_arn = EKSRole
source_profile = CIRole
```
using the aws cli it works as expected
```
export AWS_PROFILE=EKSRole
aws sts get-caller-identity
{
"Account": "...", 
"UserId": "...", 
"Arn": "...EKSRole/botocore-session-..."
}
```
But when we trigger the `aws-iam-authenticator`
```
export AWS_PROFILE=EKSRole
aws-iam-authenticator token -i …
```
> aws/session: Add support for chaining source_profile with credential_source

- service/s3/s3manager/s3manageriface/interface.go
This addresses #2273 and adds some new methods on top of it:
- `NewDownloader`
- `NewDownloaderWithClient`
- `NewUploader`
- `NewUploaderWithClient`
that were missing in the interface before.
It was suggested in #2273 that since this interface was not autogenerated and had no warning, the methods should be added as separate interfaces that can be composed together by the user to avoid breaking when the API changes.
> Update s3manager's iface with missing methods

- aws/request/connection_reset_error.go
- aws/request/connection_reset_error_test.go
- aws/request/http_request_retry_test.go
- aws/request/request.go
- aws/request/request_test.go
- service/s3/s3manager/upload_test.go
Adds a new unit test to S3 Upload Manager to verify the SDK will
correctly retry concurrent multipart uploads.
Related to #2525
> service/s3/s3manager: Add unit test for S3 Upload manager part retries

- aws/session/credentials.go
- aws/session/credentials_test.go
- aws/session/session.go
Provides an option to set role token duration in the AssumeRoleProvider
when using MFA. Without this it's difficult to change the token duration
from its default of 15 minutes while also using shared config.
Fix #2532.
Update merge conflict in #2554
> aws/session: Add option to set AssumeRole duration with NewSessionWithOptions

- example/aws/proxyWithTLSClientCert/README.md
- example/aws/proxyWithTLSClientCert/main.go
Adds an example for using the SDK with an HTTPS_PROXY that requires the
client include a TLS certificate to the HTTPS proxy.
> example/aws/proxyWithTLSClientCert: Add HTTPS_PROXY client cert example

- aws/csm/address_test.go
- aws/csm/doc.go
- aws/csm/enable.go
- aws/csm/reporter.go
- aws/session/env_config.go
- aws/session/session.go
Adds support for a host to be configured for the SDK's metric reporting
Client Side Metrics (CSM) client via the `AWS_CSM_HOST` environment
variable.
> aws/csm: Add support for AWS_CSM_HOST env option

- README.md
Fixes the SDK's README example not compiling due to `cancelFn` not begin compared against nil.
> Fix README example not compiling

- CHANGELOG_PENDING.md
- aws/session/credentials.go
- aws/session/session_test.go
Fixes the SDK's behavior when determining the source of credentials to
load. Previously the SDK would ignore the AWS_PROFILE environment, if
static environment credentials were also specified.
If both AWS_PROFILE and static environment credentials are defined, the
SDK will load any credentials from the shared config/credentials file
for the AWS_PROFILE first. Only if there are no credentials defined in
the shared config/credentials file will the SDK use the static
environment credentials instead.
>  aws/session: Fix SDK AWS_PROFILE and static environment credential behavior

- aws/client/logger.go
- aws/request/offset_reader.go
- aws/request/offset_reader_test.go
- aws/request/request.go
- aws/request/request_1_8.go
- aws/request/request_retry_test.go
- aws/request/request_test.go
- aws/signer/v4/v4.go
- example/service/s3/loggingUploadObjectReadBehavior/README.md
- example/service/s3/loggingUploadObjectReadBehavior/main.go
- service/s3/s3manager/upload.go
Fixes the SDK handling of seeking a reader to ensure errors are not
lost, and are bubbled up.
In several places the SDK ignored Seek errors when attempting to
determine a reader's length, or rewinding the reader for retry attempts.
Related to #2525
>  aws/request: Fix SDK error checking when seeking readers

- aws/awserr/types.go
- aws/awsutil/path_value.go
- aws/corehandlers/handlers_test.go
- aws/csm/reporter.go
- aws/request/request_pagination.go
- aws/request/request_pagination_test.go
- aws/request/request_test.go
- Remove unnecessary returns
- Turn for range loop into a simple append call
- Don't specify capacity if it's the default value of 0
- Simpler bool conditionals
> Simplify code

- aws/corehandlers/handlers_1_10_test.go
- aws/credentials/chain_provider_test.go
- aws/endpoints/endpoints_test.go
- aws/signer/v4/v4_test.go
Should it be intentional that those errors aren't checked, we should skip the
assignment altogether. No harm in those checks, though.
> Fixed ineffectual assignments / missing error handling

- awstesting/util.go
- The utilities StashEnv and PopEnv are moved to an internal package named sdktesting, and thus are deprecated from the awstesting package.
> Deprecated awstesting utilities: StashEnv and PopEnv

- CHANGELOG_PENDING.md
- aws/endpoints/endpoints.go
- aws/endpoints/endpoints_test.go
- aws/endpoints/v3model.go
> aws/endpoints: Expose DNSSuffix for partitions

- CHANGELOG_PENDING.md
- aws/session/credentials.go
- aws/session/credentials_test.go
- aws/session/doc.go
- aws/session/session.go
- aws/session/session_test.go
Fixes the credential loading order for environment credentials, when the
presence of an AWS_PROFILE value is also provided. The environment
credentials have precedence over the AWS_PROFILE.
If you want the profile to have precedence over the environment
credentials, (e.g when using credential_source=Environment) specify the
Profile option value when initializing the Session.
sess, err := session.NewSessionWithOptions(session.Options{
Profile: "myProfile",
})
Specifying the Options.Profile value is equivalent to the AWS CLI's
--profile flag.
Fix #2727
> aws/session: Fix credential loading order for env and shared config

- CHANGELOG_PENDING.md
- private/model/api/docstring.go
- service/kafka/api.go
Fixes the SDK's generated API documentation for structure member being
generated with the wrong documentation value when the member was
included multiple times in the model doc-2.json file, but under
different types.
The SDK was not considering the member's type when associating documetation
with the member. Only parent struct name and member names was being
used.
> private/model/api: Fix API doc being generated with wrong value

- aws/config.go
Fix typo of field names in the document.
> aws: Fix Config example field names in the document

- aws/client/default_retryer.go
- aws/client/default_retryer_test.go
- aws/corehandlers/handlers.go
- aws/request/http_request_retry_test.go
- aws/request/request.go
- aws/request/request_retry_test.go
- aws/request/request_test.go
- aws/request/retryer.go
Reorganizes the SDK's retry utilities to follow a consistent code path.
Request.IsErrorRetryable is the primary entry pointer for determining if
a request error should be retryable instead of split between
Request.Send and DefaultRetryer calling IsErrorRetryable. This also
gives the implementation of the Retryer interface consistent control
over when a request will be retried.
Also adds support for request and service specific API error retry and
throttling to be enabled by specifying API error codes before a request
is sent. The "RetryErrorCodes" and "ThrottleErrorCodes" members were added to
request.Request struct. These are used by the Request's IsErrorRetryable
and IsErrorThrottle respectively to specify additional API error codes
that identify the failed request attempt as needing to …
> aws/request: Reorganize retry behavior to reduce separation

- service/s3/s3manager/download.go
Fixes a typo in the S3 Download Manager's NewDownloaderWithClient usage example
> service/s3/s3manager: Fix typo in downloader example

- CHANGELOG_PENDING.md
- service/kinesis/customizations.go
- service/kinesis/customizations_test.go
Adds support for retrying the Kinesis API error, `LimitExceededException`.
Fix #1376
> service/kinesis: Add support for retrying service specific API errors

- CHANGELOG_PENDING.md
- aws/credentials/stscreds/web_identity_provider.go
- aws/credentials/stscreds/web_identity_provider_test.go
- service/sts/customizations.go
- service/sts/customizations_test.go
Adds retries to specific STS API errors to the STS AssumeRoleWithWebIdentity credential provider, and STS API operations in general.
> aws/credentials/stscreds: Add STS and Assume Role specific retries

- aws/credentials/endpointcreds/provider.go
Updates the docstring for NewCredentialsClient to remove an incomplete sentence and to match  other credential providers.
> aws/credentials/endpointcreds: Update NewCredentialsClient docstring

- CHANGELOG_PENDING.md
- aws/request/retryer.go
- aws/request/retryer_test.go
Fixes #2773 where the IsErrorRetryable helper was incorrectly returning true for nil errors passed in. IsErrorRetryable will now correctly return false when the passed in error is nil like documented.
> aws/request: Fix IsErrorRetryable returning true for nil error

- CHANGELOG_PENDING.md
- service/dynamodb/expression/key_condition.go
- service/dynamodb/expression/key_condition_test.go
Improves the reporting of errors when an invalid key condition is constructed using the DynamoDB expression package.
> service/dynamodb/expression: Improved reporting of bad key conditions

- CHANGELOG_PENDING.md
- aws/ec2metadata/api.go
- aws/ec2metadata/api_test.go
Adds `MarketplaceProductCodes` to the EC2 Instance Metadata's Identity Document. The ec2metadata client will now retrieve these values if they are available.
Fixes #2781
> aws/ec2metadata: Add marketplaceProductCodes to EC2 Instance Identity Document

- CHANGELOG_PENDING.md
- aws/client/default_retryer.go
- aws/client/default_retryer_test.go
Updates logic for calculating the delay after which a request can be retried. Retry delay now includes the `Retry-After` duration specified in a request.
Fixes broken test for Throttle Retry cap. 
Fixes #2795 .
> aws/client: Updates logic for request retry delay calculation

- Makefile
Fixes [#2797](https://github.com/aws/aws-sdk-go/issues/2797) where the SDK's code generation CI validation test was ignoring code generation changes that occurred during the CI test run.
Also, ensures all SDK's packages and utilities build during CI tests.
> Fix SDK's CI test validating code generation is stable

- CHANGELOG_PENDING.md
- aws/credentials/processcreds/provider_test.go
- private/protocol/eventstream/decode_test.go
This change addresses the issue reported in https://github.com/aws/aws-sdk-go/issues/2813 which caused unit tests to fail when executed within a go module.
> Fix failing tests when executed from inside a module

- .travis.yml
Updates the SDK's Travis CI test matrix to include Go 1.13
> Add Go 1.13 to CI test matrix

- CHANGELOG_PENDING.md
- aws/convert_types.go
- aws/convert_types_test.go
This change adds value and pointer conversion utilities for the remaining set of basic types:
* uint, uint8, uint16, uint32 & uint64
* int8, int16, int32
* float32
It also adds tests for each of the new convert functions
> aws: Add value/pointer conversion functions for all basic number types

- CHANGELOG_PENDING.md
- awstesting/integration/integration.go
- awstesting/integration/performance/s3UploadManager/README.md
- awstesting/integration/performance/s3UploadManager/config.go
- awstesting/integration/performance/s3UploadManager/main.go
- awstesting/integration/performance/s3UploadManager/main_test.go
- awstesting/integration/performance/s3UploadManager/metric.go
- service/s3/s3manager/buffered_read_seeker.go
- service/s3/s3manager/buffered_read_seeker_test.go
- service/s3/s3manager/default_read_seeker_write_to.go
- service/s3/s3manager/default_read_seeker_write_to_windows.go
- service/s3/s3manager/exmaples_test.go
- service/s3/s3manager/read_seeker_write_to.go
- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_test.go
This change is to help address the performance of `s3manager.Uploader` in particular on Windows platforms. This PR defines a new BufferStrategy configuration option to the Upload manager which will allow users to define whether a `[]byte` buffer should be used when uploading each part. The reasoning for this new strategy definition, is due to the fact that each part wraps the provided`io.ReadSeeker` to Uploader in an `io.SectionReader` which is limited to read from a particular offset and number of bytes. On the Windows platform if the underlying `io.ReadSeeker` is an `*os.File` this will result in a large number of blocking events as `*os.File.ReadAt` uses an emulated pread syscall which requires a mutex lock on the file in order to satisfy the read request. Introducing a BufferStrategy, …
>  service/s3/s3manager: Add Upload Buffer Provider

- private/model/api/codegentest/models/jsonrpc/0000-00-00/api-2.json
- private/model/api/codegentest/service/rpcservice/api.go
- private/model/api/codegentest/service/rpcservice/cust_eventstream_tests.go
- private/model/api/codegentest/service/rpcservice/eventstream_test.go
- private/model/api/customization_passes.go
- private/model/api/eventstream.go
- private/model/api/load.go
- private/model/api/passes.go
Fixes the operation's Output type's event stream member name being squashed with a baked in `EventStream`. The name of the member now reflects the name given in the model.
Added customization for S3's SelectObjectContent operation to persist the incorrect naming for backwards compatibility.
> private/mode/api: Fix codegen of event stream member reference naming

- aws/request/handlers.go
- aws/session/session.go
Fixed a few doc comment typos I found.
> aws: Fix typo in Handlers doc comments

- aws/client/default_retryer.go
- aws/request/http_request_retry_test.go
- aws/request/retryer.go
Refactors where the HTTP response status code is resolved for whether the request is retryable.
> aws/request: Refactors the http status code handling by the retryer

- CHANGELOG_PENDING.md
- awstesting/discard.go
- awstesting/endless_reader.go
- awstesting/integration/performance/s3DownloadManager/README.md
- awstesting/integration/performance/s3DownloadManager/client.go
- awstesting/integration/performance/s3DownloadManager/config.go
- awstesting/integration/performance/s3DownloadManager/main.go
- awstesting/integration/performance/s3DownloadManager/main_test.go
- awstesting/integration/performance/s3DownloadManager/metric.go
- internal/sdkio/byte.go
- service/s3/s3manager/default_writer_read_from.go
- service/s3/s3manager/default_writer_read_from_windows.go
- service/s3/s3manager/download.go
- service/s3/s3manager/download_test.go
- service/s3/s3manager/writer_read_from.go
- service/s3/s3manager/writer_read_from_test.go
Implements a buffering strategy for the download S3 manager. This is similar to the upload strategy being reviewed as part of https://github.com/aws/aws-sdk-go/pull/2792
> service/s3/s3manager: Add DownloadStrategy for buffering downloaded parts

- CHANGELOG_PENDING.md
- models/protocol_tests/input/rest-xml.json
- private/model/api/api.go
- private/model/api/codegentest/service/restxmlservice/api.go
- private/model/api/load.go
- private/model/api/operation.go
- private/model/api/passes.go
- private/model/api/passes_test.go
- private/model/api/shape.go
- private/protocol/restxml/build_test.go
- private/protocol/restxml/unmarshal_test.go
- private/protocol/xml/xmlutil/sort.go
- private/protocol/xml/xmlutil/sort_test.go
- private/protocol/xml/xmlutil/xml_to_struct.go
- service/cloudfront/api.go
- service/route53/api.go
- service/s3/api.go
- service/s3/s3manager/upload_input.go
- service/s3control/api.go
* `private/protocol/xml/xmlutil`: Support for sorting xml attributes
* `models/protocol_tests/input`: Revert changes to rest-xml protocol tests for marshaling top-level shapes
* `private/model/api`: Write locationName for top-level shapes for rest-xml and ec2 protocols
* Regenerated Service, Protocol, and CodeGen Tests
Fixes: #2806
> private/model/api: Write locationName for top-level shapes for rest-xml and ec2 protocols

- Makefile
- aws/corehandlers/handlers_1_10_test.go
- aws/corehandlers/handlers_test.go
- aws/credentials/credentials_test.go
- aws/credentials/endpointcreds/provider_test.go
- aws/csm/reporter_test.go
- aws/ec2metadata/service_test.go
- aws/request/request_1_8_test.go
- aws/request/request_test.go
- aws/session/credentials_test.go
- aws/signer/v4/v4_test.go
- awstesting/unit/unit.go
- internal/sdkrand/read.go
- internal/sdkrand/read_1_5.go
- service/s3/customizations_test.go
- service/s3/s3crypto/kms_key_handler_test.go
- service/s3/s3manager/batch_1_7_test.go
- service/s3/s3manager/batch_test.go
- service/s3/s3manager/bucket_region_test.go
- service/s3/s3manager/download_test.go
- service/s3/s3manager/upload_test.go
- service/s3/statusok_error_test.go
- service/s3/unmarshal_error_test.go
Ensure HTTP servers are cleaned up during testing after no longer needed. This was creating excessive noise in testing stack traces due to the number of background goroutines active.
Also updated SDK's unit tests to use verbose logging, and have a timeline of 20s.
Related to https://github.com/aws/aws-sdk-go/issues/2840
> Ensuren SDK's testing HTTP server usage are cleaned up

- service/s3/s3manager/download.go
- service/s3/s3manager/upload.go
This change performs some oppurtunistic cleanup of the internal Uploader interfaces discovered while porting changes to the V2 SDK.
> service/s3/s3manager: Simplify Upload manager internal interfaces

- CHANGELOG_PENDING.md
- Makefile
- private/model/api/example_test.go
Fixes broken TestExampleGeneration test to correctly test code generation for example.
> private/model/api: Fixes broken test for code generation example

- Makefile
- private/model/api/example_test.go
The sdk needs to update the dependencies in brazil, before adding a dependency in github to avoid release failures. 
Removing the gocmp dependency for now.
> private/model/api: removed gocmp dependency

- CHANGELOG_PENDING.md
- service/s3/s3manager/upload.go
Fixes #2036 by allowing the reuse/sharing of the part buffer pools for same-sized PartSize upload requests.
> service/s3/s3manager: Move part buffer pool upwards to allow reuse.

- awstesting/integration/performance/s3DownloadManager/client.go
- awstesting/integration/performance/s3DownloadManager/config.go
- awstesting/integration/performance/s3DownloadManager/main.go
- awstesting/integration/performance/s3DownloadManager/main_test.go
- awstesting/integration/performance/s3DownloadManager/metric.go
Adds additional CLI options for configuring the benchmark behavior when using `go test`. In addition this adds some profiling options to the standalone binary command.
> awstesting/integration/performance/s3DownloadManager: CLI Configurable Benchmarking Options

- example/service/s3/loggingUploadObjectReadBehavior/main.go
Adds the example build tag to the loggingUploadObjectReadBehavior example to prevent the binary from being built by default.
> example/service/s3/loggingUploadObjectReadBehavior: Add example buid tag

- CHANGELOG_PENDING.md
- private/model/api/codegentest/service/restjsonservice/api.go
- private/model/api/codegentest/service/restjsonservice/eventstream_test.go
- private/model/api/codegentest/service/restxmlservice/api.go
- private/model/api/codegentest/service/restxmlservice/eventstream_test.go
- private/model/api/codegentest/service/rpcservice/api.go
- private/model/api/codegentest/service/rpcservice/eventstream_test.go
- private/model/api/eventstream.go
- service/kinesis/api.go
- service/kinesis/eventstream_test.go
- service/s3/api.go
- service/s3/cust_integ_eventstream_test.go
- service/s3/cust_integ_shared_test.go
- service/s3/eventstream_test.go
Fixes calling the Err method on SDK's Amazon Kinesis's SubscribeToShared and Amazon S3's SelectObjectContent response EventStream members closing the stream. This would cause unexpected read errors, or early termination of the streams. Only the Close method of the streaming members will close the streams.
Improved generated unit and integration tests for streaming API operations.
Related to #2769
> Fix streaming APIs' Err method closing stream

- example/service/s3/concatObjects/README.md
- example/service/s3/listObjectsConcurrently/README.md
Some very minor typo fixes within the `example/service/s3` README files
> example/service/s3: Fix typo in example documentation

- example/service/s3/presignURL/client/client.go
Problem: Example for PutObjectPresigned should display error messages with 'PUT' instead of 'GET'.
Solution: This PR fixes the error messages replacing 'get'/'GET' with 'put'/'PUT' when applicable.
>  example/service/s3/presignUR: Example error message should be 'PUT' not GET'

- aws/csm/reporter.go
Removes `AttemptCount` from the `APICallAttempt` metric. This field is only valid for `APICall`
> aws/csm: Remove AttemptCount from APICallAttempt

- CHANGELOG_PENDING.md
- aws/endpoints/sts_legacy_regions.go
- aws/endpoints/v3model.go
- aws/endpoints/v3model_test.go
- aws/session/session.go
- aws/session/session_test.go
Fixes the SDK's behavior when attempting to resolve a service's endpoint when no region was provided. Adds legacy support for services that were able to resolve a valid endpoint. No new service will support resolving an endpoint without an region.
Fixes #2909
> aws/endpoints: Fix resolve endpoint with empty region

- aws/endpoints/v3model_test.go
`TestEndpointFor_EmptyRegion` breaks due to an unknown service called by the test. The fix runs this test only for aws partitions, and skips others.
> aws/endpoints: Fix testing bug in partitions other than `aws`.

- CHANGELOG_PENDING.md
- aws/request/request.go
- aws/request/retryer.go
- aws/request/retryer_test.go
Adds additional default behavior to the SDK's New request constructor,
to handle the case where a nil Retryer was passed in. This error could
occur when the SDK's Request type was being used to create requests
directly, not through one of the SDK's client.
Fixes #2889
> aws/request: Ensure New request handles nil retryer

- CHANGELOG_PENDING.md
- aws/awsutil/path_value.go
- awsmigrate/awsmigrate-renamer/gen/gen.go
- models/protocol_tests/generate.go
- private/model/api/param_filler.go
Advantages -
1. Efficient and more optimal in all cases, refer [https://www.digitalocean.com/community/questions/how-to-efficiently-compare-strings-in-go](url) for benchmarks.
2. More readable code.
3. Still uses the standard library.
> Using strings.EqualFold() for efficient string comparison

- aws/session/credentials.go
The code checks for AWS_ROLE_ARN:
aws/session/env_config.go:		"AWS_ROLE_ARN",
> aws/session: Documentation of AWS_IAM_ROLE_ARN should be AWS_ROLE_ARN (#2945)

- service/dynamodb/expression/condition.go
The `Contains` examples should be using a `string` instead of a `ValueBuilder`, as this what `Contains` expect.
> service/dynamodb/expression: Fix Contains doc examples

- Makefile
- awstesting/sandbox/Dockerfile.golang-tip
- awstesting/sandbox/Dockerfile.test.go1.10
- awstesting/sandbox/Dockerfile.test.go1.12
- awstesting/sandbox/Dockerfile.test.go1.13
- awstesting/sandbox/Dockerfile.test.go1.5
- awstesting/sandbox/Dockerfile.test.go1.5-novendorexp
- awstesting/sandbox/Dockerfile.test.go1.6
- awstesting/sandbox/Dockerfile.test.go1.7
- awstesting/sandbox/Dockerfile.test.go1.8
- awstesting/sandbox/Dockerfile.test.go1.9
- awstesting/sandbox/Dockerfile.test.gotip
Adds a go 1.13 docker sandbox file, updates gotip to use Debian Buster, and removes unnecessary Ubuntu image usage declarations.
> Add go1.13 Docker Sandbox, Update gotip sandbox, and remove Ubuntu usage

- CHANGELOG_PENDING.md
- aws/credentials/ec2rolecreds/ec2_role_provider_test.go
- aws/ec2metadata/api.go
- aws/ec2metadata/api_test.go
- aws/ec2metadata/service.go
- aws/ec2metadata/service_test.go
- aws/ec2metadata/token_provider.go
`aws/ec2metadata`: Adds support for EC2Metadata client to use secure tokens provided by the IMDS. Modifies and adds tests to verify the behavior of the EC2Metadata client.
> aws/ec2metadata: Add support for EC2Metadata client secure token

- aws/ec2metadata/api.go
- aws/ec2metadata/api_test.go
- aws/ec2metadata/service_test.go
SDK's ec2metadata client now uses dynamic data from instance identity document, to retrieve region info.
> aws/ec2metadata: fix ec2metadata client to retrieve region from dynamic data

- CHANGELOG_PENDING.md
- aws/credentials/processcreds/provider.go
Increase the default maximum buffer size used by the process credential provider.
Fixes: https://github.com/aws/aws-sdk-go/issues/2875
> aws/credentials/processcreds: Increase the default max buffer size

- aws/arn/arn.go
- aws/arn/arn_test.go
- service/s3/cust_integ_shared_test.go
- service/s3/endpoint_test.go
Fixes the SDK's handling of S3 Accesspoint ARNs to correctly parse ARNs with slashes in the resource component as valid. Previously the SDK's ARN parsing incorrectly identify ARN resources with slash delimiters as invalid ARNs.
> service/s3: Fix SDK support for Accesspoint ARNs with slash in resource

- private/model/api/passes.go
SDK has a customization for correcting incorrectly modeled endpoint prefix for `Application Auto-Scaling` service. The service has corrected the endpoint prefix in [Release v1.25.42](https://github.com/aws/aws-sdk-go/compare/v1.25.40...v1.25.41#diff-1f6436c45fb6acc4d0b4e66a583fb1f5R5). This PR removes the no longer needed customization.
> private/model: removes customization for application-autoscaling endpoint prefix

- CHANGELOG.md
Adds changelog entry highlighting a resource leak was fixed in PR #2960 .
> aws/ec2metadata : Adds changelog entry highlighting a resource leak was fixed 

- private/model/api/api.go
- private/model/api/operation.go
- private/model/api/shape.go
Modifies GetCrossLinks to lookup whether a service has has cross links by using the go PackageName rather then deriving the ServiceId from the metadata UID.
> private/model/api: Use PackageName when using HasCrossLinks

- CHANGELOG_PENDING.md
- aws/credentials/stscreds/assume_role_provider.go
- aws/credentials/stscreds/assume_role_provider_test.go
This is a small PR to add support for [session tags](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html) to the `AssumeRoleProvider`. This feature is important to enable  modelling Attribute Based Access Control (ABAC) on top of AWS IAM Policies, User and Roles.
> Add support for session tags to AssumeRoleProvider

- private/protocol/eventstream/debug.go
- private/protocol/eventstream/encode.go
- private/protocol/eventstream/eventstreamapi/reader.go
- private/protocol/eventstream/eventstreamapi/reader_test.go
- private/protocol/eventstream/eventstreamapi/shared.go
- private/protocol/eventstream/eventstreamapi/writer.go
- private/protocol/eventstream/eventstreamapi/writer_test.go
- private/protocol/eventstream/eventstreamtest/testing.go
- private/protocol/payload.go
Adds an EventWriter to the eventstreamapi package. This type provides the glue between a generate API event stream Event type being marshaled into a event stream Message, and written to the event stream Encoder.
Adds support for logging to evenstream.Encoder.
> private/protocol/eventstream: Add support for EventWriter

- CHANGELOG_PENDING.md
- aws/request/retryer.go
- aws/request/retryer_test.go
It is returned by SNS, XRAY, and ResourceGroupTagging API endpoints
https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_TagResources.html#API_TagResources_Errors
Can also be found in the JSON API spec in this repo
> Add "ThrottledException" for Retry

- aws/signer/v4/stream.go
- aws/signer/v4/stream_test.go
- aws/signer/v4/v4.go
- private/protocol/eventstream/encode.go
- private/protocol/eventstream/eventstreamapi/signer.go
- private/protocol/eventstream/eventstreamapi/signer_test.go
- private/protocol/eventstream/message.go
Implements the SigV4 signing strategy for Event Streams.
> Event Stream SigV4 Chunk Signinging

- aws/endpoints/endpoints.go
hint all map initialization that has fixed length
tried benchmark the before and after changes on defaultPartitions 
Before
`BenchmarkEnumDefaultRegions-8   	  318379	      3599 ns/op	    3973 B/op	       5 allocs/op
`
After
`BenchmarkEnumDefaultRegions-8   	  508568	      2208 ns/op	    2341 B/op	       3 allocs/op
`
> aws/endpoints: Initialize Map Sizes

- CHANGELOG_PENDING.md
- aws/request/retryer.go
- aws/request/retryer_test.go
- service/s3/s3manager/download_test.go
`shouldRetryError` should be using the `var shouldRetry` defined in outer scope and not declare another.
> Fix shouldRetry behavior for nested errors

- aws/request/request.go
- private/model/api/codegentest/service/restjsonservice/api.go
- private/model/api/codegentest/service/restxmlservice/api.go
- private/model/api/codegentest/service/rpcservice/api.go
- private/model/api/eventstream_tmpl.go
- private/model/api/eventstream_tmpl_reader.go
- private/model/api/operation.go
- private/model/api/shape.go
- service/kinesis/api.go
- service/s3/api.go
- service/transcribestreamingservice/api.go
Fixes a deadlock in the event stream writer, if the connection is closed but the application is not reading from the stream, and does not close the stream.
> Fix deadlock if event reader closed and app is not reading events

- private/protocol/eventstream/eventstreamapi/stream_writer.go
Fixes race condition in stream writer's close of underlying encoder. Ensures that close of stream writer's encoder happens in same goroutine as other event writes.
> Fix race condition in stream writer close

- aws/corehandlers/handlers.go
- aws/csm/reporter.go
- aws/csm/reporter_test.go
- aws/ec2metadata/api_test.go
- aws/ec2metadata/token_provider.go
- aws/request/request.go
- aws/request/retryer.go
- aws/request/retryer_test.go
Adds a const, `ErrCodeRequestError` for the `RequestError` status code that is used in several places in the SDK's request. Cleans up the SDK's usage of this error to use the constant instead of literal string.
> aws/request: Add const for RequestError error code

- CHANGELOG_PENDING.md
- aws/session/session.go
- aws/session/session_test.go
Fixes the SDK API clients not surfacing endpoint resolution errors, when the EndpointResolver is unable to resolve an endpoint for the client and region.
> aws/session: Fix client init not exposing endpoint resolve error

- CHANGELOG_PENDING.md
- aws/ec2metadata/api_test.go
- aws/ec2metadata/service.go
- aws/ec2metadata/service_test.go
The PR address the issues related to EC2Metadata client having long timeouts in case of failure in obtaining EC2Metadata token, while making a request to IMDS.
The PR reduces the timeout to 1 sec, and number of max retries to 2 for the EC2Metadata client. This would help reduce the long timeouts faced by the customers.
Fixes #2972
> `aws/ec2metadata`: Reduces timeout and number of max retries for EC2Metadata client

- CHANGELOG_PENDING.md
- service/s3/internal/s3testing/s3testing.go
- service/s3/s3manager/download_test.go
- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_internal_test.go
- service/s3/s3manager/upload_test.go
* Fixes resource leak if CreateMultipartUpload call fails which would result in the first `[]byte` never being returned to the `sync.Pool`
* Adds unit-test which fails defined S3 APIs to ensure that parts are correctly returned to the pool.
* Fixes #3000
* Fixes #3035
> service/s3/s3manager: Fix resource leak on failed CreateMultipartUpload calls

- CHANGELOG_PENDING.md
- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/decode_test.go
- service/dynamodb/dynamodbattribute/encode.go
- service/dynamodb/dynamodbattribute/encode_test.go
- service/dynamodb/dynamodbattribute/field.go
- service/dynamodb/dynamodbattribute/field_test.go
- service/dynamodb/dynamodbattribute/fields_go1.9.go
- service/dynamodb/dynamodbattribute/fields_go_old.go
- service/dynamodb/dynamodbattribute/marshaler_test.go
Currently struct type information is recomputed on every call to `dynamodbattribute.Marshal` and `dynamodbattribute.Unmarshal`.  To avoid this repeated work, I've added a `sync.Map`-backed cache to the reflection pass so that struct type info is only computed once.  In addition to caching fields per type, I've also included an index for each type that maps field names to fields to avoid linear searches by name in the Decoder.  On the whole, this approach basically the same as what the stdlib's `encoding/json` [does to solve the same problem](https://github.com/golang/go/blob/25a14b19abd3b9e16f47c6249fda1998431ce5be/src/encoding/json/encode.go#L1379).
`dynamodbattribute.fieldsByIndex` has been refactored into two functions, `decoderFieldsByIndex` and `encoderFieldsByIndex`.  This approach …
> dynamodbattribute: cache struct type info, refactor fieldsByIndex

- private/model/api/load.go
- private/model/api/passes.go
- private/model/api/passes_test.go
- service/applicationdiscoveryservice/api.go
- service/ec2/api.go
- service/health/api.go
- service/iam/api.go
* Adds `validateShapeName` utility to validate that the shape names for structs and enums adhere to a defined format. 
* Fixes bug which allowed service package structs, enums to start with non alphabetic character 
* Adds unit tests to test the validateShapeName utility.
> `private/model`: Add shape name validation for structs and enums 

- CHANGELOG_PENDING.md
- service/s3/s3crypto/aes_gcm_content_cipher.go
- service/s3/s3crypto/cipher_builder.go
- service/s3/s3crypto/cipher_util.go
- service/s3/s3crypto/cipher_util_test.go
- service/s3/s3crypto/decryption_client.go
- service/s3/s3crypto/encryption_client.go
- service/s3/s3crypto/key_handler.go
- service/s3/s3crypto/kms_key_handler.go
The s3crypto package is not passing a context object down to the KMS client calls so panics were being emitted by the X-Ray SDK.
This replaces my original PR #2783 in which @jasdel pointed out I'd break backwards compatibility.
I've found a relatively simple method of passing the request to the KMS client by introducing an additional interface `CipherDataDecrypterWithContext` which the KMS key handler conforms to. The decryption client then checks if the decrypter is of this type and if so calls the alternative method exposed in this interface.
I've not attempted to implement this for the `PutObject` method on the encryption client as I just couldn't find a simple way of introducing new code without breaking backwards compatibility.
I've tested my changes successfully:
> service/s3/s3crypto: Added X-Ray support to s3crypto decryption client

- CHANGELOG_PENDING.md
- service/dynamodb/expression/operand.go
- service/dynamodb/expression/operand_test.go
Now you have no way to specify a dynamodb.AttributeValue as a parameter to `expression.BuildOperand` method.
If you do so, it will be treated as any other struct, and instead of just passing a value, it will Marshal it's inner struct (all the {...BOOL: true, NULL: true, ...} fields that are needed for inner implementation).
That is a problem when you (for **example**) have a struct that was already been Marshalled:
```go
package main
import (
"fmt"
"github.com/aws/aws-sdk-go/service/dynamodb"
"github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute"
"github.com/aws/aws-sdk-go/service/dynamodb/expression"
)
type T struct {
ID    uint64  `dynamodbav:"id"`
Code  string  `dynamodbav:"code"`
Total float32 `dynamodbav:"amount"`
}
func main() {
t := T{
ID:    1,
Code:  "code",
Total: 10.5, …
```
> service/dynamodb/expression: Allow AttributeValue as a value to BuildOperand.

- CHANGELOG_PENDING.md
- aws/request/retryer.go
- aws/request/retryer_test.go
Adds support for the EC2ThrottledException throttling exception code. The SDK will now treat this error code as throttling.
> aws/request: Add support for EC2 specific throttle exception code

- CHANGELOG_PENDING.md
- aws/corehandlers/handlers_test.go
- aws/request/request.go
- aws/request/request_test.go
- aws/request/timeout_read_closer_test.go
- service/s3/endpoint_test.go
`net/http.Request` `Host` member was only computed during initial request creation. For services such as `S3` where endpoint modifications occur for referencing buckets using host-style addressing, the `Host` field on the HTTP request was not getting updated to reflect changes to the `url.URL` `Host` field. This change moves the computation of the `Host` member during the send step, right before computing the signing signature.
* Fixes #3093
> aws/request: Fix bug where the host header would not reflect changes to the endpoint URL.

- CHANGELOG_PENDING.md
- Makefile
- aws/credentials/credentials.go
- aws/credentials/credentials_test.go
- internal/sync/singleflight/LICENSE
- internal/sync/singleflight/singleflight.go
- internal/sync/singleflight/singleflight_test.go
This fixes a bug in which a continually failing credentials provider will cause many goroutines to queue on the `*Credentials.m` mutex, eventually leading to memory exhaustion.
> Use singleflight to coalesce credentials Get() calls into a single Retrieve()

- aws/request/request.go
Adds a nil check on http.Request.URL which can occur in partially mocked http.Request structures.
> aws/request: Add nil check on http.Request.URL in getHost(...)

- CHANGELOG_PENDING.md
- aws/credentials/context_background_go1.5.go
- aws/credentials/context_background_go1.7.go
- aws/credentials/context_go1.5.go
- aws/credentials/context_go1.9.go
- aws/credentials/credentials.go
- aws/credentials/credentials_go1.7_test.go
- aws/signer/v4/request_context_go1.5.go
- aws/signer/v4/request_context_go1.7.go
- aws/signer/v4/v4.go
- internal/context/background_go1.5.go
- service/s3/s3manager/batch_1_7_test.go
Adds `GetWithContext` to `Credentials` that allows canceling getting the credentials if the context is canceled, or times out. This fixes an issue where API operations would ignore their provide context when waiting for credentials to refresh.
Related to #3127
>  aws/credentials: Add `GetWithContext` method to `Credentials`

- aws/request/request.go
- private/model/api/codegentest/service/awsendpointdiscoverytest/api.go
- private/model/api/codegentest/service/awsendpointdiscoverytest/endpoint_discovery_test.go
- private/model/api/operation.go
- service/dynamodb/api.go
- service/dynamodb/integ_cust_test.go
Fixes and endpoint discovery bug where the SDK would fail to use a discovered endpoint if the scheme was not specified. The SDK will now default to using the clients original endpoint scheme if the discovered endpoint did not include one.
> Support Discovered Endpoints that don't specify Scheme

- models/apis/dynamodb/2012-08-10/api-2.json
- models/apis/dynamodb/2012-08-10/docs-2.json
- service/dynamodb/api.go
Amazon DynamoDB enables you to restore your DynamoDB backup or table data across AWS Regions such that the restored table is created in a different AWS Region from where the source table or backup resides. You can do cross-region restores between AWS commercial Regions, AWS China Regions, and AWS GovCloud (US) Regions.
> service/dynamodb: Add feature update for Amazon DynamoDB

- CHANGELOG.md
Adds missing release notes for service/fsx to the changelog.
> `Changelog`: add missing release notes for service/fsx

- CHANGELOG_PENDING.md
- awstesting/integration/performance/s3UploadManager/main_test.go
- service/s3/s3manager/upload.go
- service/s3/s3manager/upload_internal_test.go
Fixes a resource leak if an UploadPart request failed, which could cause other routines to not call their cleanup function.
> service/s3/s3manager: Fix resource leak on UploadPart failures

- private/model/api/codegentest/service/awsendpointdiscoverytest/api.go
- private/model/api/codegentest/service/awsendpointdiscoverytest/endpoint_discovery_test.go
- private/model/api/operation.go
- service/dynamodb/api.go
Adds fix to make sure endpoint discovery is not performed when a custom endpoint is provided on operation.
Adds test cases to validate behavior in different scenarios including with operations that have required/optional endpoint discovery.  
Fixes #3180
> `service`: Fix for bug in SDKs endpoint discovery 

- CHANGELOG_PENDING.md
- aws/credentials/static_provider.go
Updating documentation for NewStaticCredentials to specify when the `token` parameter should be populated.
Fixes #3162
> Docs: Clarifying token usage in NewStaticCredentials

- aws/session/credentials.go
- aws/session/credentials_test.go
- aws/session/shared_config.go
- aws/session/testdata/shared_config
Adds support for the `duration_seconds` shared config option for assume role credential provider.
> aws/session: Support Shared Config Role Duration Config Option

- .travis.yml
Updates the SDK's travis tests to include Go 1.14
> Update travis tests for Go 1.14

- private/signer/v2/v2_test.go
Fixes the following gotip vetting failure:
```
private/signer/v2/v2_test.go:34:36: conversion from int to string yields a string of one rune
Makefile:200: recipe for target 'vet' failed
make: *** [vet] Error 2
```
> Fixes gotip vet failure

- service/s3/s3manager/upload.go
Fixes an issue uncovered while doing some testing with X-Ray SDK and the S3 Upload Manager. This ensures that we set the context when generating a presign URL after finishing an upload.
> service/s3/s3manager: Add Context to S3 URL presigning

- CHANGELOG_PENDING.md
- aws/credentials/credentials.go
- aws/credentials/ec2rolecreds/ec2_role_provider.go
- aws/credentials/endpointcreds/provider.go
- aws/credentials/stscreds/assume_role_provider.go
- aws/credentials/stscreds/assume_role_provider_test.go
- aws/credentials/stscreds/web_identity_provider.go
- aws/ec2metadata/api.go
- aws/ec2metadata/token_provider.go
To support features like X-Ray tracing, allow for tracing a credential provides credential retrieval to remote services by suppressing the cancellation of the context.
Fixes https://github.com/aws/aws-sdk-go/issues/3213
> aws/credentials: Add ProviderWithContext optional interface to support passing contexts on credential retrieval

- CHANGELOG_PENDING.md
- aws/credentials/stscreds/web_identity_provider.go
This change makes it possible to fetch a token from an arbitrary source, rather than the file system (Ex: Fetch from an HTTP service)
```go
type FetchTokenFromMoon struct {}
func (v FetchTokenFromMoon) FetchToken(ctx credentials.Context) ([]byte, error) {
return /* do something cool */
}
```
> aws/credentials/stscreds: Added TokenFetcher

- CHANGELOG_PENDING.md
- aws/credentials/stscreds/assume_role_provider.go
- aws/credentials/stscreds/web_identity_provider.go
To support passing `PolicyArns` to `stscreds.AssumeRoleProvider` in the same manner as `sts.AssumeRole`.
Resolves #3233
> Add PolicyArns to stscreds.AssumeRoleProvider

- CHANGELOG_PENDING.md
- service/s3/s3manager/upload_internal_test.go
- service/s3/s3manager/upload_test.go
- service/s3/statusok_error.go
- service/s3/statusok_error_test.go
- service/s3/unmarshal_error.go
* In case of an internal error/ terminated connection, S3 operations supporting 200 errors i.e. CopyObject, UploadPartCopy, CompleteMultiPartUpload may return empty payload or payload with only xml Preamble. This is currently ignored by the SDK, and SDK returns 200 success with no response payload as a result. 
* S3 will always send a response payload in case of 200 error supporting operations. If not, client should handle internal errors/ terminated connections as retryable errors.
Rev 1
---
* Updates the S3 unmarshal xml error logic to handle empty or xml preamble only reponse payloads for operations support 200 response errors. 
* Adds and updates existing tests that use CopyObject, uploadPartCopy, or CompleteMultiPartUpload.
> `service/s3`: fix behavior for 200 OK responses with no body

- private/protocol/timestamp_test.go
Adds a unit test to verify the SDK's behavior parsing fractional second epoch values with exponents.
> private/protocol: Add unit tests for exponent Unix epoch seconds parsing

- CHANGELOG_PENDING.md
- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/decode_test.go
- service/dynamodb/dynamodbattribute/shared_test.go
Simplifies the logic in `dynamodbattribute` to decode AttributeValue as it is defined.
> service/dynamodb/dynamodbattribute: Decode AttributeValue types as defined

- aws/corehandlers/handlers_test.go
Fixes the refresh credentials request handler to correctly validate the SDK's behavior with regard to refreshing expired credentials. The old test was not doing a good job of testing the behavior correctly.
Related to #3229
> aws/corehandlers: Fix refresh credentials handler test

- CHANGELOG_PENDING.md
- service/s3/s3crypto/encryption_client.go
This was causing a nil pointer dereference runtime error instead of returning the error.
I was tearing my hair out trying to understand my SIGSEGV error, and in the end it turned out to be a silly `MissingRegion` problem.
> service/s3/s3crypto: Add missing return in encryption client

- aws/types.go
- private/checksum/content_md5.go
- private/model/api/operation.go
- private/util/content_md5.go
- service/s3/api.go
- service/s3/body_hash.go
- service/s3/content_md5_test.go
- service/s3/customizations.go
- service/s3/customizations_test.go
* Adds support for `httpChecksumRequired` trait
* Adds expected model changes for testing
* Moves `contentMd5` handler func from `s3` to `private/utils`
* Removes customizations for specific operations requiring `Content-MD5` header
* Adds and modifies existing tests for service operations decorated by the trait.
> `private`: Adds support for `httpChecksumRequired` trait 

- CHANGELOG_PENDING.md
- aws/config.go
- private/model/api/codegentest/service/awsendpointdiscoverytest/api.go
- private/model/api/operation.go
- service/dynamodb/api.go
* Allow endpoint discovery when config region is set to an empty string 
* Updates documentation
> `private/model`: enable endpoint discovery when region is set to empty string

- CHANGELOG_PENDING.md
- private/protocol/timestamp.go
- private/protocol/timestamp_test.go
Supports decimal precision timestamps for UNIX epoch.
> Support decimal precision timestamps

- aws/endpoints/v3model.go
- aws/endpoints/v3model_test.go
Adds validation to the passed in region identifier before templating in the value.
> Add validation to region identifier before setting endpoint

- CHANGELOG_PENDING.md
- service/s3/s3crypto/envelope.go
- service/s3/s3crypto/envelope_test.go
Allows the tag length envelope member to be valid JSON numbers.
> service/s3/s3crypto: Allow envelope unmarshal to accept JSON numbers for tag length.

- service/s3/s3crypto/envelope.go
- service/s3/s3crypto/envelope_test.go
Allow the envelope content length key to be a JSON Number.
> service/s3/s3crypto: Allow content length JSON Number

- aws/config.go
The following PR changed the Endpoint behavior to include falling back to the default generated endpoint if an empty string is set. 
https://github.com/aws/aws-sdk-go/pull/3349
It's not very clear that this is the intended behavior when reading the docs. Adding this clarification promotes using the following code rather than have to conditionally check if it's set or not.
For example:
```go
type S3 struct {
Endpoint string
Region 	 string
}
// ideal behavior
sess, err := session.NewSession(&aws.Config{
Endpoint: aws.String(s3Cfg.Endpoint),
Region:   aws.String(s3Cfg.Region),
})
// required check given docs assumption
var endpoint *string
if s3Cfg.Endpoint != "" {
endpoint = aws.String(s3Cfg.Endpoint)
}
sess, err := session.NewSession(&aws.Config{
Endpoint: endpoint,
Region: …
```
> clarify Endpoint behavior on empty strings

- aws/config.go
I stumbled upon a typo in the example code of `EC2MetadataDisableTimeoutOverride`, and while at it, also fixed 2 more 
typos here.
> Fix documentation typos in aws/config

- CHANGELOG_PENDING.md
- aws/corehandlers/handlers.go
- service/s3/s3manager/bucket_region.go
- service/s3/s3manager/bucket_region_test.go
Updates the documentation for GetBucketRegion's behavior with regard to default configuration for path style addressing. Provides examples how to override this behavior.
Updates the GetBucketRegion utility to not require a region hint when the session or client was configured with a custom endpoint URL.
Related to https://github.com/aws/aws-sdk-go/issues/3115
> service/s3/s3manager: Clarify documentation and behavior of GetBucketRegion

- CHANGELOG_PENDING.md
- private/model/api/codegentest/service/restjsonservice/api.go
- private/model/api/codegentest/service/restjsonservice/eventstream_test.go
- private/model/api/codegentest/service/restxmlservice/api.go
- private/model/api/codegentest/service/restxmlservice/eventstream_test.go
- private/model/api/codegentest/service/rpcservice/api.go
- private/model/api/codegentest/service/rpcservice/eventstream_test.go
- private/model/api/eventstream.go
- private/model/api/eventstream_tmpl.go
- private/model/api/eventstream_tmpl_reader.go
- private/model/api/eventstream_tmpl_readertests.go
- private/protocol/eventstream/eventstreamapi/reader.go
- private/protocol/eventstream/header.go
- private/protocol/eventstream/message.go
- service/kinesis/api.go
- service/kinesis/eventstream_test.go
- service/s3/api.go
- service/s3/eventstream_test.go
- service/transcribestreamingservice/api.go
- service/transcribestreamingservice/eventstream_test.go
Adds failsafe handling for receiving unknown stream messages from an API. A `<streamName>UnknownEvent` type will encapsulate the unknown message received from the API. Where `<streamName>` is the name of the API's stream, (e.g. S3's `SelectObjectContentEventStreamUnknownEvent`).
>  codegen: Add failsafe handling for unknown stream messages

- CHANGELOG_PENDING.md
- service/s3/s3crypto/helper.go
- service/s3/s3crypto/helper_test.go
Closing and removing the temp file after send causes retry requests to
fail with an error such as:
```
filestore: SerializationError: failed to prepare body for retry
caused by: SerializationError: failed to reset request body
caused by: SerializationError: failed to get next request body reader
caused by: seek /tmp/213721967: file already closed
```
I believe the Complete handler is guaranteed to be called
after retries attempts have succeeded or been exhausted.
> service/s3/s3crypto Fix request retries

- CONTRIBUTING.md
- README.md
*Description of changes:*
Updating common files (readme, code of conduct, contributing) to standardize content & formatting across all AWS SDKs
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Updating common files

- private/model/api/api.go
- private/model/api/eventstream_tmpl_writertests.go
- service/transcribestreamingservice/eventstream_test.go
Fixes the code generation for eventstream APIs to correctly not generated required parameter validation, and fix test WriteEvents code generation.
> codegen: Fix eventstream require params and test generation

- CHANGELOG_PENDING.md
- service/dynamodb/dynamodbattribute/doc.go
Fixes typo in `dynamodbattribute` package docs.
> service/dynamodb/dynamodbattribute: Fix typo in package docs.

- CHANGELOG_PENDING.md
- private/model/api/codegentest/service/restjsonservice/api.go
- private/model/api/codegentest/service/restxmlservice/api.go
- private/model/api/codegentest/service/rpcservice/api.go
- private/model/api/eventstream_tmpl.go
- private/model/api/operation.go
- service/kinesis/api.go
- service/s3/api.go
- service/transcribestreamingservice/api.go
Fixes #3412 by exporting the operation's EventStream type's constructor function so it can be used to fully initialize fully when mocking out behavior for API operations with event streams.
> codegen: Export event stream constructor for easier mocking

- CHANGELOG_PENDING.md
- aws/request/connection_reset_error.go
- aws/request/connection_reset_error_test.go
- aws/request/request_test.go
Allows "use of closed network connection" errors to be retryable by the SDK.
Fixes #3406
> aws/request: Allows "use of closed network connection" errors to be retryable

- CHANGELOG_PENDING.md
- service/ec2/customizations.go
- service/ec2/customizations_test.go
Fixes #3374 by correcting the EC2 API client's customization for ModifyNetworkInterfaceAttribute and AssignPrivateIpAddresses operations to use the aws.Config.MaxRetries value if set. Previously the API client's customizations would ignore MaxRetries specified in the SDK's aws.Config.MaxRetries field.
> service/ec2: Fix max retries with client customizations

- CHANGELOG_PENDING.md
- private/protocol/timestamp.go
- private/protocol/timestamp_test.go
Allows the for parsing of decimal precision iso8601 time formats.
> Allow parsing of decimal precision iso8601 formats

- .github/workflows/stale_issues.yml
Issues can be excluded from the stale-issue-cleanup workflow by applying the `no-autoclose` label.
> Reducing ancient issue threshold to 1 year

- CHANGELOG_PENDING.md
- private/protocol/timestamp.go
- private/protocol/timestamp_test.go
Limits the iso8601 time format to milliseconds precision when serializing fractional seconds. This prevents issues seen with services like CloudWatch which don't support nanoseconds granular clock sources.
Fixes https://github.com/aws/aws-sdk-go/issues/3498
> Limit iso8601 fractional second precision to milliseconds

- CHANGELOG_PENDING.md
- aws/defaults/defaults_test.go
- aws/ec2metadata/api.go
- aws/ec2metadata/api_test.go
- aws/ec2metadata/service.go
- aws/ec2metadata/service_test.go
- aws/session/credentials_test.go
- aws/session/doc.go
- aws/session/env_config.go
- aws/session/env_config_test.go
- aws/session/session.go
- aws/session/session_test.go
Adds support for specifying a custom EC2 IMDS endpoint from the environment variable, `AWS_EC2_METADATA_SERVICE_ENDPOINT`.
```
AWS_EC2_METADATA_SERVICE_ENDPOINT=http://[::1]
```
The `aws/session#Options` struct also has a new field, `EC2IMDSEndpoint`. This field can be used to configure the custom endpoint of the EC2 IMDS client. The option only applies to EC2 IMDS clients created after the Session with EC2IMDSEndpoint is specified.
```go
sess, err := session.NewSessionWithOptions(session.Options{
EC2IMDSEndpoint: "http://[::1]",
})
```
> Add support for EC2 IMDS endpoint from environment variable

- service/kinesis/cust_integ_eventstream_test.go
- service/kinesis/cust_integ_shared_test.go
Adds t.skip() to temporarily disable kinesis test for release
> Temporarily disable kinesis test for release

- service/kinesis/cust_integ_eventstream_test.go
- service/kinesis/cust_integ_shared_test.go
Reverts test skipped as a part of https://github.com/aws/aws-sdk-go/pull/3529. 
Tested Integ test with our test account. The tests succeed.
> `service/kinesis`: Reverts temp test skipped for kinesis

- .travis.yml
- Makefile
- awstesting/sandbox/Dockerfile.test.go1.14
- awstesting/sandbox/Dockerfile.test.go1.15
Adds Go 1.15 to CI tests, and creates sandbox test environments for missing go versions.
> Update SDK CI and sandbox tests for Go 1.15

- CHANGELOG_PENDING.md
- service/s3/s3manager/pool.go
- service/s3/s3manager/pool_test.go
Problem:
S3 uploader could allocate more memory than it is actually needed.
Added unit test should showcase the problem
> service/s3/s3manager:  Prefer using allocated slices from pool over allocating new ones.

- CONTRIBUTING.md
- README.md
The anchor links on README.md and CONTRIBUTING.md were broken with underscores and returned 404 on GitHub's UI. This change fixes it.
> Fixing anchor links on README and CONTRIBUTING pages

- aws/credentials/credentials.go
- aws/ec2metadata/token_provider.go
Ensures that the monotonic clock readings are removed from times when used with the `credentials.Expiry` type.
> Clear monotonic clock when setting credential expiration values.

- CHANGELOG_PENDING.md
- private/model/api/endpoint_arn.go
- service/s3/api.go
- service/s3control/api.go
- service/s3control/customizations.go
- service/s3control/endpoint.go
- service/s3control/endpoint_test.go
- service/s3control/validate.go
* Updates customizations to mutate a copy of original input, so that manual retry's do not break.
* Adds test for s3control to verify the behavior
> fix original input being modified with s3control ARN operations

- CHANGELOG_PENDING.md
- private/model/api/customization_passes.go
- service/s3control/api.go
Reference: https://github.com/aws/aws-sdk-go/issues/3598
> service/s3control: Fix GetAccessPointPolicy, DeleteAccessPointPolicy, and PutAccessPointPolicy operations not routing properly for S3 on Outposts

- CHANGELOG_PENDING.md
- internal/ini/ini_parser.go
- internal/ini/ini_parser_test.go
Hello, 
This is a bugfix for the INI parser that fails to parse an INI file like:
```
[default]
region = us-west-2
s3 =
```
Notice the absence of the empty line at the end of the file. 
There was a previously closed bug addressing a similar issue - https://github.com/aws/aws-sdk-go/issues/2800, but the corner case when the right-hand value is missed in the last statement is still failing. 
In my case, it was critical (granted adding a newline at the end of the file also fixes it) as I had a `~/.aws/config` written as described in AWS Docs here: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html : 
```
[default]
cli_pager=
```
Please note, that in this case an `ASTKindSkipStatement` statement is not added in the resulting AST. If the desired behaviour would be to …
> Fixes ini file parsing for cases when Right Hand Value is missed in the last statement of the ini file

- private/model/api/passes.go
- private/model/api/passes_test.go
Updates the SDK's code generation to renames structures that collide with the service's API client struct name.
For example, service Foo, has struct shape named Foo. The API client type would be generated as Foo, and the colliding struct shape would be renamed to `Foo_`, with a trailing underscore(_).
> codegen: Ensure API structs don't collide with API client type name 

- CHANGELOG_PENDING.md
- aws/session/client_tls_cert_test.go
- aws/session/custom_transport.go
- aws/session/custom_transport_go1.12.go
- aws/session/custom_transport_go1.5.go
- aws/session/custom_transport_go1.6.go
- aws/session/doc.go
- aws/session/env_config.go
- aws/session/env_config_test.go
- aws/session/session.go
- aws/session/shared_config.go
- awstesting/client_tls_cert.go
Adds support for the SDK to automatically modify the HTTP client to include TLS configuration of custom Client TLS certificate. This configuration can be provide via the environment variable or directly in code via the `session.Options` struct.
These options are compatible with the AWS_CA_BUNDLE configuration.
Both `AWS_SDK_GO_CLIENT_TLS_CERT`, and `AWS_SDK_GO_CLIENT_TLS_KEY` must be provided together, and must point to valid PEM encoded file containing the certificate, and key respectively.
```
AWS_SDK_GO_CLIENT_TLS_CERT=$HOME/my_client_cert
AWS_SDK_GO_CLIENT_TLS_KEY=$HOME/my_client_key
```
Alternative configuration is to specify the `ClientTLSCert` and `ClientTLSKey` fields on the `session.Options` struction. These are `io.Reader`s that provide the PEM encoded content for the …
> aws/session: Add support for client TLS certs on HTTP client

- private/model/api/eventstream.go
- private/model/api/shape.go
Updates the SDK's code generation for event stream member event for
methods to be sorted order. Ensures load order doesn't impact code
generation output.
Fixes https://github.com/aws/aws-sdk-go/issues/3664
> codegen: Ensure event stream events are in sorted order

- aws/request/retryer_test.go
Adds additional retry expectation tests for SDK's handling of SerializationError being treated as a retryable/throttling error.
Related to #3649
> aws/request: Add additional retry tests for SerializationError

- private/model/api/codegentest/service/awsendpointdiscoverytest/api.go
- private/model/api/operation.go
- service/dynamodb/api.go
- service/timestreamquery/api.go
- service/timestreamwrite/api.go
Currently, the SDK calls endpoint discovery API such as `DescribeEndpoints()` with no `context.Context`.
This causes some problems such as:
- no cancellation propagation happens
- cannot adopt other context-aware tools such as aws-xray-sdk-go
Call `DescribeEndpointsWithContext` with endpoint discovery struct's context instead of `DescribeEndpoints()`
---
> Pass context to endpoint discovery requests

- private/model/api/codegentest/service/awsendpointdiscoverytest/api.go
- private/model/api/operation.go
- service/dynamodb/api.go
- service/timestreamquery/api.go
- service/timestreamwrite/api.go
Reverts aws/aws-sdk-go#3653
Upon additional investigation we determined that there might be some unattended behaviors with regards to requests being terminated by a context when attempting to discover an endpoint. Since endpoint discovery may happen out of band in a separate goroutine, essentially not blocking the original operation, it's lifetime shouldn't always be coupled to the same context timeout. There is likely a larger design change that would have to occur to make this possible.
> Revert "Pass context to endpoint discovery requests"

- CHANGELOG_PENDING.md
- aws/config.go
This commit is for adding missing `chaining` and `mergeInConfig` parameters.
- chain: LowerCaseHeaderMaps, DisableRestProtocolURICleaning
- mergeInConfig: LowerCaseHeaderMaps
> Add missing methods for Config type

- aws/credentials/ssocreds/doc.go
- aws/credentials/ssocreds/os.go
- aws/credentials/ssocreds/os_windows.go
- aws/credentials/ssocreds/provider.go
- aws/credentials/ssocreds/provider_test.go
- aws/credentials/ssocreds/testdata/00126f0eb29dc1310529dcc8fc178693e1493135.json
- aws/credentials/ssocreds/testdata/b5f90cb535abf87a12eb4c57db2b1e837e229ea0.json
- aws/credentials/ssocreds/testdata/f7f7ff326478d8c33d47eeb3408cf1c783cb611e.json
- aws/session/credentials.go
- aws/session/credentials_test.go
- aws/session/session.go
- aws/session/shared_config.go
- aws/session/shared_config_test.go
- aws/session/testdata/credential_source_config
- aws/session/testdata/shared_config
Adds support for the AWS Single Sign-On (SSO) service by supporting the ability to utilize tokens cached in ~/.aws/sso/cache.
Adds support for the AWS SSO provider in the default credential loading chain.
> AWS Single Sign-On (SSO) Provider Support

- CHANGELOG_PENDING.md
- service/lexmodelsv2/cust_integ_test.go
- service/lexmodelsv2/customizations.go
- service/lexmodelsv2/customizations_test.go
Fixes the Amazon Lex Model Builder V2 API client to send the expected Content-Type of application/x-amz-json-1.1.
> service/lexmodelsv2: Add fix to send expected Content-Type header

- CHANGELOG_PENDING.md
- aws/session/credentials.go
- aws/session/credentials_test.go
- aws/session/shared_config.go
- aws/session/shared_config_test.go
- aws/session/testdata/credential_source_config
Fixes a bug that prevented credentials from being sourced from the environment if the loaded shared config profile contained partial SSO configuration.
This change ensures that a profile's SSO configuration is only validated if the SSO provider were to be used.
Fixes: https://github.com/aws/aws-sdk-go/issues/3768
> Fix: Only Validate SSO profile configuration when attempting to use SSO credentials

- CHANGELOG_PENDING.md
- example/service/s3/usingPrivateLink/README.md
- example/service/s3/usingPrivateLink/usingPrivateLink.go
- private/model/api/customization_passes.go
- service/s3/endpoint.go
- service/s3/endpoint_builder.go
- service/s3/endpoint_test.go
- service/s3/service.go
- service/s3control/endpoint.go
- service/s3control/endpoint_builder.go
- service/s3control/endpoint_test.go
`service/s3`: Adds support for S3 vpc interface endpoint.
`service/s3control`: Adds support for S3control vpc interface endpoint.
> s3: adds support for s3 vpc interface endpoints

- CHANGELOG_PENDING.md
- aws/client/client.go
- aws/client/client_test.go
- aws/client/logger.go
- aws/client/logger_test.go
Allow logging of operation and request to be enabled per operation, not only per client or session.
```go
client := dynamodb.New(sess)
var w bytes.Buffer
resp, err := client.DescribeTableWithContext(context.TODO(), params,
func(r *request.Request) {
r.Config.LogLevel = aws.LogLevel(aws.LogDebugWithHTTPBody)
r.Config.Logger = aws.LoggerFunc(func(args ...interface{}) {
fmt.Fprintln(&w, args...)
})
})
if someCondition {
log.Printf("Condition met\n%s", w.String())
}
```
> aws/client: Fix logging to allow it to be enabled per operation

- CHANGELOG_PENDING.md
- private/model/api/customization_passes.go
- service/docdb/api.go
- service/docdb/customizations.go
- service/docdb/customizations_test.go
- service/neptune/api.go
- service/neptune/customizations.go
- service/neptune/customizations_test.go
Adds support for presigned URL generation for CopyDBClusterSnapshot and CreateDBCluster operations in Neptune and DocDB services.
> Presigned URL generation for Neptune and DocDB CopyDBClusterSnapshot & CreateDBCluster

- aws/credentials/stscreds/assume_role_provider.go
The original comment for `func StdinTokenProvider()` contained the sentence 
```
Use this function go read MFA tokens from stdin.
``` 
It should be `...to read...` instead of `...go read...`.
> Fix a tiny typo

- aws/config_test.go
Actualy, I wanna fix the `LowerCaseHeaderMaps` issue, its' an important config for the users who are using Metadata, related to #445. 
The `unmarshalHeaderMap` method always returns the canonical header key form, but before this PR #3671, the `LowerCaseHeaderMaps` config didn't work, so I tried to debug it and I found there's a bug in`mergeInConfig` method, now it has been fixed, so just add some tests.
> Add missing fields for config test.

- README.md
Travis is migrating its host from travis-ci.org to travis-ci.com. Updated the SDK's README build status link to reflect the new host.
> Update SDK build status link for travis-ci.com

- .travis.yml
- Makefile
- aws/credentials/credentials_bench_test.go
- awstesting/assert.go
- awstesting/sandbox/Dockerfile.test.go1.16
- internal/smithytesting/document.go
- internal/smithytesting/document_test.go
- internal/smithytesting/xml/doc.go
- internal/smithytesting/xml/sort.go
- internal/smithytesting/xml/sort_test.go
- internal/smithytesting/xml/xmlToStruct.go
- private/model/cli/gen-protocol-tests/main.go
- private/protocol/restxml/build_test.go
- private/util/util.go
- service/kinesis/cust_integ_eventstream_test.go
Fixes the SDK's handling of XML protocol tests to correctly compare two
XML document strings without mangling the XML namespace.
Fixes #3731
Fixes unit and vet for Go 1.16
>  private/protocol: Fix protocol unit test for Go 1.16.

- .travis.yml
- CONTRIBUTING.md
- README.md
- example/service/dynamodb/unitTest/README.md
* Updates Travis jobs to refer to `main` as the target branch name.
* Updates documentation links to refer to `main`.
> Rename master branch to main

- CHANGELOG_PENDING.md
- service/lookoutmetrics/cust_integ_test.go
- service/lookoutmetrics/customizations.go
- service/lookoutmetrics/customizations_test.go
Fix SDK's serialization of request to include expected Content-Type header.
> service/lookoutmetrics: Fixes handling of API requests

- aws/session/credentials_test.go
Fixes SSO unit test to cleanup temporary directory.
> aws/session: Fix SSO unit test to cleanup tmp directory

- service/route53/customizations_test.go
Fixes the API client's customization unit test to be less specific about
the expected URL. This change prevents unit test failures if unrelated
API model updates occur.
> service/route53: Fix customization test being to specific

- CHANGELOG_PENDING.md
- private/protocol/xml/xmlutil/build.go
- private/protocol/xml/xmlutil/build_test.go
- private/protocol/xml/xmlutil/xml_to_struct.go
Updates XML encoding function to include line feed characters in escaping.
> private/protocol/xml/xmlutil: Updated XML encoding

- CHANGELOG_PENDING.md
- aws/session/credentials.go
- aws/session/credentials_test.go
- aws/session/shared_config.go
- aws/session/shared_config_test.go
- aws/session/testdata/credential_source_config
- aws/session/testdata/credential_source_config_for_windows
- aws/session/testdata/shared_config
- aws/session/testdata/wit.txt
Enables SSO credential provider configuration to be mixed with other credential providers. 
Fixes: #3763
> aws/session: Enable SSO provider to be mixed with other credential providers

- .github/workflows/go.yml
- .travis.yml
Updates the SDK's CI to use GitHub actions intead of Travis for most CI tasks. Travis is still used for Go tip.
> Add GitHub actions instead of Travis for Go CI tests

- CHANGELOG_PENDING.md
- aws/request/request.go
- aws/request/request_1_8_test.go
Fixes the SDK's handling of endpoints that end in a slash (`/`) causing
signature validation errors due to Request.HTTPRequest.URL.Path not
matching what was sent in the request.
Squashes the duplicate slash character between endpoint's path and
operation path.
> aws/request: Fix SDK's handling of endpoints ending in slash

- private/model/api/eventstream_tmpl_tests.go
Updates the SDK's code gen to not encode entries as `nil` for shapes
that have already been visited. This skips `nil`'s in nested slice and
map event stream shapes.
Related to bigger issue of SDK's JSON serializer does not correctly
skip, or serialize NULL for nil values in slices. https://github.com/aws/aws-sdk-go/issues/3933
> codegen: Dont serialize nil for visited nested event stream shapes

- internal/s3shared/arn/arn.go
- internal/s3shared/arn/arn_test.go
- internal/s3shared/endpoint_errors.go
- internal/s3shared/resource_request.go
- service/s3/endpoint.go
- service/s3/endpoint_test.go
- service/s3control/endpoint.go
- service/s3control/endpoint_builder.go
- service/s3control/endpoint_test.go
Update S3 ARN Handling for AccessPoints and Outpost ARNs
> Update S3 ARN Handling for AccessPoints and Outpost ARNs

- private/model/api/legacy_io_suffix.go
- private/model/api/load.go
- private/model/api/passes.go
- private/model/api/passes_test.go
Rename shapes that have `Input` or `Output` suffix in the shape name, but are not input or output shape for any operation. 
Shapes are renamed to add `_` at the end. 
To not break existing shape names, we maintain a legacy list.
> rename new shapes that are suffixed as Input/Output in shape name

- CHANGELOG_PENDING.md
- aws/ec2metadata/api_test.go
- aws/ec2metadata/service.go
Fixes the EC2 IMDS client to not retry 404 HTTP errors received for operations like GetMetadata.
> aws/ec2metadata: Fix client retrying HTTP 404 errors

- CHANGELOG_PENDING.md
- private/protocol/timestamp.go
- private/protocol/timestamp_test.go
Updates the SDK's parsing of IOS based date time formats to support UTC offsets.
Related to https://github.com/aws/smithy-go/pull/307
> private/protocol: add support for UTC offset for IOS datetime formats

- CHANGELOG_PENDING.md
- aws/signer/v4/header_rules.go
- aws/signer/v4/header_rules_test.go
- aws/signer/v4/headers_test.go
- aws/signer/v4/v4.go
Updates the SigV4 signer to exclude the X-Amz-Object-Lock- group of headers to not be signed as a part of the query string for presigned URLs.
Related to aws/aws-sdk-go-v2#1307
>  aws/signer/v4: Add X-Amz-Object-Lock-* as unhoisted presign headers

- private/protocol/rest/build.go
Fixed typo.
```
stirng -> string
```
> private/protocol/rest: Fix typo in build.go

- service/transcribestreamingservice/cust_integ_eventstream_test.go
Updates the SDK's transcribestreaming integration test to be skipped until the test can be made stable.
```go test -tags integration -run TestInteg_ -v ./service/transcribestreamingservice```
```
=== RUN   TestInteg_StartStreamTranscription
cust_integ_eventstream_test.go:39: test failing with CANCEL response
--- SKIP: TestInteg_StartStreamTranscription (0.00s)
=== RUN   TestInteg_StartStreamTranscription_contextClose
cust_integ_eventstream_test.go:102: test failing with CANCEL response
--- SKIP: TestInteg_StartStreamTranscription_contextClose (0.00s)
PASS
ok  	github.com/aws/aws-sdk-go/service/transcribestreamingservice	0.173s
```
> Skip TranscribeStreaming integration test until stable

- CHANGELOG_PENDING.md
- aws/ec2metadata/service.go
- aws/endpoints/decode.go
- aws/endpoints/decode_test.go
- aws/endpoints/defaults.go
- aws/endpoints/endpoints.go
- aws/endpoints/endpoints_test.go
- aws/endpoints/v3model.go
- aws/endpoints/v3model_test.go
- aws/session/doc.go
- aws/session/env_config.go
- aws/session/env_config_test.go
- aws/session/session.go
- aws/session/session_test.go
- aws/session/shared_config.go
- aws/session/shared_config_test.go
- aws/session/testdata/shared_config
Support for EC2 IMDS IPv6 Endpoints.
> EC2 IMDS IPv6 Support

- aws/signer/v4/header_rules.go
Related to the work done in https://github.com/aws/aws-sdk-go/pull/3968 - noted there were a few minor typos made when flipping to allow/exclude named lists.
> Fixup signer header rules excludeList struct/func descriptions

- service/dynamodb/expression/examples_test.go
Missing expression attribute names in example causes error: `An expression attribute value used in expression is not defined`
> Add missing expression attribute names to example

- models/apis/devicefarm/2015-06-23/smoke.json
- service/devicefarm/integ_test.go
Reverts https://github.com/aws/aws-sdk-go/pull/4004
> add smoke test for device-farm

- service/s3/endpoint_test.go
Updates Amazon S3 Output ARN unit test to more specifically describe the behavior that is being tested.
If the client's resolved endpoint's signing region does not match the Output ARN's region component the client will return the region not match error. If the client's resolved endpoint's signing region does match the Output ARN's region component, but the API client's configured region includes FIPS, the FIPS configured error will be returned.
> service/s3: Update unit test to clarify implemented behavior

- .github/workflows/stale_issues.yml
The stale issues yml had no message defined for stale pr's which meant that if "response-requested" was asssigned to a PR the aciton broke. 
Adding it fixes this.
> Update stale_issue.yml to include pr message

- CHANGELOG_PENDING.md
- service/s3/customizations.go
- service/s3/statusok_error.go
- service/s3/statusok_error_test.go
Fixes #4037. See that issue for more details.
Note, in case of read error we don't close the body because later Unmarshal hooks expect it to not be closed (they close it themselves). There's an existing test guarding that behavior.
Close error is ignored as it has no side effects and there's nothing we can do about it.
> Close http.Response.Body in S3 CopyObject, UploadPartCopy and CompleteMultipartUpload operations. 

- CHANGELOG_PENDING.md
- aws/awsutil/prettify.go
- aws/awsutil/prettify_test.go
- aws/awsutil/string_value.go
The SDK did not correctly suppress sensitive API parameters via the `String` and `GoString` methods. Updates the SDK's behavior to suppress sensitive API parameters.
> aws: Fix SDK's suppressing of sensitive API parameters being logged.

- CHANGELOG_PENDING.md
- private/protocol/timestamp.go
- private/protocol/timestamp_test.go
Adds support for parsing RFC 3339 timestamp but without the `Z` character, nor UTC offset.
Related to https://github.com/aws/aws-sdk-go-v2/issues/1387
> private/protocol: Add support for parsing RFC 3339 timestamp without trailing Z

- CHANGELOG_PENDING.md
- aws/client/logger.go
Updates the SDK's base client to only log request headers when logging is enabled. This fixes an issue where event stream API operations would always log request headers. Regardless if logging was enabled or not.
> aws/client: Update client to only log request headers when enabled

- CHANGELOG_PENDING.md
- service/dynamodb/dynamodbattribute/decode.go
- service/dynamodb/dynamodbattribute/decode_test.go
Fixes #3983 by correcting the unmarshaler's decoding of AttributeValue N parameter into string aliased type.
> service/dynamodb/dynamodbattribute: Fix string alias unmarshal

- private/model/api/docstring.go
- private/model/api/docstring_test.go
Allow docs-2.json to reference shapes not present in API without failure.
> Allow docs-2.json to reference shapes not present in API without failure

- private/model/api/example.go
- private/model/api/example_test.go
- private/model/api/shape_value_builder.go
Don't generate example shape values if they don't exist in the model.
> Don't generate example shape values if they don't exist in the model.

- private/model/api/smoke.go
- service/sts/integ_test.go
Customize STS smoke test definitions to remove `GetSessionToken` if present, and replace it with `GetCallerIdentity` if not present.
> STS Smoke Test Customization to use GetCallerIdentity

- service/dynamodb/expression/projection.go
Fixes typo in NameBuilder.NamesList example documentation to use the correct variable name.
> service/dynamodb/expression: Fixup NameBuilder example doc

- CHANGELOG_PENDING.md
- aws/crr/cache.go
- aws/crr/cache_test.go
- aws/crr/endpoint.go
- aws/crr/endpoint_test.go
Backports a fix from V2 SDK for a race condition in endpoint discovery as reported in https://github.com/aws/aws-sdk-go-v2/issues/1407
> Fix race condition in endpoint discovery

- private/protocol/rest/unmarshal.go
Fixes #4120 by returning error from unmarshalHeaderMap method.
>  private/protocol/rest: Fix return error in location headers

- example/aws/proxyWithTLSClientCert/main.go
This can remove `golang.org/x/net/http2` dependency.
This field was added at Go 1.13. This example file now required
Go 1.15+. So we can use this field safely.
Ref: https://golang.org/doc/go1.13#net/http
> example/aws/proxyWithTLSClientCert: Use `Transport.ForceAttemptHTTP2` to enable HTTP/2

- CHANGELOG_PENDING.md
- aws/credentials/stscreds/web_identity_provider.go
- aws/credentials/stscreds/web_identity_provider_test.go
- aws/session/credentials.go
- aws/session/credentials_test.go
- aws/session/session.go
Fixes #4160. It's a little different than what I originally proposed, since (1) this avoid an import cycle, and (2) this is a little more flexible.
> add options for customizing credential providers

- CHANGELOG_PENDING.md
- aws/request/request.go
- aws/request/request_test.go
Updates SDK Request.Send to always ensure HTTPResponse member is not
nil, and its Header and Body fields are not nil as well.
Fixes #4211
> aws/config: Update Request Send to always ensure HTTPResponse is not nil

- service/cloudfront/sign/privkey_test.go
This fixes two dropped test errors in `service/cloudfront/sign`.
The unit tests are still passing, so I don't believe that this warrants a changelog entry.
> service/cloudfront/sign: fix dropped test errors

- private/model/api/codegentest/models/restjson/0000-00-00/api-2.json
- private/model/api/codegentest/service/restjsonservice/api.go
- private/model/api/codegentest/service/restjsonservice/eventstream_test.go
- private/model/api/eventstream.go
Updates SDK's code generation for even stream event names to match the member's modeled name. Fixes the SDK not using the right case or name if the modeled name is not Go exportable name.
> codegen: Fixup event stream (un)marshal event name to match model

- service/s3/s3crypto/cipher_util_test.go
This fixes three dropped `err` variables in the `service/s3/s3crypto` tests.
> service/s3/s3crypto: fix dropped test errors

- private/model/api/codegentest/service/restjsonservice/api.go
- private/model/api/codegentest/service/restxmlservice/api.go
- private/model/api/codegentest/service/rpcservice/api.go
- private/model/api/eventstream_tmpl.go
- service/kinesis/api.go
- service/lexruntimev2/api.go
- service/s3/api.go
- service/transcribestreamingservice/api.go
Fixes missing closing parentheses in event stream docstring found in https://github.com/aws/aws-sdk-go/pull/4251
> codegen: Correct the generated event stream docstring

- CHANGELOG_PENDING.md
- private/model/api/api.go
- private/model/api/customization_passes.go
- private/model/api/legacy_jsonvalue.go
- private/model/api/load.go
- private/model/api/passes.go
- private/model/api/shape.go
- private/model/cli/gen-protocol-tests/main.go
- private/protocol/rest/build.go
- private/protocol/rest/unmarshal.go
- service/lexruntimeservice/api.go
- service/lexruntimeservice/cust_jsonvalue_test.go
Updates the SDK's code generation to stop supporting new API modeled JSONValue parameters. The SDK's JSONValue type is only compatible with JSON documents with a top level JSON Object. JSON Lists, Strings, Scalars, are not compatible. This prevents JSON Value working with some APIs such as Amazon Lex Runtime Service's operations. 
Related to [#4264](https://github.com/aws/aws-sdk-go/pull/4264) and [#4258](https://github.com/aws/aws-sdk-go/issues/4258)
Fixes https://github.com/aws/aws-sdk-go/issues/4258 https://github.com/aws/aws-sdk-go/issues/3847
This update also introduces the breaking change to service/lexruntimeservice package by changing the following parameters from a JSONValue to string type.
* PostContentInput.ActiveContexts
* PutContentOutput.AlternativeIntents
* …
> codegen: Update API client generation to not support new JSONValue members

- CHANGELOG_PENDING.md
- private/model/api/operation.go
- private/protocol/eventstream/eventstreamapi/transport.go
- private/protocol/eventstream/eventstreamapi/transport_go1.17.go
- service/lexruntimev2/api.go
- service/lexruntimev2/cust_integ_eventstream_test.go
- service/transcribestreamingservice/api.go
Adds fix addressing an issue where SDK's bi-directional eventstream API operation request could hang when the HTTP/2 stream was closed by the service with a non-200 status code.
Go 1.15 through 1.17 have an issue where the HTTP/2 request can hang while waiting for the HTTP response, and input payload reader. The Expect: 100-Continue workaround forces the HTTP client to wait for a `100 continue` or other HTTP status code before attempting to wait for the request's body to be read. This workaround is not needed for Go
1.18, as a fix to the HTTP client resolves this issue.
Fixes `services/lexruntimev2` and `service/transcribestreamingservice` eventstream operations.
Related to https://github.com/aws/aws-sdk-go-v2/pull/1515
> codegen: Add fix to prevent HTTP/2 event stream request hang on error

- aws/config.go
Adds small blurb to Config.LowerCaseHeaderMaps documenting the v1's opt-in behavior vs v2's default behavior. Related to https://github.com/aws/aws-sdk-go/issues/445
> config: add document to LowerCaseHeaderMaps v1 vs v2 behavior

- internal/ini/walker_test.go
This fixes a dropped `err` variable in the tests for `internal/ini`.
> internal/ini: fix dropped test error

- Makefile
This reverts commit 2a3e58928889934211e5c641d673ce1f9ed63a34.
Reverts REGABI disabling change since the issue was resolved in Go 1.17.6, and no longer impacts the SDK's code generation.
> Revert "Disable regabi due to on-going stability issues (#4245)"

- CHANGELOG_PENDING.md
- aws/request/handlers.go
- aws/request/handlers_test.go
Addresses an issue where the header keys being added were being added
directly to the header map, and did not have the canonical header casing
applied. This introduced bugs where instead of overwriting existing
header key, it added another map entry.
> aws/request: Fixes WithSetRequestHeaders key added to header map directly

- aws/endpoints/endpoints_test.go
- aws/endpoints/example_test.go
- aws/endpoints/main_test.go
- aws/endpoints/testdata/endpoints.json
- aws/endpoints/v3model_legacy_region_test.go
- aws/endpoints/v3model_test.go
Updates the SDK's endpoints model unit tests to ensure that unit tests are performed on static data instead of the live model that can be updated at any time. This change was done to ensure that upstream sources of endpoint models making semantic changes do not cause unit tests to break.
> aws/endpoints: Update unit tests use static data instead of live model

- CHANGELOG_PENDING.md
- private/model/api/legacy_jsonvalue.go
- service/cloudwatchevidently/api.go
Introduces a breaking change for following parameters from a JSONValue to string type, because the SDKs JSONValue is not compatible with the service's request and response shapes.
`EvaluateFeatureInput.EvaluationContext`
`EvaluateFeatureOutput.Details`
`EvaluationRequest.EvaluationContext`
`EvaluationResult.Details`
`Event.Data`
`ExperimentReport.Content`
`MetricDefinition.EventPattern`
`MetricDefinitionConfig.EventPattern`
> Breaking change to fix JSONValue usage for CloudWatch Evidently.

- CHANGELOG_PENDING.md
- internal/encoding/gzip/handler.go
- internal/encoding/gzip/handler_test.go
- service/cloudwatch/customizations.go
- service/cloudwatch/customizations_test.go
Adds a new helper, `WithGzipRequest` to compress the request payload before it is sent. May not be supported by all API operations. See service's API Reference docs for details about operations that are supported.
> service/cloudwatch: Add helper for GZIP request payload

- CHANGELOG_PENDING.md
- private/model/api/legacy_jsonvalue.go
- service/pricing/api.go
* `service/pricing`: Fixes a bug that caused `GetProductsOutput.PriceList` to be generated incorrectly. ([#4486](https://github.com/aws/aws-sdk-go/pull/4486))
* The [v1.44.46](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.46) release incorrectly resulted in the `PriceList` field's type changing from `[]aws.JSONValue` to `[]*string`.
* This release reverts this change, with the field now correctly updated to `[]aws.JSONValue`.
* Fixes [#4480](https://github.com/aws/aws-sdk-go/issues/4480)
> service/pricing: Fix PriceList type to aws.JSONValue

- CHANGELOG_PENDING.md
- service/dynamodb/dynamodbattribute/encode.go
- service/dynamodb/dynamodbattribute/encode_test.go
this change adds a String method to dynamodbattribute.UnixTime, so that when structs with this field get logged it prints a human readable time
> add String to dynamodbattribute.UnixTime

- private/model/api/docstring.go
- private/model/api/docstring_test.go
Fixes the SDKs code generation handling of unexpected closing HTML tags when processing API documentation.
This bug prevented the SDK to correctly generate `privatenetworks` API client published in the v1.44.74 release.
> codegen: Fix SDK codegen handling of poorly formatted API docs

- CHANGELOG.md
Fixes the SDK's changelog to have correct changenotes for v1.44.75 and v1.44.74.
> Fixup CHANGELOG.md to have correct changenotes for v1.44.75 and 74.

- private/protocol/ec2query/unmarshal.go
- private/protocol/ec2query/unmarshal_error_test.go
- private/protocol/query/unmarshal_error.go
- private/protocol/query/unmarshal_error_test.go
Fixes the ec2query and query protocol error deserializers to trim leading and trailing spaces from error code and message parameters. JSON based protocol's don't need this change, because the values are quoted.
> private/protocol/query: Fix deserialize error code with spaces

- CHANGELOG_PENDING.md
- internal/shareddefaults/shared_config.go
- internal/shareddefaults/shared_config_resolve_home.go
- internal/shareddefaults/shared_config_resolve_home_go1.12.go
https://github.com/aws/aws-sdk-go/issues/4444
Added a fallback to resolve home using current user from "os/user".
> fix-resolve-home-v1

- private/protocol/json/jsonutil/build.go
- private/protocol/json/jsonutil/build_test.go
- private/protocol/json/jsonutil/unmarshal.go
- private/protocol/json/jsonutil/unmarshal_test.go
- private/protocol/query/queryutil/queryutil.go
- private/protocol/rest/build.go
- private/protocol/rest/build_test.go
- private/protocol/rest/unmarshal.go
- private/protocol/rest/unmarshal_test.go
- private/protocol/xml/xmlutil/build.go
- private/protocol/xml/xmlutil/build_test.go
- private/protocol/xml/xmlutil/unmarshal.go
- private/protocol/xml/xmlutil/unmarshal_test.go
Adds protocol level support for float values that are NaN (Not a Number), or signed infinity.
> Protocol Support for NaN/Infinity/-Infinity float values

- private/model/api/endpoint_arn.go
When a model has multiple elements where `if $elem.AccountIDMemberWithARN ` is true it will create the same function signature for each element
```
func (s {{ $.ShapeName }}) updateAccountID(accountId string) (interface{}, error) {
```
This updates the function signature to take the shape name into account
```
func (s {{ $.ShapeName }}) update{{ $name }}(accountId string) (interface{}, error) {
```
> Fixes codegen for multiple account ids

- aws/credentials/ec2rolecreds/ec2_role_provider_test.go
- aws/session/credentials_test.go
- private/protocol/jsonrpc/unmarshal_error.go
- service/s3/statusok_error_test.go
Removes timestamp with single digit hour code to avoid confusion. Also fixes lint issues (`make lint` was failing from query compatible work apparently).
> fix misleading timestamp value from tests and lint issues

- service/s3/platform_handlers_go1.6.go
- service/s3/platform_handlers_go1.6_test.go
ref: https://www.rfc-editor.org/rfc/rfc9110.html#name-expect
Expect header value should be "100-continue" not "100-Continue"
> Fix expect header value to '100-continue'

- aws/credentials/processcreds/provider.go
In order to have a canonical type for encoding/decoding JSON for a credential process, the visibility of this type needed to be public. This type has been detailed in official AWS CLI documentation and is effectively part of the tooling ecosystem's external interface.
> Update `processcreds.CredentialProcessResponse` visibility to public

- .github/workflows/go.yml
Excluding Go versions which appear to fail when run on macos-latest.
Exclude <= 1.10 on macos-latest for without module support because of:
https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue
Excluding 1.11-1.16 on macos-latest for same reasons listed on https://github.com/aws/aws-sdk-go-v2/pull/1971/
> remove failing Go versions on macos-latest

- .github/workflows/go.yml
Update CI to cover latest two Go versions to 1.19 and 1.20
> add go 1.20 support

- CHANGELOG_PENDING.md
- aws/config.go
- aws/ec2metadata/api_test.go
- aws/ec2metadata/service.go
- aws/ec2metadata/token_provider.go
* Adds a flag to config to disable IMDSv1 fallback. When enabled the `EC2Metadata` client will return an error when fetching a token from IMDS fails instead of falling back to the insecure data flow of IMDSv1
* I did confirm (and tests cover this) that fetching a token is retried
v2 PR: https://github.com/aws/aws-sdk-go-v2/pull/2048
> feat: add flag to disable IMDSv1 fallback

- CHANGELOG_PENDING.md
- private/protocol/restjson/unmarshal_error.go
- private/protocol/restjson/unmarshal_error_test.go
Closes #4733 
This fix will handle cases when an unknown error response includes a code header, but not a message header. Rather than returning an empty message (the current behavior) the message parsed from the JSON body is returned.
Here is a trivial example of a lambda `ValidationException` before and after the change:
Before:
```
ValidationException:
status code: 400, request id: 455ba702-2c14-42e4-993f-f091b2e956e2
```
After:
```
ValidationException: 1 validation error detected: Value '2000' at 'timeout' failed to satisfy constraint: Member must have value less than or equal to 900
status code: 400, request id: 60e3a922-3eec-4fb3-b3fe-83c8e2bca1ed
```
Also adds a pair of unit tests to cover "unknown" response cases with partial headers (ie. code without message and vice-versa): …
> Use request body error message for unknown errors missing a message header

- aws/session/session.go
Just fixing a typo in `AssumeRoleTokenProvider` parameter description.
> Fix typo in AssumeRoleTokenProvider description

- CHANGELOG_PENDING.md
- aws/session/session.go
Move credentials resolution after other config values are resolved from the current environment. Notably `AWS_USE_FIPS_ENDPOINT` and `AWS_USE_DUALSTACK_ENDPOINT` were being resolved after the credentials chain was configured. This results in credentials that use STS or other AWS service endpoints to not respect those settings. 
internal: `P83606045`
> fix: resolve credentials last such that other environment config is respected

- CHANGELOG.md
Creates a change log entry that explains changes done on a previous release. specifically [Ssm sap rename](https://github.com/aws/aws-sdk-go/commit/b18be4c13c6dbd9c53660012dbf7d52c919f4ce4). addressed [issues/4631](https://github.com/aws/aws-sdk-go/issues/4631)
This change removed model files from `models/apis/ssmsap` as they are now being placed in `models/apis/ssm-sap` due to a update in naming for the service. This functionally changes nothing and this is reflected by the changelog one 1.44.141 
```
service/ssm-sap: Updates service API, documentation, paginators, and examples
```
That release actually contained incorrect artifacts and `1.44.142` updated them correctly.
> Adds missing changelog entry for a past release.

- private/model/api/pagination.go
- private/model/api/smoke.go
- private/model/api/waiters.go
N/A.
---
N/A.
---
`aws-sdk-go` doesn't support document types, so they are removed from the API JSON models upstream (and anything that references it, i.e. structures and even operations). 
Paginators do not have the same upstream removal process, so there could be "orphaned" operations. This change loosens restrictions when loading paginators, waiters, and smoke tests when an operation cannot be found in the API JSON model.
Loosen operation existence during model loading so generation won't fail when operations don't exist in …
> Loosen Operation Existence during Model Loading

- service/ec2/customizations.go
- service/ec2/customizations_test.go
N/A.
---
N/A.
---
*Description:*
In some cases, the Presigned URL was NOT being sent when calling EC2 CopySnapshot.
This PR fixes the customization responsible for generating the Presigned URL.
*Testing:*
1. CI/CD
2. New unit tests for the customization cases
> Fix EC2 Presigned URL customization

- aws/credentials/stscreds/assume_role_provider.go
This commit adds support for exposing SourceIdentity on the `AssumeRoleProvider` class.
This is a very small commit and just passes through the params.
Fixes #4829
> Add support for SourceIdentity to stscreds.NewCredentials

- CHANGELOG_PENDING.md
- aws/config.go
- private/protocol/rest/build.go
- private/protocol/rest/build_test.go
> Revert "Deprecate url path cleaning during http request serialization"

- private/model/cli/gen-api/main.go
This is being flagged by Snyk as a security issue. In other places in the code, debug.Stack() is wrapped in string(). Just adding that here.
> Wrap debug.Stack() in string()

- CHANGELOG_PENDING.md
- aws/signer/v4/v4.go
Example code of testing an outpost endpoint. NOTE: You don't actually have to have an outpost endpoint setup, just plugin your own account and a dummy value for the access point (e.g. `my-test-access-point`). 
```go
package main
import (
"github.com/aws/aws-sdk-go/aws"
"github.com/aws/aws-sdk-go/aws/session"
"github.com/aws/aws-sdk-go/service/s3"
"fmt"
)
func main() {
sess, err := session.NewSession(&aws.Config{
Region: aws.String("us-east-1"),
LogLevel: aws.LogLevel(aws.LogDebugWithHTTPBody),
},)
svc := s3.New(sess)
bucket := "arn:aws:s3-outposts:us-east-1:<account>:outpost/ec2/accesspoint/<my-access-point>"
resp, err := svc.ListObjectsV2(&s3.ListObjectsV2Input{Bucket: aws.String(bucket)})
fmt.Printf(" response %v error %v \n", resp, err)
}
```
output contains
```
Missing required header …
```
> fix s3 requests sent to outpost arn missing x-amz-content-sha256 header

- aws/session/credentials.go
This change exposes the options for the ProcessProvider in the session's CredentialsProviderOptions. This allows users to configure the timeout for a ProcessProvider.
> Expose ProcessProviderOptions in session's CredentialsProviderOptions

- CHANGELOG_PENDING.md
- private/model/api/codegentest/service/restjsonservice/api.go
- private/model/api/codegentest/service/restxmlservice/api.go
- private/model/api/codegentest/service/rpcservice/api.go
- private/model/api/eventstream_tmpl.go
- service/kinesis/api.go
- service/lambda/api.go
- service/lexruntimev2/api.go
- service/s3/api.go
- service/transcribestreamingservice/api.go
Event stream codegen blindly imports `"time"`, but doesn't actually use it unless one of the following is true:
* there's a stream with input
* a payload or header used in event streaming has a timestamp field
This patch adds a compile-time reference to prevent `vet` from failing on the unused import (as we've done with `"awserr"` whose usage is also conditional in event streams).
> prevent unused time import in event streams

- aws/signer/v4/v4.go
> Fix typo in v4.go: "many" should be "may"

- CHANGELOG_PENDING.md
- aws/credentials/ssocreds/token_provider.go
Modify sso token provider logic to handle possible nil token val returned by ssooidc CreateToken op, possibly will resolve #4947
> Handle nil token returned by ssooidc

- .github/workflows/go.yml
> Upgrade GitHub Actions packages to resolve deprecation warnings

- CHANGELOG_PENDING.md
- service/glacier/treehash.go
- service/glacier/treehash_test.go
Hello. I've decided to rework **ComputeTreeHash** function because it makes lots of memory allocations. 
Benchmark I used:
```
func BenchmarkComputeTreeHash(b *testing.B) {
var hashes [][]byte
for i := 0; i < 1024; i++ {
h := sha256.Sum256([]byte("test"))
hashes = append(hashes, h[:])
}
b.ResetTimer()
for i := 0; i < b.N; i++ {
_ = glacier.ComputeTreeHash(hashes)
}
b.ReportAllocs()
}
```
Benchcmp result:
```
benchmark                       old ns/op     new ns/op     delta
BenchmarkComputeTreeHash-10     128886        88221         -31.55%
benchmark                       old allocs     new allocs     delta
BenchmarkComputeTreeHash-10     3124           1              -99.97%
benchmark                       old bytes     new bytes     delta
BenchmarkComputeTreeHash-10     179808 …
```
> Reduce memory allocations when computing a tree hash

- example/aws/credentials/plugincreds/plugin/plugin.go
- go.mod
- go.sum
repo github.com/pkg/errors has been archived since Dec 2021.
Go starting with version 1.13, there is now a standard way of replacing the errors.Wrap functions.
The included change should produce exactly the same error.
https://go.dev/blog/go1.13-errors is a good reference
> Remove depricated package github.com/pkg/errors

- service/s3/s3crypto/aes_cbc_content_cipher.go
- service/s3/s3crypto/aes_gcm_content_cipher.go
- service/s3/s3crypto/decryption_client.go
- service/s3/s3crypto/encryption_client.go
- service/s3/s3crypto/envelope.go
- service/s3/s3crypto/kms_key_handler.go
Documentation for deprecated functions on pkg.go.dev is case-sensitive. 
Examples
- Working: https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.46.6/aws/awsutil#StringValue
- Broken: https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.46.6/service/s3/s3crypto#EncryptionClient
> Fix deprecated function documentation

- CHANGELOG_PENDING.md
- aws/signer/v4/v4.go
Adding the `x-amz-expected-bucket-owner` to the list of headers to sign. 
Driver code:
```go
package main
import (
"fmt"
"io"
"net/http"
"time"
"github.com/aws/aws-sdk-go/aws"
"github.com/aws/aws-sdk-go/aws/session"
"github.com/aws/aws-sdk-go/service/s3"
)
func main() {
sess, err := session.NewSession(&aws.Config{
Region: aws.String("us-east-1"),
})
if err != nil {
panic(err)
}
svc := s3.New(sess)
req, _ := svc.GetObjectRequest(&s3.GetObjectInput{
Bucket:              aws.String("bucket"),
Key:                 aws.String("hey.txt"),
ExpectedBucketOwner: aws.String("123456789123"),
})
str, err := req.Presign(60 * time.Minute)
if err != nil {
fmt.Println("Failed to sign request", err)
return
}
fmt.Println("The presigned URL is:", str)
request, err := http.NewRequest("GET", str, nil)
if err …
```
> Add `x-amz-expected-bucket-owner` as a header the SDK needs to sign

- CHANGELOG_PENDING.md
https://github.com/aws/aws-sdk-go/pull/5062/ had an incorrect changelog pending format. 
This PR fixes it.
> Fix changelog pending format

- CHANGELOG_PENDING.md
- private/model/api/api.go
- private/model/api/codegentest/service/awsquerycompatible/awsquerycompatible_test.go
- service/sqs/errors.go
On 11/8/2023, the values for SQS string error constants were incorrectly changed when SQS switched protocols from AWS Query to AWS JSON.
This PR reverts SQS string error constants back to their old values on 11/7/2023
Testing:
correctness can be verified by viewing the diff between the commit ID on 11/7/2023 and the latest commit ID on this PR branch
```
git diff b87529cf2 b601e1966 -- service/sqs/errors.go
```
Fixes: https://github.com/aws/aws-sdk-go/issues/5090
> Breakfix revert SQS string error constants

- CHANGELOG.md
Drop s3express blurb since v1 didn't get support.
> drop s3express blurb

- CHANGELOG_PENDING.md
- aws/config.go
The ability to chain `UseFIPSEndpoint` was missing.
> Add `WithUseFIPSEndpoint` to `aws.Config`

- CHANGELOG_PENDING.md
- aws/ec2metadata/token_provider.go
**Description**
Addresses #5116 
This PR updates the logging behavior in the EC2Metadata token provider (`token_provider.go`). It modifies the conditions under which the warning message about falling back to IMDSv1 is logged.
**Changes**
The warning _"WARN: failed to get session token, falling back to IMDSv1"_ in the `fetchTokenHandler` method is now conditioned on the `LogLevel` being set to `LogDebugWithDeprecated`.
This update prevents the warning from being logged when the `LogLevel` is configured to suppress such messages.
**Testing**
This testing setup demonstrates the modified behavior of the EC2Metadata token provider, using a custom HTTP transport to simulate conditions that trigger a fallback to IMDSv1. The test verifies that the warning message is conditionally logged based on …
> Add log level check to gate IMDSv1 fallback warning

- CHANGELOG_PENDING.md
- private/protocol/query/queryutil/queryutil.go
Backport https://github.com/aws/aws-sdk-go-v2/issues/2627 to v1. Verified correct behavior w/ `RevokeSecurityGroupEgress` request--
before:
```
Action=RevokeSecurityGroupEgress&GroupId=asdf&IpPermissions=&Version=2016-11-15
```
after:
```
Action=RevokeSecurityGroupEgress&GroupId=asdf&Version=2016-11-15
```
> don't serialize empty lists in ec2query

- CHANGELOG_PENDING.md
- aws/request/waiter.go
- aws/request/waiter_test.go
Adds missing functionality defined in the waiters spec:
> error: A string representing the parsed AWS error code when looking for a specific error code, **or boolean true to match on any error code, or boolean false to test if no errors were encountered.**
Nothing actually uses this right now but I modified dynamodb's two error-match waiters with expected booleans to test generation.
> add missing any/none waiter error matching

- README.md
Adds maintenance mode announcement to the readme.
[hyperlink to md render](https://github.com/aws/aws-sdk-go/blob/d5e950bcb776482360d5934944f90a8139064d59/README.md)
We should merge **before** the final release on 7/30 such that this message is captured in the tagged version.
> [merge before 7/30 release] declare maintenance mode

- aws/session/shared_config.go
- awstesting/assert.go
- private/model/api/load.go
- service/dynamodb/dynamodbattribute/converter.go
- service/sqs/checksums.go
Go 1.24 is expected to release in the coming weeks. Though this package isn't accepting PRs, this will no longer build without an update. This change simply fixes the vetting/printf-style issues the compiler now catches. There is no real functionality changed being introduced.
> Fix improper use of Printf-style functions

- CHANGELOG.md
- aws/version.go
**[IMPORTANT] We [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025) the upcoming end-of-support for AWS SDK for Go v1. We are no longer accepting PRs for the v1 SDK.**
> release v1.55.6 (2025-01-15)

- CHANGELOG_PENDING.md
- service/s3/s3manager/download.go
- service/s3/s3manager/download_test.go
This pr fixes #4986, which is a port from the [fix](https://github.com/aws/aws-sdk-go-v2/pull/3050) on go v2
> Feat GetObject Version Control

- CHANGELOG.md
- aws/version.go
**[IMPORTANT] We [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025) the upcoming end-of-support for AWS SDK for Go v1. We are no longer accepting PRs for the v1 SDK.**
> release v1.55.7 (2025-04-22)
