aws/aws-sdk-go

aws/ec2.go
aws/error.go
aws/json.go
aws/query.go
aws/rest.go
aws/rest_test.go
gen/cloudfront/cloudfront.go
gen/cognito/sync/sync.go
gen/elastictranscoder/elastictranscoder.go
gen/lambda/lambda.go
gen/route53/route53.go
gen/s3/s3.go
model/model.go
model/templates.go

This is a merged version of these pull requests
* #49 - Include HTTP StatusCode in APIError
* #51 - Fix crash on nil nested XML structs
* #52 - s3: Make Size 64 bit
* #53 - Url escape path components the way AWS expects 
* #54 - Make Metadata in headers work
If you want to merge all of those unchanged then you can merge this instead which will make your life easier, especially since git got one of the merges wrong when I did them and it needed fixing.
If you don't want to merge all of the above as-is then just close this pull request and I'll rebase the pull requests as necessary.
Thanks
Nick

Merged fixes from @ncw

---

gen/endpoints/endpoints.go

Reverts stripe/aws-go#65
Modifies a generated file.

Revert "Add support for service endpoint overrides"

---

aws/ec2.go
aws/ec2_test.go

Code copied from `query.go` and `query_test.go`.
Fixes #68

Added code to catch time.Time when reflecting

---

README.md

fix sample code to show all instances' id

fix sample code

---

README.md
service/s3/content_md5.go
service/s3/customizations.go

~~The set of operations that require Content-MD5 is incomplete.~~ (edit: all operations were added)
Fixes #154

service/s3: build handler that adds Content-MD5 to requests requiring it

---

.gitignore
.travis.yml
Makefile
README.md
aws/corehandlers/handlers.go
aws/corehandlers/param_validator.go
aws/request/handlers_test.go
awsmigrate/awsmigrate-renamer/rename/rename.go
private/signer/v4/v4_test.go
service/cloudfront/sign/policy_test.go
vendor/github.com/vaughan0/go-ini/LICENSE
vendor/github.com/vaughan0/go-ini/README.md
vendor/github.com/vaughan0/go-ini/ini.go
vendor/github.com/vaughan0/go-ini/ini_linux_test.go
vendor/github.com/vaughan0/go-ini/ini_test.go
vendor/github.com/vaughan0/go-ini/test.ini

Updates the SDK by adding its runtime dependancies to the `vendor` folder enabling support for Go 1.5's experimental vendoring.

Update the SDK to vendor its runtime dependencies.

---

aws/awsutil/equal.go
aws/awsutil/equal_test.go
private/model/api/waiters.go
private/waiter/waiter.go
private/waiter/waiter_test.go
service/cloudformation/waiters.go
service/cloudfront/waiters.go
service/dynamodb/waiters.go
service/ec2/waiters.go
service/ecs/waiters.go
service/elasticache/waiters.go
service/elastictranscoder/waiters.go
service/elb/waiters.go
service/emr/waiters.go
service/glacier/waiters.go
service/iam/waiters.go
service/kinesis/waiters.go
service/opsworks/waiters.go
service/rds/waiters.go
service/redshift/waiters.go
service/s3/waiters.go
service/ses/waiters.go

Fixes the waiter's check for matches to handle pointer vs value.
Adds tests for waiters.
Fix #442

Fix waiters to correctly wait for their associated resources

---

awstesting/integration/smoke/shared.go

This reverts commit 06e1b9c18b10a18ab549459aec463b90c2008ea7.
The upstream dependency was update to remove the breaking change.
Fix #495

Revert "Shim gucumber.Tester to workaround stretchr/testify#263"

---

aws/awserr/error.go
aws/awserr/types.go
aws/credentials/chain_provider.go
aws/credentials/chain_provider_test.go
service/s3/s3manager/upload.go

Allows for multiple errors to be logged and printed

---

aws/awserr/error.go
aws/awserr/types.go
aws/config.go
aws/credentials/chain_provider.go
aws/credentials/chain_provider_test.go
aws/defaults/defaults.go

Fixes #515 backwards breaking change

VerboseErrors flag fixing previous merge

---

aws/awserr/error.go

Fix up example code for unwrapping awserr.Error

---

awstesting/util.go
awstesting/util_test.go
private/protocol/protocol_test.go
private/protocol/rest/unmarshal.go
private/protocol/restjson/restjson.go
service/s3/unmarshal_error.go
service/s3/unmarshal_error_leak_test.go
service/s3/unmarshal_error_test.go
service/simpledb/unmarshal_error_leak_test.go
service/simpledb/unmarshall_error.go

* New testing `io.ReadCloser` for detecting leaks, `awstesting.ReadCloser`. 
* Protocol tests to check for leaks
* Service tests to check for leaks
* Close and drain body where necessary

protocol tests to test for response body closing and being drained

---

aws/ec2metadata/api.go
aws/ec2metadata/api_test.go

I think that both methods can be useful.
It would make my code slightly cleaner in https://github.com/hashicorp/terraform/pull/5030

ec2metadata: Add IAMInfo()

---

aws/client/default_retryer.go
aws/request/request_test.go
aws/request/retryer.go
aws/request/retryer_test.go

Change the floor for throttling retries

---

aws/session/session.go

Missing parenthes in docs

---

private/signer/v4/v4.go
private/signer/v4/v4_test.go

Fixes #642. Issue with spacing in headers for s3 v4 signing

---

private/model/api/load.go

Fixes malformed models would not report an error when being loaded.

private/model/api: Update load to fail on error loading model.

---

models/protocol_tests/generate.go
models/protocol_tests/input/rest-json.json
models/protocol_tests/input/rest-xml.json
private/protocol/restjson/build_test.go
private/protocol/restxml/build_test.go

Adds a state to check for the type of test it is. For instance, input tests will be flagged as such.

Updating protocol tests

---

doc-src/aws-godocs/templates/godoc.html

Update's the template for pkg list to be an html instead of path.

Update doc generation template

---

example/service/s3/listObjects/listObjects.go

Fix example

---

service/cloudfront/sign/policy.go
service/cloudfront/sign/sign_url.go
service/cloudfront/sign/sign_url_test.go

A simple check to make sure you arent passing a URL which contains non-ascii characters

Test that url does not contain any non-ascii characters before signing

---

aws/defaults/defaults.go
aws/request/request.go
aws/request/request_1_6_test.go
aws/request/request_test.go

Invalid endpoint URL fix

---

Makefile
awstesting/sandbox/Dockerfile.golang-tip
awstesting/sandbox/Dockerfile.test.go1.7

Adds sandbox tests for Go 1.7 (currently 1.7beta1)

Add Go 1.7 sandbox testing

---

Makefile

Reduces the noise in unit test that are used for travis.

Simplify unit-testing for travis

---

aws/convert_types.go

http://docs.aws.amazon.com/sdk-for-go/api/aws.html

Remove typos in convert_types docs

---

service/dynamodb/dynamodbattribute/doc.go

Updating docs to specify which time formats are supported.

---

aws/awsutil/copy.go
aws/awsutil/copy_test.go

Fixing bug where time wasn't being properly set

---

private/protocol/json/jsonutil/build.go

Linter was complaining about implied types

Linter fix

---

service/dynamodb/dynamodbattribute/decode.go

fixed typo in error message on InvalidUnmarshalError

Typo in Message

---

aws/signer/v4/v4.go
aws/signer/v4/v4_test.go

The Sign method was not setting the provided body to the request as
would be expected. This fixes this issue by setting the body parameter
as the request's Body field.

aws/signer/v4: Fix signer to set signed body on request as expected

---

example/aws/request/handleServiceErrorCodes/README.md
example/aws/request/handleServiceErrorCodes/handleServiceErrorCodes.go

Example which shows how specific service error codes can be handled.

example: Add handling specific service error code

---

aws/ec2metadata/api.go
aws/ec2metadata/api_test.go

Adds the `GetUserData` method to `EC2Metadata` client. This allows you
to get instance user data from the `/latest/user-data` EC2 metadata
endpoint.
If the instance does not have any data set the error code
`NotFoundError` will be returned. If any data is set that value as a
string will be returned by the method.
Fix #852

aws/ec2metadata: Add support for EC2 User Data

---

CHANGELOG.md
aws/version.go
models/apis/acm/2015-12-08/api-2.json
models/apis/acm/2015-12-08/docs-2.json
models/apis/elasticbeanstalk/2010-12-01/api-2.json
models/apis/elasticbeanstalk/2010-12-01/docs-2.json
models/apis/gamelift/2015-10-01/api-2.json
models/apis/gamelift/2015-10-01/docs-2.json
models/apis/gamelift/2015-10-01/examples-1.json
service/acm/acmiface/interface.go
service/acm/api.go
service/acm/examples_test.go
service/acm/service.go
service/elasticbeanstalk/api.go
service/elasticbeanstalk/examples_test.go
service/elasticbeanstalk/service.go
service/gamelift/api.go
service/gamelift/examples_test.go
service/gamelift/gameliftiface/interface.go
service/gamelift/service.go

Service Model Updates
---
* `service/acm`: Update service API, and documentation.
* This change allows users to import third-party SSL/TLS certificates into ACM.
* `service/elasticbeanstalk`: Update service API, documentation, and pagination.
* Elastic Beanstalk DescribeApplicationVersions API is being updated to support pagination.
* `service/gamelift`: Update service API, and documentation.
* New APIs to protect game developer resource (builds, alias, fleets, instances, game sessions and player sessions) against abuse.
SDK Features
---
* `service/s3`: Add support for accelerate with dualstack (#887)

Release v1.4.17

---

example/service/dynamodb/unitTest/README.md
example/service/dynamodb/unitTest/unitTest.go
example/service/dynamodb/unitTest/unitTest_test.go

This patch demonstrates how one might unit test with DynamoDB that
integrates well with Go `type` development.
I didn't find much in the way of unit test examples, so thanks to
@xibz's help, I came up with this.

Example of unit test w/ DynamoDB in struct's field

---

aws/signer/v4/v4.go
aws/signer/v4/v4_test.go

moved sorting to be at the root `Signer` level.

Moving where sorting is done

---

aws/request/retryer.go

aws/request: Add PriorRequestNotComplete to throttle retry codes

---

doc-src/aws-godoc/templates/package_service.html
doc-src/aws-godoc/templates/pkglist.html
doc-src/aws-godoc/templates/style.css

This updates the doc templates to be more customer friendly.

Updating aws-godoc

---

doc-src/aws-godoc/templates/pkglist.html
doc-src/aws-godoc/templates/style.css

Docs on Firefox were displaying package list incorrectly.

Update Docs pkg list for Firefox

---

README.md

Updates README.md with additional info on getting help, and handling of issues.

Add Getting help and  Opening issues to readme

---

private/model/api/operation.go
service/apigateway/api.go
service/cloudfront/api.go
service/cognitosync/api.go
service/efs/api.go
service/elastictranscoder/api.go
service/elb/api.go
service/lambda/api.go
service/machinelearning/api.go
service/marketplacemetering/api.go
service/route53/api.go
service/s3/api.go
service/sfn/api.go
service/ssm/api.go
service/swf/api.go
service/workspaces/api.go

Getting rid of an extra line that was being generated with the documentation of errors.

Fix doc error list

---

service/s3/s3manager/upload.go
service/s3/s3manager/upload_test.go

service/s3/s3manager: Adding support for sse

---

private/protocol/rest/rest_test.go
private/protocol/rest/unmarshal.go

private/protocol/rest: Ignore unset header when unmarshaling responses

---

service/s3/s3manager/s3manageriface/interface.go

Update s3manageriface with new context methods.

---

README.md

Updates the READEME example to highlight the new Context support. Also cleans up header to put tags on same line as title.

Update README example highlighting context support.

---

aws/session/doc.go

I just noticed this small discrepancy, and decided to try to fix it. Let me know if I need to do anything else.

Correct documentation for session.SharedConfigEnable

---

doc-src/aws-godoc/templates/package_service.html
doc-src/aws-godoc/templates/style.css

doc-src/aws-godoc/templates: Add deprecated tag for operations in docs

---

service/rds/rdsutils/connect.go

service/rds/rdsutil: Changing signing name

---

service/rds/rdsutils/connect.go
service/rds/rdsutils/connect_test.go

service/rds/rdsutils: Scheme isn't included in the presigner

---

README.md
doc-src/aws-godoc/templates/style.css

Cleaned up the README's header style and fixup to the godoc styling.
Related #1224

Fixup SDK README and doc styles

---

service/dynamodb/dynamodbattribute/encode.go

Fix typo in dynamodbattribute.UnixTime docs

---

service/polly/customizations_test.go

service/polly: Remove testify from tests.

---

README.md

Corrects typo in README's Getting Help section.

Fix Typo for Getting help in README

---

aws/signer/v4/v4.go

aws/signer/v4: Correct wording for signer's docs.

---

aws/request/validation.go

Change ParamMinValueErrCode to ParamMinLenErrCode

---

service/dynamodb/dynamodbattribute/decode.go

Update doc for typo on UnmarshalDynamoDBAttributeValue function

Update doc for typo on UnmarshalDynamoDBAttributeValue function

---

aws/logger.go

Update comments in logger.go

---

aws/signer/v4/v4.go
aws/signer/v4/v4_test.go

aws/signer/v4: checking length on stripExcessSpaces

---

aws/signer/v4/v4.go
aws/signer/v4/v4_test.go

aws/signer/v4: Fixing issue with double spaces

---

example/aws/credentials/plugincreds/main.go

Fixes the usage docs for the plugin credentials example.

example/aws/credentials/plugincreds: Update usage docs

---

service/s3/s3manager/batch.go
service/s3/s3manager/batch_test.go

service/s3/s3manager: Delete will now call DeleteObjects rather than DeleteObject

---

service/s3/s3manager/batch_test.go

Minor clean up to BatchDelete's tests.

service/s3/s3manager: Minor cleanup to BatchDelete tests

---

aws/request/waiter.go
aws/request/waiter_test.go
private/model/api/waiters.go

aws/request: Fixing data race in waiters test

---

private/protocol/restxml/build_bench_test.go

Cleans up the RESTXML benchmarks, and adds additional tests for request lifecycle.

private/protocol/restxml: Cleanup and add new benchmarks

---

.travis.yml

Updating travis file to attempt to have it run more stable

---

aws/request/request.go

Fix incorrect "recieved"  comment

---

private/model/api/waiters.go
service/appstream/waiters.go
service/autoscaling/waiters.go
service/cloudformation/waiters.go
service/cloudfront/waiters.go
service/cloudwatch/waiters.go
service/codedeploy/waiters.go
service/dynamodb/waiters.go
service/ec2/waiters.go
service/ecs/waiters.go
service/elasticache/waiters.go
service/elastictranscoder/waiters.go
service/elb/waiters.go
service/elbv2/waiters.go
service/emr/waiters.go
service/glacier/waiters.go
service/iam/waiters.go
service/kinesis/waiters.go
service/machinelearning/waiters.go
service/opsworks/waiters.go
service/rds/waiters.go
service/redshift/waiters.go
service/route53/waiters.go
service/s3/waiters.go
service/ses/waiters.go

Closes #1453
Hope I was supposed to run `make generate` before committing. I can remove the generated file changes if needed. Thanks!

grammatical fixes

---

service/dynamodb/expression/condition.go
service/dynamodb/expression/condition_test.go
service/dynamodb/expression/operand.go
service/dynamodb/expression/operand_test.go

And and Between Condition

---

service/dynamodb/expression/condition.go
service/dynamodb/expression/condition_test.go
service/dynamodb/expression/operand_test.go

Implement rest of condition expression functions

---

service/dynamodb/expression/condition.go
service/dynamodb/expression/condition_test.go
service/dynamodb/expression/operand.go
service/dynamodb/expression/operand_test.go
service/dynamodb/expression/projection.go
service/dynamodb/expression/projection_test.go

Implement Projection Expression

---

service/dynamodb/expression/condition_test.go
service/dynamodb/expression/expression.go
service/dynamodb/expression/expression_test.go
service/dynamodb/expression/key_condition.go
service/dynamodb/expression/key_condition_test.go
service/dynamodb/expression/operand.go
service/dynamodb/expression/operand_test.go
service/dynamodb/expression/projection_test.go

Implement Key Condition Expression

---

models/apis/autoscaling/2011-01-01/docs-2.json
service/autoscaling/api.go

Corrects documentation for PutScalingPolicy.AutoScalingGroupName
Fix #1474

service/autoscaling: Documenation Update

---

example/service/dynamodb/expression/readme.md
example/service/dynamodb/expression/scan.go

Create a working example for expression package

---

service/dynamodb/doc_custom.go
service/dynamodb/dynamodbattribute/doc.go
service/dynamodb/expression/condition.go
service/dynamodb/expression/error.go
service/dynamodb/expression/examples_test.go

Minor updates to the the DynamoDB expression package's docs and examples.

Doc Fixups for expressions

---

private/protocol/restjson/build_bench_test.go
private/protocol/restxml/build_bench_test.go

Updates the format of the REST JSON and XML benchmarks to be readable. RESTJSON benchmarks were updated to more accurately bench building of the protocol.

private/protocol: Update format of REST JSON and XMl benchmarks

---

awstesting/integration/customizations/s3/s3crypto/stepdef.go
awstesting/performance/init.go

Fixes the integration test `t` not defined.

Fix integration tests undefined value

---

service/s3/s3crypto/aes_gcm_content_cipher_test.go
service/s3/s3crypto/aes_gcm_test.go
service/s3/s3crypto/cipher_test.go
service/s3/s3crypto/cipher_util_test.go
service/s3/s3crypto/decryption_client_test.go
service/s3/s3crypto/encryption_client_test.go
service/s3/s3crypto/hash_io_test.go
service/s3/s3crypto/helper_test.go
service/s3/s3crypto/key_handler_test.go
service/s3/s3crypto/kms_key_handler_test.go
service/s3/s3crypto/mat_desc_test.go
service/s3/s3crypto/strategy_test.go

service/s3/s3crypto: removing testing package from s3crypto

---

service/cognitoidentity/customizations_test.go
service/route53/unmarshal_error_leak_test.go
service/route53/unmarshal_error_test.go
service/s3/bucket_location_test.go
service/s3/customizations_test.go
service/s3/platform_handlers_go1.6_test.go
service/s3/sse_test.go
service/s3/statusok_error_test.go
service/s3/unmarshal_error_leak_test.go

service/*: removing testing package

---

aws/awsutil/copy_test.go
aws/awsutil/equal_test.go
aws/awsutil/path_value_test.go
aws/signer/v4/functional_1_5_test.go
aws/signer/v4/header_rules_test.go
aws/types_test.go

aws/awsutil: removing test dependencies

---

private/model/api/api.go

private/model/api: helper method to return whether or not a service has crosslinking

---

service/dynamodb/dynamodbattribute/decode.go
service/dynamodb/dynamodbattribute/encode.go
service/dynamodb/dynamodbattribute/marshaler_test.go

service/dynamodb/dynamodbattribute: fixes bug to handle array types marshaling

---

models/protocol_tests/input/ec2.json
models/protocol_tests/input/json.json
models/protocol_tests/input/query.json
models/protocol_tests/input/rest-xml.json
models/protocol_tests/output/ec2.json
models/protocol_tests/output/json.json
models/protocol_tests/output/query.json
models/protocol_tests/output/rest-xml.json
private/protocol/ec2query/build_test.go
private/protocol/ec2query/unmarshal_test.go
private/protocol/jsonrpc/build_test.go
private/protocol/jsonrpc/unmarshal_test.go
private/protocol/query/build_test.go
private/protocol/query/unmarshal_test.go
private/protocol/restxml/build_test.go
private/protocol/restxml/unmarshal_test.go

Update SDK protocol tests to include Enum validation

Update SDK protocol tests to include enum validation

---

models/protocol_tests/input/ec2.json
models/protocol_tests/input/json.json
models/protocol_tests/input/query.json
models/protocol_tests/input/rest-json.json
models/protocol_tests/input/rest-xml.json
models/protocol_tests/output/ec2.json
models/protocol_tests/output/json.json
models/protocol_tests/output/query.json
models/protocol_tests/output/rest-json.json
private/protocol/ec2query/build_test.go
private/protocol/restjson/build_test.go
private/protocol/restjson/unmarshal_test.go

Sync protocol tests up with updated versions for Enum tests.

Update protocol tests with latest version

---

example/aws/endpoints/customEndpoint/customEndpoint.go

fix simple typo

---

service/s3/s3manager/batch.go
service/s3/s3manager/batch_test.go

service/s3/s3manager: Fix check for nil OrigErr in Error()

---

CHANGELOG_PENDING.md

Add pending change log changes.

---

private/model/api/example_test.go
private/model/api/examples_builder.go
service/ec2/examples_test.go
service/lexmodelbuildingservice/examples_test.go
service/route53/examples_test.go
service/s3/examples_test.go
service/ses/examples_test.go
service/snowball/examples_test.go
service/waf/examples_test.go
service/wafregional/examples_test.go

This fixes an issue where list of collection or struct types were omitting fields.

private/model/api: bug fix with some examples excluding fields

---

service/s3/s3manager/batch.go
service/s3/s3manager/batch_1_7_test.go

service/s3/s3manager: batch delete will now utilize context

---

README.md

Updating README.md to have correct link

---

.travis.yml

Adds OSX to the travis test matrix.

Add OSX test to travis test matrix

---

doc-src/aws-godoc/templates/godoc.html

Adds a GDPR banner for the SDK's doc templates.

docs: Add GDPR banner to docs template

---

CHANGELOG.md
aws/version.go

Release v1.13.59

---

Makefile
awstesting/sandbox/Dockerfile.test.go1.10

Adds sandbox testing docker file for Go 1.10.

Add Go 1.10 sandbox testing Dockerfile

---

go.mod
go.sum
service/s3/s3manager/download.go

Adds documentation for downloading object sequentially with the S3 download manager.

service/s3/s3manager: Add doc for sequential download

---

awstesting/integration/customizations/s3/s3manager/integration_test.go
awstesting/integration/smoke/glacier/glacier.feature

awstesting/integration: fixing compiler errors in integration test and glacier test

---

private/protocol/restjson/restjson.go

private/protocol/restjson/restjson: Use json.Decoder to decrease memory allocation

---

private/protocol/jsonrpc/jsonrpc.go

private/protocol/jsonrpc/jsonrpc: Use json.Decoder to decrease memory allocation

---

.travis.yml
Makefile
awstesting/sandbox/Dockerfile.test.go1.11

Add Go 1.11 CI tests

---

Makefile
awstesting/integration/customizations/s3/s3manager/integration_test.go
awstesting/integration/customizations/s3/s3manager/shared_test.go
awstesting/integration/customizations/s3/shared.go
awstesting/integration/customizations/s3/shared_test.go

Adds additional logging to the S3 integration tests. Also refactors the shared setup and teardown logic to be consistent between s3 and s3manager integration tests.

awstesting: Add additional logging to S3 integration tests

---

internal/ini/ini_parser.go
internal/ini/testdata/valid/arn_profile
internal/ini/testdata/valid/arn_profile_expected
internal/ini/walker_test.go

internal/ini: fixing bug where ':' was not valid in the profile

---

aws/endpoints/decode.go
awstesting/integration/customizations/s3control/public_lockdown_test.go
awstesting/integration/customizations/s3control/shared_test.go
awstesting/integration/customizations/s3control/stub.go
private/model/api/customization_passes.go
private/model/api/operation.go

private/model/api: adding support for s3 control support

---

.travis.yml

Updates the CI test scripts for windows to investigate the windows Travis build failures.

Update CI test scripts for windows

---

service/sqs/checksums.go
service/sqs/checksums_test.go

Adds additional test of the SQS batch checksum validation.
Related to v2: aws/aws-sdk-go-v2#239

service/sqs: Add batch checksum validation test

---

CHANGELOG.md
aws/endpoints/defaults.go
aws/version.go
models/endpoints/endpoints.json

* `aws/endpoints`: Fix incorrect AWS Organizations global endpoint
* Fixes the endpoint metadata for the AWS Organization in [Release v1.19.16](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.16)

Release v1.19.17 (2019-04-24)

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general_issue.md

Moving existing issue template to general issue template, adding template for feature requests.

Replacing single issue template with feature request + general templates

---

service/s3/s3manager/download.go

… and Downloader.DownloadWithContext()

service/s3/s3manager: Clarify return values for Downloader methods

---

aws/session/env_config_test.go

Ran gofmt to fix two simple code formatting issues.

Gofmt code

---

aws/request/request.go
aws/session/credentials.go

Can't see anything that still uses these.

Removed unused global variables

---

aws/request/request_test.go

No need to convert RetryCount.

Avoid unnecessary conversion

---

awstesting/integration/performance/s3GetObject/README.md
awstesting/integration/performance/s3GetObject/client.go
awstesting/integration/performance/s3GetObject/config.go
awstesting/integration/performance/s3GetObject/logger.go
awstesting/integration/performance/s3GetObject/main.go
awstesting/integration/performance/s3GetObject/trace.go
awstesting/integration/performance/s3UploadManager/README.md
awstesting/integration/performance/s3UploadManager/client.go
awstesting/integration/performance/s3UploadManager/config.go
awstesting/integration/performance/s3UploadManager/main.go
awstesting/integration/performance/s3UploadManager/metric.go

Adds testing utilities to the SDK for evaluating performance of the SDK with Amazon S3.

awstesting: Add integration performance test utils for S3

---

service/s3/doc_custom.go

service/s3: Show how to disable URI cleaning in s3 docs

---

aws/ec2metadata/service.go

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>

aws/ec2metadata: Fix typo in error message

---

private/protocol/rest/unmarshal.go
private/protocol/restxml/restxml.go

fixed the nil check bug at "private/protocol/rest/unmarshal.go" and minor change in "private/protocol/restxml/restxml.go"

private/protocol: Fix checks for nil during REST and RESTXML unmarshal

---

CHANGELOG_PENDING.md
models/protocol_tests/output/rest-json.json
models/protocol_tests/output/rest-xml.json
private/protocol/rest/unmarshal.go
private/protocol/restjson/unmarshal_test.go
private/protocol/restxml/unmarshal_test.go

Adds RESTJSON and RESTXML protocol tests for blob headers.
Related to #750

private/protocol Add protocol tests for blob types and headers

---

CHANGELOG_PENDING.md
Makefile

Enables verbose logging for continuous integration tests.

Enable verbose output for CI tests

---

awstesting/integration/performance/s3UploadManager/main.go
awstesting/integration/performance/s3UploadManager/main_test.go

Adds CLI configuration options for controlling the benchmarking configuration options for the S3UploadManager performance package.

awstesting/integration/performance/s3UploadManager: CLI Configurable Benchmarking Options

---

README.md

Changed wording in README.md for clarity

---

service/dataexchange/api.go
service/sesv2/api.go

Regenerates the service models that were updated prior to the merge of #2942

Regenerate Services from Latest Models

---

CHANGELOG_PENDING.md
service/s3/s3crypto/aes_gcm.go
service/s3/s3crypto/aes_gcm_test.go

Return 0 at error, cause did not wrote []byte.

return 0 at read error #2999

---

CHANGELOG_PENDING.md

Fixes formatting issue in CHANGELOG_PENDING.md

Fix CHANGELOG_PENDING.md formatting

---

private/protocol/eventstream/decode.go
private/protocol/eventstream/eventstreamtest/testing.go
service/transcribestreamingservice/eventstream_writer_test.go

Add event stream unit-testing.

Add EventStream Unit Testing

---

private/model/api/eventstream.go

Adds support for APIs to share event streams across multiple operations, and round tripped.

Add support for streams shared across operations

---

CHANGELOG_PENDING.md

Add CHANGELOG_PENDING.md entry for Amazon Transcribe Streaming support

---

service/iotdataplane/endpoint_example_test.go
service/iotdataplane/example_endpoint_test.go
service/mediastoredata/endpoint_example_test.go
service/mediastoredata/example_endpoint_test.go

* Modifies custom integration test for `Mediastoredata` & `IoTDataPlane` to be examples

`service`: modifies custom integration test to be examples

---

CHANGELOG_PENDING.md

Updates change log for feature entry for generated API errors.

Add changelog feature entry for generated API error fix

---

service/s3/s3crypto/decryption_client.go
service/s3/s3crypto/encryption_client.go

Adds S3crypto value to the user-agent header when using the S3 crypto clients.

service/s3/s3crypto: Add User-Agent Header

---

service/dynamodb/expression/expression_test.go
service/dynamodb/expression/operand.go

service/dynamodb/expression - Documentation update for expression.Value when using empty slice

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/questions-help.md

Fix label applied to issues created with `Bug report` template, fix URLs in `Questions / Help` issue template.

Fix bug report & guidance issue templates

---

aws/endpoints/decode.go
aws/endpoints/defaults.go

Generate Dualstack endpoints for aws-cn and aws-us-gov partitions.

Generate Dualstack endpoints for aws-cn and aws-us-gov partitions

---

CHANGELOG_PENDING.md

Fix CHANGELOG_PENDING.md entry

---

CHANGELOG.md

* Updates change-log entry for service/organizations.

`service/organizations`: fix changelog 

---

service/s3/endpoint_test.go

* updates test for accesspoint to use custom endpoint resolver
* This fixes the accesspoint test for fips endpoint

updates test for accesspoint using fips to use custom endpoint resolver

---

example/service/rds/rdsutils/authentication/README.md
example/service/rds/rdsutils/authentication/iam_authentication.go
go.mod
go.sum

Fixes https://github.com/aws/aws-sdk-go/issues/3548
```
$ go run -tags example ./example/service/rds/rdsutils/authentication/iam_authentication.go us-west-2 user dbname localhost arn:aws:iam::805114051414:user/sample
Successfully opened connection to database
```

Removed direct dependency of mysql

---

README.md

Added the version maintenance policy and matrix to the Readme.

version maintenance policy

---

.github/workflows/stale_issues.yml

setting debug mode and dry run to see what's broken.

Update stale_issues.yml 

---

CHANGELOG_PENDING.md

Add CHANGELOG_PENDING.md for AWS SSO Credential Provider.

Add CHANGELOG_PENDING.md for AWS SSO Credential Provider

---

.github/workflows/stale_issues.yml

version change may have fixed the issue, but to be sure I'm leaving the loglevel as debug for the next run.

Stale Action fix

---

service/lexmodelsv2/cust_integ_test.go
service/lexmodelsv2/customizations_test.go

Fixes the unit tests for the API's customizations of old versions of go.

service/lexmodelsv2: Fixup unit test for Go 1.5 and 1.6

---

CHANGELOG.md
CHANGELOG_PENDING.md
aws/version.go

* `service/lookoutmetrics`: Fixes handling of API requests.
* Fix SDK's serialization of request to include expected Content-Type header.

Release v1.38.6 (2021-03-25)

---

README.md

Adds build badge for GitHub actions to readme.

Add build badge to readme.

---

example/aws/endpoints/customEndpoint/customEndpoint.go

Updates example for custom endpoint resolver

Updates example for custom endpoint resolver

---

aws/ec2metadata/api_test.go

Adds an additional unit test to verify that the EC2 IMDS token is refreshed when the operation receives a 401 HTTP status code.

aws/ec2metadata: Add test to verify token refresh for 401

---

aws/signer/v4/v4.go

Fixes typo in documentation for SignSDKRequest.

aws/signer/v4: Fixup documentation for SignSDKRequest

---

CHANGELOG_PENDING.md
models/apis/iot-data/2015-05-28/api-2.json
models/apis/iot-data/2015-05-28/docs-2.json
models/apis/iot-data/2015-05-28/paginators-1.json
service/iotdataplane/api.go
service/iotdataplane/doc.go
service/iotdataplane/iotdataplaneiface/interface.go

Updated IoT Data service model.

IoT Data Model Updates

---

models/protocol_tests/input/rest-json.json
private/protocol/restjson/build_test.go

Updates the SDK's REST-JSON protocol tests to add additional payload/content-type cases.

Update SDK's REST-JSON protocol tests to add additional cases

---

go.mod
go.sum

Updates the `golang.org/x/net` package to the latest version.

Updated golang.org/x/net package to latest version.

---

Makefile

Disable regabi due to stability issues during codegen

---

private/model/api/smoke.go
service/waf/integ_test.go
service/wafregional/integ_test.go

Remove WAF smoke test

---

aws/request/retryer.go

Fix word repetition in comment

---

private/protocol/eventstream/eventstreamapi/transport.go

Fixes docstring for new `ApplyHTTPTransportFixes` function added to `eventstreampapi` package.

eventstreamapi: fixup golint function docstring

---

private/model/api/smoke.go

Customize Iot Data Plane Smoke Tests

---

.github/workflows/go.yml
awstesting/sandbox/Dockerfile.test.go1.19
private/model/api/example_test.go
service/s3/s3manager/download.go
service/s3/s3manager/writer_read_from.go

Updates the SDK's CI actions to include go1.19.

Update CI to include Go 1.19

---

models/apis/kms/2014-11-01/examples-1.json

There was a incorrectly modeled shape in KMS example documentation causing code generation issues. This correctly updates the model.

Fix KMS example models.

---

.changelog/74c9af99629e453b97a0af6251efd414.json
aws/endpoints/defaults.go
models/endpoints/endpoints.json

The endpoints for kendra-ranking were incorrect. This fixes that.

Fix endpoints for kendra-ranking

---

CHANGELOG_PENDING.md

fix pending changelog

---

CHANGELOG.md

fix Glue release notes

---

.github/workflows/go.yml

Run workflows on features to support workflow testing on long running (multiple PRs) features

add feature workflows

---

CHANGELOG_PENDING.md
private/protocol/rest/build.go
private/protocol/rest/build_test.go

fix header serialization of empty enum lists in restxml

---

.github/workflows/stale_issues.yml

update time to ancient

---

service/s3/cust_integ_shared_test.go

fix minor typo cust_integ_shared_test.go
